#pragma once

ZEN3_FUNCDEF_UCODE(vpermq)
ZEN3_FUNCDEF_UCODE(vpermd)
ZEN3_FUNCDEF_UCODE(vpmovzxbq)
ZEN3_FUNCDEF_UCODE(vpclmulqdq)
ZEN3_FUNCDEF_UCODE(vmpsadbw)
ZEN3_FUNCDEF_UCODE(vdppd)
ZEN3_FUNCDEF_UCODE(vphaddd)
ZEN3_FUNCDEF_UCODE(movq2dq)

ZEN3_FUNCDEF_UCODE(vhaddpd)
ZEN3_FUNCDEF_UCODE(vcvtps2pd)
ZEN3_FUNCDEF_UCODE(vcvtpd2ps)

ZEN3_FUNCDEF_UCODE(vdivpd)
ZEN3_FUNCDEF_UCODE(vdivps)
ZEN3_FUNCDEF_UCODE(vdivsd)
ZEN3_FUNCDEF_UCODE(vdivss)

ZEN3_FUNCDEF_UCODE(vsqrtpd)
ZEN3_FUNCDEF_UCODE(vsqrtps)
ZEN3_FUNCDEF_UCODE(vsqrtsd)
ZEN3_FUNCDEF_UCODE(vsqrtss)

ZEN3_FUNCDEF_UCODE(fsqrt32)
ZEN3_FUNCDEF_UCODE(fsqrt64)
ZEN3_FUNCDEF_UCODE(fsqrt80)
ZEN3_FUNCDEF_UCODE(fdiv32)
ZEN3_FUNCDEF_UCODE(fdiv64)
ZEN3_FUNCDEF_UCODE(fdiv80)

