#include "stdafx.h"
using namespace std;

zen3_methods zen3_avx[] = {
	ZEN3_FUNCDECL0(-- Port01 FP (2 read op) --)
	ZEN3_FUNCDECL(VMULPD x<-x1 x1,				vmulpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMULPD y<-y1 y1,				vmulpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VMULPS x<-x1 x1,				vmulps,				2xmm2xmm)
	ZEN3_FUNCDECL(VMULPS y<-y1 y1,				vmulps,				2ymm2ymm)
	ZEN3_FUNCDECL(VMULSD x<-x1 x1,				vmulsd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMULSS x<-x1 x1,				vmulss,				2xmm2xmm)
	ZEN3_FUNCDECL(VRCPPS x<-x,					vrcpps,				xmm2xmm)
	ZEN3_FUNCDECL(VRCPPS y<-y,					vrcpps,				ymm2ymm)
	ZEN3_FUNCDECL(VRCPSS x<-x1 x1,				vrcpss,				2xmm2xmm)
	ZEN3_FUNCDECL(VRSQRTPS x<-x,				vrsqrtps,			xmm2xmm)
	ZEN3_FUNCDECL(VRSQRTPS y<-y,				vrsqrtps,			ymm2ymm)
	ZEN3_FUNCDECL(VRSQRTSS x<-x1 x1,			vrsqrtss,			2xmm2xmm)
	ZEN3_FUNCDECL0(---- Port01 (3 read op) ---)
	ZEN3_FUNCDECL(VPBLENDVB x1<-x1 x1 x1,		vpblendvb,			3xmm2xmm)
	ZEN3_FUNCDECL(VPBLENDVB y1<-y1 y1 y1,		vpblendvb,			3ymm2ymm)
	ZEN3_FUNCDECL(VBLENDVPD x1<-x1 x1 x1,		vblendvpd,			3xmm2xmm)
	ZEN3_FUNCDECL(VBLENDVPD y1<-y1 y1 y1,		vblendvpd,			3ymm2ymm)
	ZEN3_FUNCDECL(VBLENDVPS x1<-x1 x1 x1,		vblendvps,			3xmm2xmm)
	ZEN3_FUNCDECL(VBLENDVPS y1<-y1 y1 y1,		vblendvps,			3ymm2ymm)
	ZEN3_FUNCDECL(VPBLENDVB x1<-x1 x2 x3,		vpblendvb,			3xmm2xmmRot)
	ZEN3_FUNCDECL(VPBLENDVB y1<-x1 y2 y3,		vpblendvb,			3ymm2ymmRot)
	ZEN3_FUNCDECL(VBLENDVPD x1<-x1 x2 x3,		vblendvpd,			3xmm2xmmRot)
	ZEN3_FUNCDECL(VBLENDVPD y1<-x1 y2 y3,		vblendvpd,			3ymm2ymmRot)
	ZEN3_FUNCDECL(VBLENDVPS x1<-x1 x2 x3,		vblendvps,			3xmm2xmmRot)
	ZEN3_FUNCDECL(VBLENDVPS y1<-x1 y2 y3,		vblendvps,			3ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADDSUB132PD x1<-x1 x1 x1,	vfmaddsub132pd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB132PD y1<-y1 y1 y1,	vfmaddsub132pd,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADDSUB132PS x1<-x1 x1 x1,	vfmaddsub132ps,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB132PS y1<-y1 y1 y1,	vfmaddsub132ps,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADD132SD x1<-x1 x1 x1,		vfmadd132sd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADD132SS x1<-x1 x1 x1,		vfmadd132ss,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB213PD x1<-x1 x1 x1,	vfmaddsub213pd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB213PD y1<-y1 y1 y1,	vfmaddsub213pd,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADDSUB213PS x1<-x1 x1 x1,	vfmaddsub213ps,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB213PS y1<-y1 y1 y1,	vfmaddsub213ps,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADD213SD x1<-x1 x1 x1,		vfmadd213sd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADD213SS x1<-x1 x1 x1,		vfmadd213ss,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB231PD x1<-x1 x1 x1,	vfmaddsub231pd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB231PD y1<-y1 y1 y1,	vfmaddsub231pd,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADDSUB231PS x1<-x1 x1 x1,	vfmaddsub231ps,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB231PS y1<-y1 y1 y1,	vfmaddsub231ps,		2ymm2ymm)
	ZEN3_FUNCDECL(VFMADD231SD x1<-x1 x1 x1,		vfmadd231sd,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADD231SS x1<-x1 x1 x1,		vfmadd231ss,		2xmm2xmm)
	ZEN3_FUNCDECL(VFMADDSUB132PD x1<-x1 x2 x3,	vfmaddsub132pd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB132PD y1<-y1 y2 y3,	vfmaddsub132pd,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADDSUB132PS x1<-x1 x2 x3,	vfmaddsub132ps,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADD132SD x1<-x1 x2 x3,		vfmadd132sd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADD132SS x1<-x1 x2 x3,		vfmadd132ss,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB132PS y1<-y1 y2 y3,	vfmaddsub132ps,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADDSUB213PD x1<-x1 x2 x3,	vfmaddsub213pd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB213PD y1<-y1 y2 y3,	vfmaddsub213pd,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADDSUB213PS x1<-x1 x2 x3,	vfmaddsub213ps,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB213PS y1<-y1 y2 y3,	vfmaddsub213ps,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADD213SD x1<-x1 x2 x3,		vfmadd213sd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADD213SS x1<-x1 x2 x3,		vfmadd213ss,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB231PD x1<-x1 x2 x3,	vfmaddsub231pd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB231PD y1<-y1 y2 y3,	vfmaddsub231pd,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADDSUB231PS x1<-x1 x2 x3,	vfmaddsub231ps,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADDSUB231PS y1<-y1 y2 y3,	vfmaddsub231ps,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VFMADD231SD x1<-x1 x1 x1,		vfmadd231sd,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VFMADD231SS x1<-x1 x1 x1,		vfmadd231ss,		2xmm2xmmRot)
	ZEN3_FUNCDECL0(-------- Port23 FP --------)
	ZEN3_FUNCDECL(VADDPD x<-x1 x1,				vaddpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VADDPD y<-y1 y1,				vaddpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VADDPS x<-x1 x1,				vaddps,				2xmm2xmm)
	ZEN3_FUNCDECL(VADDPS y<-y1 y1,				vaddps,				2ymm2ymm)
	ZEN3_FUNCDECL(VADDSD x<-x1 x1,				vaddsd,				2xmm2xmm)
	ZEN3_FUNCDECL(VADDSS x<-x1 x1,				vaddss,				2xmm2xmm)
	ZEN3_FUNCDECL(VSUBPD x<-x1 x1,				vsubpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VSUBPD y<-y1 y1,				vsubpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VSUBPS x<-x1 x1,				vsubps,				2xmm2xmm)
	ZEN3_FUNCDECL(VSUBPS y<-y1 y1,				vsubps,				2ymm2ymm)
	ZEN3_FUNCDECL(VSUBSD x<-x1 x1,				vsubsd,				2xmm2xmm)
	ZEN3_FUNCDECL(VSUBSS x<-x1 x1,				vsubss,				2xmm2xmm)
	ZEN3_FUNCDECL(VADDSUBPD x<-x1 x1,			vaddsubpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VADDSUBPD y<-y1 y1,			vaddsubpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VADDSUBPS x<-x1 x1,			vaddsubps,			2xmm2xmm)
	ZEN3_FUNCDECL(VADDSUBPS y<-y1 y1,			vaddsubps,			2ymm2ymm)
	ZEN3_FUNCDECL(VROUNDPD x<-x i,				vroundpd,			xmmi2xmm)
	ZEN3_FUNCDECL(VROUNDPD y<-y i,				vroundpd,			ymmi2ymm)
	ZEN3_FUNCDECL(VROUNDPS x<-x i,				vroundps,			xmmi2xmm)
	ZEN3_FUNCDECL(VROUNDPS y<-y i,				vroundps,			ymmi2ymm)
	ZEN3_FUNCDECL(VROUNDSD x<-x1 x1 i,			vroundsd,			2xmmi2xmm)
	ZEN3_FUNCDECL(VROUNDSS x<-x1 x1 i,			vroundss,			2xmmi2xmm)
	ZEN3_FUNCDECL(VCVTPS2DQ x<-x,				vcvtps2dq,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTPS2DQ y<-y,				vcvtps2dq,			ymm2ymm)
	ZEN3_FUNCDECL(VCVTPS2PD x<-x,				vcvtps2pd,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTPD2PS x<-x,				vcvtpd2ps,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTPD2DQ x<-x,				vcvtpd2dq,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTDQ2PS x<-x,				vcvtdq2ps,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTDQ2PS y<-y,				vcvtdq2ps,			ymm2ymm)
	ZEN3_FUNCDECL(VCVTDQ2PD x<-x,				vcvtdq2pd,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTPS2PH x<-x i,				vcvtps2ph,			xmmi2xmm)
	ZEN3_FUNCDECL(VCVTPH2PS x<-x,				vcvtph2ps,			xmm2xmm)
	ZEN3_FUNCDECL(VCVTSS2SD x<-x1 x1,			vcvtss2sd,			2xmm2xmm)
	ZEN3_FUNCDECL(VCVTSD2SS x<-x1 x1,			vcvtsd2ss,			2xmm2xmm)
	ZEN3_FUNCDECL(VMINPD x<-x1 x1,				vminpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMINPD y<-y1 y1,				vminpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VMINPS x<-x1 x1,				vminps,				2xmm2xmm)
	ZEN3_FUNCDECL(VMINPS y<-y1 y1,				vminps,				2ymm2ymm)
	ZEN3_FUNCDECL(VMINSD x<-x1 x1,				vminsd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMINSS x<-x1 x1,				vminss,				2xmm2xmm)
	ZEN3_FUNCDECL(VMAXPD x<-x1 x1,				vmaxpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMAXPD y<-y1 y1,				vmaxpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VMAXPS x<-x1 x1,				vmaxps,				2xmm2xmm)
	ZEN3_FUNCDECL(VMAXPS y<-y1 y1,				vmaxps,				2ymm2ymm)
	ZEN3_FUNCDECL(VMAXSD x<-x1 x1,				vmaxsd,				2xmm2xmm)
	ZEN3_FUNCDECL(VMAXSS x<-x1 x1,				vmaxss,				2xmm2xmm)
	ZEN3_FUNCDECL(VCMPEQPD x<-x1 x1,			vcmpeqpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VCMPEQPD y<-y1 y1,			vcmpeqpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VCMPEQPS x<-x1 x1,			vcmpeqps,			2xmm2xmm)
	ZEN3_FUNCDECL(VCMPEQPS y<-y1 y1,			vcmpeqps,			2ymm2ymm)
	ZEN3_FUNCDECL(VCMPEQSD x<-x1 x1,			vcmpeqsd,			2xmm2xmm)
	ZEN3_FUNCDECL(VCMPEQPS x<-x1 x1,			vcmpeqss,			2xmm2xmm)
	ZEN3_FUNCDECL0(-------- Port0123 FP ------)
	ZEN3_FUNCDECL(VANDPD x<-x1 x1,				vandpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VANDPD y<-y1 y1,				vandpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VANDPS x<-x1 x1,				vandps,				2xmm2xmm)
	ZEN3_FUNCDECL(VANDPS y<-y1 y1,				vandps,				2ymm2ymm)
	ZEN3_FUNCDECL(VANDNPD x<-x1 x2,				vandnpd,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VANDNPD y<-y1 y2,				vandnpd,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VANDNPS x<-x1 x2,				vandnps,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VANDNPS y<-y1 y2,				vandnps,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VORPD x<-x1 x1,				vorpd,				2xmm2xmm)
	ZEN3_FUNCDECL(VORPD y<-y1 y1,				vorpd,				2ymm2ymm)
	ZEN3_FUNCDECL(VORPS x<-x1 x1,				vorps,				2xmm2xmm)
	ZEN3_FUNCDECL(VORPS y<-y1 y1,				vorps,				2ymm2ymm)
	ZEN3_FUNCDECL(VXORPD x<-x1 x2,				vxorpd,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VXORPD y<-y1 y2,				vxorpd,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VXORPS x<-x1 x2,				vxorps,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VXORPS y<-y1 y2,				vxorps,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VBLENDPD x<-x1 x1 i,			vblendpd,			2xmmi2xmm)
	ZEN3_FUNCDECL(VBLENDPD y<-y1 y1 i,			vblendpd,			2ymmi2ymm)
	ZEN3_FUNCDECL0(------- Port0123 Int ------)
	ZEN3_FUNCDECL(VPAND x<-x1 x1,				vpand,				2xmm2xmm)
	ZEN3_FUNCDECL(VPAND y<-y1 y1,				vpand,				2ymm2ymm)
	ZEN3_FUNCDECL(VPANDN x<-x1 x2,				vpandn,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPANDN y<-y1 y2,				vpandn,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPOR x<-x1 x1,				vpor,				2xmm2xmm)
	ZEN3_FUNCDECL(VPOR y<-y1 y1,				vpor,				2ymm2ymm)
	ZEN3_FUNCDECL(VPXOR x<-x1 x2,				vpxor,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPXOR y<-y1 y2,				vpxor,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPBLENDD x<-x1 x1 i,			vpblendd,			2xmmi2xmm)
	ZEN3_FUNCDECL(VPBLENDD y<-y1 y1 i,			vpblendd,			2ymmi2ymm)
	ZEN3_FUNCDECL(VPBLENDW x<-x1 x1 i,			vpblendw,			2xmmi2xmm)
	ZEN3_FUNCDECL(VPBLENDW y<-y1 y1 i,			vpblendw,			2ymmi2ymm)
	ZEN3_FUNCDECL(VBLENDPS x<-x1 x1 i,			vblendps,			2xmmi2xmm)
	ZEN3_FUNCDECL(VBLENDPS y<-y1 y1 i,			vblendps,			2ymmi2ymm)
	ZEN3_FUNCDECL(VPADDB x<-x1 x1,				vpaddb,				2xmm2xmm)
	ZEN3_FUNCDECL(VPADDB y<-y1 y1,				vpaddb,				2ymm2ymm)
	ZEN3_FUNCDECL(VPADDW x<-x1 x1,				vpaddw,				2xmm2xmm)
	ZEN3_FUNCDECL(VPADDW y<-y1 y1,				vpaddw,				2ymm2ymm)
	ZEN3_FUNCDECL(VPADDD x<-x1 x1,				vpaddd,				2xmm2xmm)
	ZEN3_FUNCDECL(VPADDD y<-y1 y1,				vpaddd,				2ymm2ymm)
	ZEN3_FUNCDECL(VPADDQ x<-x1 x1,				vpaddq,				2xmm2xmm)
	ZEN3_FUNCDECL(VPADDQ y<-y1 y1,				vpaddq,				2ymm2ymm)
	ZEN3_FUNCDECL(VPSUBB x<-x1 x2,				vpsubb,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBB y<-y1 y2,				vpsubb,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPSUBW x<-x1 x2,				vpsubw,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBW y<-y1 y2,				vpsubw,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPSUBD x<-x1 x2,				vpsubd,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBD y<-y1 y2,				vpsubd,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPSUBQ x<-x1 x2,				vpsubq,				2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBQ y<-y1 y2,				vpsubq,				2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPEQB x<-x1 x2,			vpcmpeqb,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPEQB y<-y1 y2,			vpcmpeqb,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPEQW x<-x1 x2,			vpcmpeqw,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPEQW y<-y1 y2,			vpcmpeqw,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPEQD x<-x1 x2,			vpcmpeqd,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPEQD y<-y1 y2,			vpcmpeqd,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPGTB x<-x1 x2,			vpcmpgtb,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPGTB y<-y1 y2,			vpcmpgtb,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPGTW x<-x1 x2,			vpcmpgtw,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPGTW y<-y1 y2,			vpcmpgtw,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPGTD x<-x1 x2,			vpcmpgtd,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPGTD y<-y1 y2,			vpcmpgtd,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPGTQ x<-x1 x2,			vpcmpgtq,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPGTQ y<-y1 y2,			vpcmpgtq,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPMINSB x<-x1 x1,				vpminsb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINSB y<-y1 y1,				vpminsb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMINUB x<-x1 x1,				vpminub,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINUB y<-y1 y1,				vpminub,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMINSW x<-x1 x1,				vpminsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINSW y<-y1 y1,				vpminsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMINUW x<-x1 x1,				vpminuw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINUW y<-y1 y1,				vpminuw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMINSD x<-x1 x1,				vpminsd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINSD y<-y1 y1,				vpminsd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMINUD x<-x1 x1,				vpminud,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMINUD y<-y1 y1,				vpminud,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXSB x<-x1 x1,				vpmaxsb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXSB y<-y1 y1,				vpmaxsb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXUB x<-x1 x1,				vpmaxub,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXUB y<-y1 y1,				vpmaxub,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXSW x<-x1 x1,				vpmaxsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXSW y<-y1 y1,				vpmaxsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXUW x<-x1 x1,				vpmaxuw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXUW y<-y1 y1,				vpmaxuw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXSD x<-x1 x1,				vpmaxsd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXSD y<-y1 y1,				vpmaxsd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMAXUD x<-x1 x1,				vpmaxud,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMAXUD y<-y1 y1,				vpmaxud,			2ymm2ymm)
	ZEN3_FUNCDECL0(-------- Port01 Int -------)
	ZEN3_FUNCDECL(VPADDSB x<-x1 x1,				vpaddsb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPADDSB y<-y1 y1,				vpaddsb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPADDSW x<-x1 x1,				vpaddsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPADDSW y<-y1 y1,				vpaddsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSUBSB x<-x1 x2,				vpsubsb,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBSB y<-y1 y2,				vpsubsb,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPSUBSW x<-x1 x2,				vpsubsw,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPSUBSW y<-y1 y2,				vpsubsw,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPCMPEQQ x<-x1 x2,			vpcmpeqq,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VPCMPEQQ y<-y1 y2,			vpcmpeqq,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VPABSB x<-x,					vpabsb,				xmm2xmm)
	ZEN3_FUNCDECL(VPABSB y<-y,					vpabsb,				ymm2ymm)
	ZEN3_FUNCDECL(VPABSW x<-x,					vpabsw,				xmm2xmm)
	ZEN3_FUNCDECL(VPABSW y<-y,					vpabsw,				ymm2ymm)
	ZEN3_FUNCDECL(VPABSD x<-x,					vpabsd,				xmm2xmm)
	ZEN3_FUNCDECL(VPABSD y<-y,					vpabsd,				ymm2ymm)
	ZEN3_FUNCDECL(VPAVGB x<-x1 x1,				vpavgb,				2xmm2xmm)
	ZEN3_FUNCDECL(VPAVGB y<-y1 y1,				vpavgb,				2ymm2ymm)
	ZEN3_FUNCDECL(VPAVGW x<-x1 x1,				vpavgw,				2xmm2xmm)
	ZEN3_FUNCDECL(VPAVGW y<-y1 y1,				vpavgw,				2ymm2ymm)
	ZEN3_FUNCDECL(VPSIGNB x<-x1 x1,				vpsignb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSIGNB y<-y1 y1,				vpsignb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSIGNW x<-x1 x1,				vpsignw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSIGNW y<-y1 y1,				vpsignw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSIGND x<-x1 x1,				vpsignd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSIGND y<-y1 y1,				vpsignd,			2ymm2ymm)
	ZEN3_FUNCDECL(VAESENC x<-x1 x1,				vaesenc,			2xmm2xmm)
	ZEN3_FUNCDECL(VAESENC y<-y1 y1,				vaesenc,			2ymm2ymm)
	ZEN3_FUNCDECL(VAESENCLAST x<-x1 x1,			vaesenclast,		2xmm2xmm)
	ZEN3_FUNCDECL(VAESENCLAST y<-y1 y1,			vaesenclast,		2ymm2ymm)
	ZEN3_FUNCDECL(VAESDEC x<-x1 x1,				vaesdec,			2xmm2xmm)
	ZEN3_FUNCDECL(VAESDEC y<-y1 y1,				vaesdec,			2ymm2ymm)
	ZEN3_FUNCDECL(VAESDECLAST x<-x1 x1,			vaesdeclast,		2xmm2xmm)
	ZEN3_FUNCDECL(VAESDECLAST y<-y1 y1,			vaesdeclast,		2ymm2ymm)
	ZEN3_FUNCDECL(VAESENC x<-x1 x2,				vaesenc,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VAESENC y<-y1 y2,				vaesenc,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VAESENCLAST x<-x1 x2,			vaesenclast,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VAESENCLAST y<-y1 y2,			vaesenclast,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VAESDEC x<-x1 x2,				vaesdec,			2xmm2xmmRot)
	ZEN3_FUNCDECL(VAESDEC y<-y1 y2,				vaesdec,			2ymm2ymmRot)
	ZEN3_FUNCDECL(VAESDECLAST x<-x1 x2,			vaesdeclast,		2xmm2xmmRot)
	ZEN3_FUNCDECL(VAESDECLAST y<-y1 y2,			vaesdeclast,		2ymm2ymmRot)
	ZEN3_FUNCDECL(VAESIMC x<-x,					vaesimc,			xmm2xmm)
	ZEN3_FUNCDECL(VAESKEYGENASSIST x-<x i,		vaeskeygenassist,	xmmi2xmm)
	ZEN3_FUNCDECL(VPHMINPOSUW x<-x,				vphminposuw,		xmm2xmm)
	ZEN3_FUNCDECL(VPERMILPD x<-x1 x1,			vpermilpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPERMILPD y<-y1 y1,			vpermilpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPERMILPS x<-x1 x1,			vpermilps,			2xmm2xmm)
	ZEN3_FUNCDECL(VPERMILPS y<-y1 y1,			vpermilps,			2ymm2ymm)
	ZEN3_FUNCDECL0(-------- Port12 Int -------)
	ZEN3_FUNCDECL(VPSLLVD x<-x1 x2,				vpsllvd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSLLVD y<-y1 y2,				vpsllvd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSRLVD x<-x1 x2,				vpsrlvd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSRLVD y<-y1 y2,				vpsrlvd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSRAVD x<-x1 x2,				vpsravd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSRAVD y<-y1 y2,				vpsravd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSLLVQ x<-x1 x2,				vpsllvq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSLLVQ y<-y1 y2,				vpsllvq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSRLVQ x<-x1 x2,				vpsrlvq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSRLVQ y<-y1 y2,				vpsrlvq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSLLW x<-x1 x2,				vpslld,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSLLW y<-y1 x2,				vpslld,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSRLW x<-x1 x2,				vpsrld,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSRLW y<-y1 x2,				vpsrld,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSRAW x<-x1 x2,				vpsrad,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSRAW y<-y1 x2,				vpsrad,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSLLD x<-x1 x2,				vpslld,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSLLD y<-y1 x2,				vpslld,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSRLD x<-x1 x2,				vpsrld,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSRLD y<-y1 x2,				vpsrld,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSRAD x<-x1 x2,				vpsrad,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSRAD y<-y1 x2,				vpsrad,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSLLQ x<-x1 x2,				vpsllq,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSLLQ y<-y1 x2,				vpsllq,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSRLQ x<-x1 x2,				vpsrlq,				2xmm2xmm)
	ZEN3_FUNCDECL(VPSRLQ y<-y1 x2,				vpsrlq,				xmmymm2ymm)
	ZEN3_FUNCDECL(VPSLLW x<-x i,				vpsllw,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSLLW y<-y i,				vpsllw,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSRLW x<-x i,				vpsrlw,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSRLW y<-y i,				vpsrlw,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSRAW x<-x i,				vpsraw,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSRAW y<-y i,				vpsraw,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSLLD x<-x i,				vpslld,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSLLD y<-y i,				vpslld,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSRLD x<-x i,				vpsrld,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSRLD y<-y i,				vpsrld,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSRAD x<-x i,				vpsrad,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSRAD y<-y i,				vpsrad,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSLLQ x<-x i,				vpsllq,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSLLQ y<-y i,				vpsllq,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSRLQ x<-x i,				vpsrlq,				xmmi2xmm)
	ZEN3_FUNCDECL(VPSRLQ y<-y i,				vpsrlq,				ymmi2ymm)
	ZEN3_FUNCDECL(VPSLLDQ x<-x i,				vpslldq,			xmmi2xmm)
	ZEN3_FUNCDECL(VPSLLDQ y<-y i,				vpslldq,			ymmi2ymm)
	ZEN3_FUNCDECL(VPSRLDQ x<-x i,				vpsrldq,			xmmi2xmm)
	ZEN3_FUNCDECL(VPSRLDQ y<-y i,				vpsrldq,			ymmi2ymm)
	ZEN3_FUNCDECL(VPUNPCKLBW x<-x1 x1,			vpunpcklbw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKLBW y<-y1 y1,			vpunpcklbw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKHBW x<-x1 x1,			vpunpckhbw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKHBW y<-y1 y1,			vpunpckhbw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKLWD x<-x1 x1,			vpunpcklwd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKLWD y<-y1 y1,			vpunpcklwd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKHWD x<-x1 x1,			vpunpckhwd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKHWD y<-y1 y1,			vpunpckhwd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKLDQ x<-x1 x1,			vpunpckldq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKLDQ y<-y1 y1,			vpunpckldq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKHDQ x<-x1 x1,			vpunpckhdq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKHDQ y<-y1 y1,			vpunpckhdq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKLQDQ x<-x1 x1,			vpunpcklqdq,		2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKLQDQ y<-y1 y1,			vpunpcklqdq,		2ymm2ymm)
	ZEN3_FUNCDECL(VPUNPCKHQDQ x<-x1 x1,			vpunpckhqdq,		2xmm2xmm)
	ZEN3_FUNCDECL(VPUNPCKHQDQ y<-y1 y1,			vpunpckhqdq,		2ymm2ymm)
	ZEN3_FUNCDECL(VUNPCKLPS x<-x1 x1,			vunpcklps,			2xmm2xmm)
	ZEN3_FUNCDECL(VUNPCKLPS y<-y1 y1,			vunpcklps,			2ymm2ymm)
	ZEN3_FUNCDECL(VUNPCKHPS x<-x1 x1,			vunpckhps,			2xmm2xmm)
	ZEN3_FUNCDECL(VUNPCKHPS y<-y1 y1,			vunpckhps,			2ymm2ymm)
	ZEN3_FUNCDECL(VUNPCKLPD x<-x1 x1,			vunpcklpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VUNPCKLPD y<-y1 y1,			vunpcklpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VUNPCKHPD x<-x1 x1,			vunpckhpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VUNPCKHPD y<-y1 y1,			vunpckhpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VMOVHLPS x<-x1 x1,			vmovhlps,			2xmm2xmm)
	ZEN3_FUNCDECL(VMOVLHPS x<-x1 x1,			vmovlhps,			2xmm2xmm)
	ZEN3_FUNCDECL(VPACKSSWB x<-x1 x1,			vpacksswb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPACKSSWB y<-y1 y1,			vpacksswb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPACKUSWB x<-x1 x1,			vpackuswb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPACKUSWB y<-y1 y1,			vpackuswb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPACKSSDW x<-x1 x1,			vpackssdw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPACKSSDW y<-y1 y1,			vpackssdw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPACKUSDW x<-x1 x1,			vpackusdw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPACKUSDW y<-y1 y1,			vpackusdw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPERMILPD x<-x i,				vpermilpd,			xmmi2xmm)
	ZEN3_FUNCDECL(VPERMILPD y<-y i,				vpermilpd,			ymmi2ymm)
	ZEN3_FUNCDECL(VPERMILPS x<-x i,				vpermilps,			xmmi2xmm)
	ZEN3_FUNCDECL(VPERMILPS y<-y i,				vpermilps,			ymmi2ymm)
	ZEN3_FUNCDECL(VSHUFPD x<-x1 x1 i,			vshufpd,			2xmmi2xmm)
	ZEN3_FUNCDECL(VSHUFPD y<-y1 y1 i,			vshufpd,			2ymmi2ymm)
	ZEN3_FUNCDECL(VSHUFPS x<-x1 x1 i,			vshufps,			2xmmi2xmm)
	ZEN3_FUNCDECL(VSHUFPS y<-y1 y1 i,			vshufps,			2ymmi2ymm)
	ZEN3_FUNCDECL(VPSHUFB x<-x1 x1,				vpshufb,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSHUFB y<-y1 y1,				vpshufb,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSHUFLW x<-x i,				vpshuflw,			xmmi2xmm)
	ZEN3_FUNCDECL(VPSHUFLW y<-y i,				vpshuflw,			ymmi2ymm)
	ZEN3_FUNCDECL(VPSHUFHW x<-x i,				vpshufhw,			xmmi2xmm)
	ZEN3_FUNCDECL(VPSHUFHW y<-y i,				vpshufhw,			ymmi2ymm)
	ZEN3_FUNCDECL(VPSHUFD x<-x i,				vpshufd,			xmmi2xmm)
	ZEN3_FUNCDECL(VPSHUFD y<-y i,				vpshufd,			ymmi2ymm)
	ZEN3_FUNCDECL(VPALIGNR x<-x1 x1 i,			vpalignr,			2xmmi2xmm)
	ZEN3_FUNCDECL(VPALIGNR y<-y1 y1 i,			vpalignr,			2ymmi2ymm)
	ZEN3_FUNCDECL(VMOVDDUP x<-x,				vmovddup,			xmm2xmm)
	ZEN3_FUNCDECL(VMOVDDUP y<-y,				vmovddup,			ymm2ymm)
	ZEN3_FUNCDECL(VMOVSLDUP x<-x,				vmovsldup,			xmm2xmm)
	ZEN3_FUNCDECL(VMOVSLDUP y<-y,				vmovsldup,			ymm2ymm)
	ZEN3_FUNCDECL(VMOVSHDUP x<-x,				vmovshdup,			xmm2xmm)
	ZEN3_FUNCDECL(VMOVSHDUP y<-y,				vmovshdup,			ymm2ymm)
	ZEN3_FUNCDECL(VPBROADCASTB x<-x,			vpbroadcastb,		xmm2xmm)
	ZEN3_FUNCDECL(VPBROADCASTW x<-x,			vpbroadcastw,		xmm2xmm)
	ZEN3_FUNCDECL(VPBROADCASTD x<-x,			vpbroadcastd,		xmm2xmm)
	ZEN3_FUNCDECL(VPBROADCASTQ x<-x,			vpbroadcastq,		xmm2xmm)
	ZEN3_FUNCDECL(VBROADCASTSS x<-x,			vbroadcastss,		xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXBW x<-x,				vpmovzxbw,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXBD x<-x,				vpmovzxbd,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXBQ x<-x,				vpmovzxbq,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXWD x<-x,				vpmovzxwd,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXWQ x<-x,				vpmovzxwq,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVZXDQ x<-x,				vpmovzxdq,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXBW x<-x,				vpmovsxbw,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXBD x<-x,				vpmovsxbd,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXBQ x<-x,				vpmovsxbq,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXWD x<-x,				vpmovsxwd,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXWQ x<-x,				vpmovsxwq,			xmm2xmm)
	ZEN3_FUNCDECL(VPMOVSXDQ x<-x,				vpmovsxdq,			xmm2xmm)
	ZEN3_FUNCDECL(VINSERTPS x<-x1 x1 i,			vinsertps,			2xmmi2xmm)
	ZEN3_FUNCDECL0(-------- Port03 Int -------)
	ZEN3_FUNCDECL(VPMULHW x<-x1 x1,				vpmulhw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULHW y<-y1 y1,				vpmulhw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULHUW x<-x1 x1,			vpmulhuw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULHUW y<-y1 y1,			vpmulhuw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULHRSW x<-x1 x1,			vpmulhrsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULHRSW y<-y1 y1,			vpmulhrsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULLW x<-x1 x1,				vpmullw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULLW y<-y1 y1,				vpmullw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULLD x<-x1 x1,				vpmulld,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULLD y<-y1 y1,				vpmulld,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULDQ x<-x1 x1,				vpmuldq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULDQ y<-y1 y1,				vpmuldq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMULUDQ x<-x1 x1,			vpmuludq,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMULUDQ y<-y1 y1,			vpmuludq,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMADDWD x<-x1 x1,			vpmaddwd,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMADDWD y<-y1 y1,			vpmaddwd,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMADDUBSW x<-x1 x1,			vpmaddubsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPMADDUBSW y<-y1 y1,			vpmaddubsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VPSADBW x<-x1 x1,				vpsadbw,			2xmm2xmm)
	ZEN3_FUNCDECL(VPSADBW y<-y1 y1,				vpsadbw,			2ymm2ymm)
	ZEN3_FUNCDECL0(----- P0 (Cross-lanes) ----)
	ZEN3_FUNCDECL(VINSERTI128 y<-y x i,			vinserti128,		xmmymmi2ymm)
	ZEN3_FUNCDECL(VINSERTF128 y<-y x i,			vinsertf128,		xmmymmi2ymm)
	ZEN3_FUNCDECL(VINSERTI128 y<-y m128 i,		vinserti128,		m128ymmi2ymm)
	ZEN3_FUNCDECL(VINSERTF128 y<-y m128 i,		vinsertf128,		m128ymmi2ymm)
	ZEN3_FUNCDECL(VEXTRACTI128 x<-y i,			vextracti128,		ymmi2xmm)
	ZEN3_FUNCDECL(VEXTRACTF128 x<-y i,			vextractf128,		ymmi2xmm)
	ZEN3_FUNCDECL(VEXTRACTI128 m128<-y i,		vextracti128,		ymmi2m128)
	ZEN3_FUNCDECL(VEXTRACTF128 m128<-y i,		vextractf128,		ymmi2m128)
	ZEN3_FUNCDECL(VPERM2I128 y<-y y i,			vperm2i128,			2ymmi2ymm)
	ZEN3_FUNCDECL(VPERM2F128 y<-y y i,			vperm2f128,			2ymmi2ymm)
	ZEN3_FUNCDECL(VPERM2I128 y<-y m256 i,		vperm2i128,			m256ymmi2ymm)
	ZEN3_FUNCDECL(VPERM2F128 y<-y m256 i,		vperm2f128,			m256ymmi2ymm)
	ZEN3_FUNCDECL(VBROADCASTSS y<-x,			vbroadcastss,		xmm2ymm)
	ZEN3_FUNCDECL(VBROADCASTSD y<-x,			vbroadcastsd,		xmm2ymm)
	ZEN3_FUNCDECL(VPBROADCASTB y<-x,			vpbroadcastb,		xmm2ymm)
	ZEN3_FUNCDECL(VPBROADCASTW y<-x,			vpbroadcastw,		xmm2ymm)
	ZEN3_FUNCDECL(VPBROADCASTD y<-x,			vpbroadcastd,		xmm2ymm)
	ZEN3_FUNCDECL(VPBROADCASTQ y<-x,			vpbroadcastq,		xmm2ymm)
	ZEN3_FUNCDECL(VBROADCASTSS y<-m32,			vbroadcastss,		m32_2ymm)
	ZEN3_FUNCDECL(VBROADCASTSD y<-m64,			vbroadcastsd,		m64_2ymm)
	ZEN3_FUNCDECL(VPBROADCASTB y<-m8,			vpbroadcastb,		m8_2ymm)
	ZEN3_FUNCDECL(VPBROADCASTW y<-m16,			vpbroadcastw,		m16_2ymm)
	ZEN3_FUNCDECL(VPBROADCASTD y<-m32,			vpbroadcastd,		m32_2ymm)
	ZEN3_FUNCDECL(VPBROADCASTQ y<-m64,			vpbroadcastq,		m64_2ymm)
	ZEN3_FUNCDECL0(------ P1 (DIV/SQRT) ------)
	ZEN3_FUNCDECL(VDIVPD x<-x1 x2,				vdivpd,				2xmm2xmm2)
	ZEN3_FUNCDECL(VDIVPD y<-y1 y2,				vdivpd,				2ymm2ymm2)
	ZEN3_FUNCDECL(VDIVSD x<-x1 x2,				vdivsd,				2xmm2xmm2)
	ZEN3_FUNCDECL(VDIVPS x<-x1 x2,				vdivps,				2xmm2xmm2)
	ZEN3_FUNCDECL(VDIVPS y<-y1 y2,				vdivps,				2ymm2ymm2)
	ZEN3_FUNCDECL(VDIVSS y<-y1 y2,				vdivss,				2xmm2xmm2)
	ZEN3_FUNCDECL(VSQRTPD x<-x,					vsqrtpd,			xmm2xmm1)
	ZEN3_FUNCDECL(VSQRTPD y<-y,					vsqrtpd,			ymm2ymm1)
	ZEN3_FUNCDECL(VSQRTSD x<-x1 x1,				vsqrtsd,			2xmm2xmm1)
	ZEN3_FUNCDECL(VSQRTPS x<-x,					vsqrtps,			xmm2xmm1)
	ZEN3_FUNCDECL(VSQRTPS y<-y,					vsqrtps,			ymm2ymm1)
	ZEN3_FUNCDECL(VSQRTSS y<-y1 y1,				vsqrtss,			2xmm2xmm1)
	ZEN3_FUNCDECL0(-------- GPR<->VEC --------)
	ZEN3_FUNCDECL(VMOVD gpr32<-x,				vmovd,				xmm2gpr32)
	ZEN3_FUNCDECL(VMOVD gpr64<-x,				vmovd,				xmm2gpr64)
	ZEN3_FUNCDECL(VMOVD x<-gpr32,				vmovd,				gpr32_2xmm)
	ZEN3_FUNCDECL(VMOVD x<-gpr64,				vmovd,				gpr64_2xmm)
	ZEN3_FUNCDECL(VPEXTRB gpr32<-x,				vpextrb,			xmmi2gpr32)
	ZEN3_FUNCDECL(VPEXTRB gpr64<-x,				vpextrb,			xmmi2gpr64)
	ZEN3_FUNCDECL(VPEXTRW gpr32<-x,				vpextrw,			xmmi2gpr32)
	ZEN3_FUNCDECL(VPEXTRW gpr64<-x,				vpextrw,			xmmi2gpr64)
	ZEN3_FUNCDECL(VPEXTRD gpr32<-x,				vpextrd,			xmmi2gpr32)
	ZEN3_FUNCDECL(VPEXTRQ gpr64<-x,				vpextrq,			xmmi2gpr64)
	ZEN3_FUNCDECL(VPINSRB x<-gpr32,				vpinsrb,			gpr32ixmm2xmm)
	ZEN3_FUNCDECL(VPINSRW x<-gpr32,				vpinsrw,			gpr32ixmm2xmm)
	ZEN3_FUNCDECL(VPINSRD x<-gpr32,				vpinsrd,			gpr32ixmm2xmm)
	ZEN3_FUNCDECL(VPINSRQ x<-gpr64,				vpinsrq,			gpr64ixmm2xmm)
	ZEN3_FUNCDECL(VCVTSS2SI gpr32<-x,			vcvtss2si,			xmm2gpr32)
	ZEN3_FUNCDECL(VCVTSS2SI gpr64<-x,			vcvtss2si,			xmm2gpr64)
	ZEN3_FUNCDECL(VCVTSD2SI gpr32<-x,			vcvtsd2si,			xmm2gpr32)
	ZEN3_FUNCDECL(VCVTSD2SI gpr64<-x,			vcvtsd2si,			xmm2gpr64)
	ZEN3_FUNCDECL(VCVTSI2SS x<-gpr32,			vcvtsi2ss,			gpr32xmm2xmm)
	ZEN3_FUNCDECL(VCVTSI2SS x<-gpr64,			vcvtsi2ss,			gpr64xmm2xmm)
	ZEN3_FUNCDECL(VCVTSI2SD x<-gpr32,			vcvtsi2sd,			gpr32xmm2xmm)
	ZEN3_FUNCDECL(VCVTSI2SD x<-gpr64,			vcvtsi2sd,			gpr64xmm2xmm)
	ZEN3_FUNCDECL(VEXTRACTPS gpr32<-x i,		vextractps,			xmmi2gpr32)
	ZEN3_FUNCDECL(VPMOVMSKB gpr32<-x,			vpmovmskb,			xmm2gpr32)
	ZEN3_FUNCDECL(VPMOVMSKB gpr64<-x,			vpmovmskb,			xmm2gpr64)
	ZEN3_FUNCDECL(VPMOVMSKB gpr32<-y,			vpmovmskb,			ymm2gpr32)
	ZEN3_FUNCDECL(VPMOVMSKB gpr64<-y,			vpmovmskb,			ymm2gpr64)
	ZEN3_FUNCDECL(VMOVMSKPD gpr32<-x,			vmovmskpd,			xmm2gpr32)
	ZEN3_FUNCDECL(VMOVMSKPD gpr64<-x,			vmovmskpd,			xmm2gpr64)
	ZEN3_FUNCDECL(VMOVMSKPD gpr32<-y,			vmovmskpd,			ymm2gpr32)
	ZEN3_FUNCDECL(VMOVMSKPD gpr64<-y,			vmovmskpd,			ymm2gpr64)
	ZEN3_FUNCDECL(VMOVMSKPS gpr32<-x,			vmovmskps,			xmm2gpr32)
	ZEN3_FUNCDECL(VMOVMSKPS gpr64<-x,			vmovmskps,			xmm2gpr64)
	ZEN3_FUNCDECL(VMOVMSKPS gpr32<-y,			vmovmskps,			ymm2gpr32)
	ZEN3_FUNCDECL(VMOVMSKPS gpr64<-y,			vmovmskps,			ymm2gpr64)
	ZEN3_FUNCDECL(VPTEST f<-x1 x1,				vptest,				xmm2F)
	ZEN3_FUNCDECL(VPTEST f<-y1 y1,				vptest,				ymm2F)
	ZEN3_FUNCDECL(VTESTPD f<-x1 x1,				vtestpd,			xmm2F)
	ZEN3_FUNCDECL(VTESTPD f<-y1 y1,				vtestpd,			ymm2F)
	ZEN3_FUNCDECL(VTESTPS f<-x1 x1,				vtestps,			xmm2F)
	ZEN3_FUNCDECL(VTESTPS f<-y1 y1,				vtestps,			ymm2F)
	ZEN3_FUNCDECL(VCOMISD f<-x1 x1,				vcomisd,			xmm2F)
	ZEN3_FUNCDECL(VCOMISS f<-y1 y1,				vcomiss,			xmm2F)
	ZEN3_FUNCDECL(VUCOMISD f<-x1 x1,			vucomisd,			xmm2F)
	ZEN3_FUNCDECL(VUCOMISS f<-y1 y1,			vucomiss,			xmm2F)
	ZEN3_FUNCDECL0(---------- uCode ----------)
	ZEN3_FUNCDECL(VPERMQ y<-y i,				vpermq,				ymmi2ymm)
	ZEN3_FUNCDECL(VPERMPD y<-y i,				vpermpd,			ymmi2ymm)
	ZEN3_FUNCDECL(VPERMD y<-y1 y1,				vpermd,				2ymm2ymm)
	ZEN3_FUNCDECL(VPERMPS y<-y1 y1,				vpermps,			2ymm2ymm)
	ZEN3_FUNCDECL(VPMOVZXBW y<-x,				vpmovzxbw,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVZXBD y<-x,				vpmovzxbd,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVZXBQ y<-x,				vpmovzxbq,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVZXWD y<-x,				vpmovzxwd,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVZXWQ y<-x,				vpmovzxwq,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVZXDQ y<-x,				vpmovzxdq,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXBW y<-x,				vpmovsxbw,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXBD y<-x,				vpmovsxbd,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXBQ y<-x,				vpmovsxbq,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXWD y<-x,				vpmovsxwd,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXWQ y<-x,				vpmovsxwq,			xmm2ymm)
	ZEN3_FUNCDECL(VPMOVSXDQ y<-x,				vpmovsxdq,			xmm2ymm)
	ZEN3_FUNCDECL(VCVTPS2PD y<-x,				vcvtps2pd,			xmm2ymm)
	ZEN3_FUNCDECL(VCVTPD2PS x<-y,				vcvtpd2ps,			ymm2xmm)
	ZEN3_FUNCDECL(VCVTDQ2PD y<-x,				vcvtdq2pd,			xmm2ymm)
	ZEN3_FUNCDECL(VCVTPD2DQ x<-y,				vcvtpd2dq,			ymm2xmm)
	ZEN3_FUNCDECL(VCVTPH2PS y<-x,				vcvtph2ps,			xmm2ymm)
	ZEN3_FUNCDECL(VCVTPS2PH x<-y i,				vcvtps2ph,			ymmi2xmm)
	ZEN3_FUNCDECL(VHADDPD x<-x1 x1,				vhaddpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VHADDPD y<-y1 y1,				vhaddpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VHADDPS x<-x1 x1,				vhaddps,			2xmm2xmm)
	ZEN3_FUNCDECL(VHADDPS y<-y1 y1,				vhaddps,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBPD x<-x1 x1,				vhsubpd,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBPD y<-y1 y1,				vhsubpd,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBPS x<-x1 x1,				vhsubps,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBPS y<-y1 y1,				vhsubps,			2ymm2ymm)
	ZEN3_FUNCDECL(VHADDW x<-x1 x1,				vphaddw,			2xmm2xmm)
	ZEN3_FUNCDECL(VHADDW y<-y1 y1,				vphaddw,			2ymm2ymm)
	ZEN3_FUNCDECL(VHADDD x<-x1 x1,				vphaddd,			2xmm2xmm)
	ZEN3_FUNCDECL(VHADDD y<-y1 y1,				vphaddd,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBSW x<-x1 x1,				vphaddsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBSW y<-y1 y1,				vphaddsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBW x<-x1 x1,				vphsubw,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBW y<-y1 y1,				vphsubw,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBD x<-x1 x1,				vphsubd,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBD y<-y1 y1,				vphsubd,			2ymm2ymm)
	ZEN3_FUNCDECL(VHSUBSW x<-x1 x1,				vphsubsw,			2xmm2xmm)
	ZEN3_FUNCDECL(VHSUBSW y<-y1 y1,				vphsubsw,			2ymm2ymm)
	ZEN3_FUNCDECL(VDPPD x<-x1 x1 i,				vdppd,				2xmmi2xmm)
	ZEN3_FUNCDECL(VDPPS x<-x1 x1 i,				vdpps,				2xmmi2xmm)
	ZEN3_FUNCDECL(VDPPS y<-y1 y1 i,				vdpps,				2ymmi2ymm)
	ZEN3_FUNCDECL(VPCLMULQDQ x<-x1 x1 i,		vpclmulqdq,			2xmmi2xmm)
	ZEN3_FUNCDECL(VPCLMULQDQ y<-y1 y1 i,		vpclmulqdq,			2ymmi2ymm)
	ZEN3_FUNCDECL(VMPSADBW x<-x1 x1 i,			vmpsadbw,			2xmmi2xmm)
	ZEN3_FUNCDECL(VMPSADBW y<-y1 y1 i,			vmpsadbw,			2ymmi2ymm)
};

zen3_methods_ucode zen3_ucode[] = {
	ZEN3_FUNCDECL_UCODE0(---------- uCode ----------)
	ZEN3_FUNCDECL_UCODE(VPERMQ y<-y1 i,				vpermq)
	ZEN3_FUNCDECL_UCODE(VPERMD y<-y1 y1,			vpermd)
	ZEN3_FUNCDECL_UCODE(VPMOVZXBQ y<-x,				vpmovzxbq)
	ZEN3_FUNCDECL_UCODE(VPCLMULQDQ y<-y1 y1 0,		vpclmulqdq)
	ZEN3_FUNCDECL_UCODE(VMPSADBW y<-y1 y1 0,		vmpsadbw)
	ZEN3_FUNCDECL_UCODE(VDPPD x<-x1 x1 i,			vdppd)
	ZEN3_FUNCDECL_UCODE(VPHADDD y<-y1 y1,			vphaddd)
	ZEN3_FUNCDECL_UCODE(VHADDPD y<-y1 y1,			vhaddpd)
	ZEN3_FUNCDECL_UCODE(VCVTPS2PD y<-x,				vcvtps2pd)
	ZEN3_FUNCDECL_UCODE(VCVTPD2PS x<-y,				vcvtpd2ps)
	ZEN3_FUNCDECL_UCODE(VDIVPD y<-y1 y1,			vdivpd)
	ZEN3_FUNCDECL_UCODE(VDIVPS y<-y1 y1,			vdivps)
	ZEN3_FUNCDECL_UCODE(VDIVSD x<-x1 x1,			vdivsd)
	ZEN3_FUNCDECL_UCODE(VDIVSS x<-x1 x1,			vdivss)
	ZEN3_FUNCDECL_UCODE(VSQRTPD y<-y1,				vsqrtpd)
	ZEN3_FUNCDECL_UCODE(VSQRTPS y<-y1,				vsqrtps)
	ZEN3_FUNCDECL_UCODE(VSQRTSD x<-x1 x1,			vsqrtsd)
	ZEN3_FUNCDECL_UCODE(VSQRTSS x<-x1 x1,			vsqrtss)
	ZEN3_FUNCDECL_UCODE(FSQRT32,					fsqrt32)
	ZEN3_FUNCDECL_UCODE(FSQRT64,					fsqrt64)
	ZEN3_FUNCDECL_UCODE(FSQRT80,					fsqrt80)
	ZEN3_FUNCDECL_UCODE(FDIV32,						fdiv32)
	ZEN3_FUNCDECL_UCODE(FDIV64,						fdiv64)
	ZEN3_FUNCDECL_UCODE(FDIV80,						fdiv80)
};

zen3_methods zen3_sse[] = {
	ZEN3_FUNCDECL0(----------  SSE  ----------)
	ZEN3_FUNCDECL0(-- Port01 FP (2 read op) --)
	ZEN3_FUNCDECL(MULPD x1<-x1 x2,			mulpd,				xmm2xmm)
	ZEN3_FUNCDECL(MULPS x1<-x1 x2,			mulps,				xmm2xmm)
	ZEN3_FUNCDECL(MULSD x1<-x1 x2,			mulsd,				xmm2xmm)
	ZEN3_FUNCDECL(MULSS x1<-x1 x2,			mulss,				xmm2xmm)
	ZEN3_FUNCDECL(RCPPS x1<-x1 x2,			rcpps,				xmm2xmm)
	ZEN3_FUNCDECL(RCPSS x1<-x1 x2,			rcpss,				xmm2xmm)
	ZEN3_FUNCDECL(RSQRTPS x1<-x1 x2,		rsqrtps,			xmm2xmm)
	ZEN3_FUNCDECL(RSQRTSS x1<-x1 x2,		rsqrtss,			xmm2xmm)
	ZEN3_FUNCDECL0(---- Port01 (3 read op) ---)
	ZEN3_FUNCDECL(PBLENDVB x1<-x1 x2 x0,	pblendvb,			xmm0_2xmm)
	ZEN3_FUNCDECL(BLENDVPD x1<-x1 x2 x0,	blendvpd,			xmm0_2xmm)
	ZEN3_FUNCDECL(BLENDVPS x1<-x1 x2 x0,	blendvps,			xmm0_2xmm)

	ZEN3_FUNCDECL0(-------- Port23 FP --------)
	ZEN3_FUNCDECL(ADDPD x1<-x1 x2,			addpd,				xmm2xmm)
	ZEN3_FUNCDECL(ADDPS x1<-x1 x2,			addps,				xmm2xmm)
	ZEN3_FUNCDECL(ADDSD x1<-x1 x2,			addsd,				xmm2xmm)
	ZEN3_FUNCDECL(ADDSS x1<-x1 x2,			addss,				xmm2xmm)
	ZEN3_FUNCDECL(SUBPD x1<-x1 x2,			subpd,				xmm2xmm)
	ZEN3_FUNCDECL(SUBPS x1<-x1 x2,			subps,				xmm2xmm)
	ZEN3_FUNCDECL(SUBSD x1<-x1 x2,			subsd,				xmm2xmm)
	ZEN3_FUNCDECL(SUBSS x1<-x1 x2,			subss,				xmm2xmm)
	ZEN3_FUNCDECL(ADDSUBPD x1<-x1 x2,		addsubpd,			xmm2xmm)
	ZEN3_FUNCDECL(ADDSUBPS x1<-x1 x2,		addsubps,			xmm2xmm)
	ZEN3_FUNCDECL(ROUNDPD x<-x i,			roundpd,			xmmi2xmm)
	ZEN3_FUNCDECL(ROUNDPS x<-x i,			roundps,			xmmi2xmm)
	ZEN3_FUNCDECL(ROUNDSD x<-x i,			roundsd,			xmmi2xmm)
	ZEN3_FUNCDECL(ROUNDSS x<-x i,			roundss,			xmmi2xmm)
	ZEN3_FUNCDECL(CVTPS2DQ x<-x,			cvtps2dq,			xmm2xmm)
	ZEN3_FUNCDECL(CVTPS2PD x<-x,			cvtps2pd,			xmm2xmm)
	ZEN3_FUNCDECL(CVTPD2PS x<-x,			cvtpd2ps,			xmm2xmm)
	ZEN3_FUNCDECL(CVTPD2DQ x<-x,			cvtpd2dq,			xmm2xmm)
	ZEN3_FUNCDECL(CVTDQ2PD x<-x,			cvtdq2pd,			xmm2xmm)
	ZEN3_FUNCDECL(CVTDQ2PS x<-x,			cvtdq2ps,			xmm2xmm)
	ZEN3_FUNCDECL(CVTSS2SD x<-x,			cvtss2sd,			xmm2xmm)
	ZEN3_FUNCDECL(CVTSD2SS x<-x,			cvtsd2ss,			xmm2xmm)

	ZEN3_FUNCDECL(MINPD x1<-x1 x2,			minpd,				xmm2xmm)
	ZEN3_FUNCDECL(MINPS x1<-x1 x2,			minps,				xmm2xmm)
	ZEN3_FUNCDECL(MINSD x1<-x1 x2,			minsd,				xmm2xmm)
	ZEN3_FUNCDECL(MINSS x1<-x1 x2,			minss,				xmm2xmm)
	ZEN3_FUNCDECL(MAXPD x1<-x1 x2,			maxpd,				xmm2xmm)
	ZEN3_FUNCDECL(MAXPS x1<-x1 x2,			maxps,				xmm2xmm)
	ZEN3_FUNCDECL(MAXSD x1<-x1 x2,			maxsd,				xmm2xmm)
	ZEN3_FUNCDECL(MAXSS x1<-x1 x2,			maxss,				xmm2xmm)
	ZEN3_FUNCDECL(CMPEQPD x1<-x1 x2,		cmpeqpd,			xmm2xmm)
	ZEN3_FUNCDECL(CMPEQPS x1<-x1 x2,		cmpeqps,			xmm2xmm)
	ZEN3_FUNCDECL(CMPEQSD x1<-x1 x2,		cmpeqsd,			xmm2xmm)
	ZEN3_FUNCDECL(CMPEQSS x1<-x1 x2,		cmpeqss,			xmm2xmm)

	ZEN3_FUNCDECL0(-------- Port0123 FP ------)
	ZEN3_FUNCDECL(ANDPD x1<-x1 x2,			andpd,				xmm2xmm)
	ZEN3_FUNCDECL(ANDPS x1<-x1 x2,			andps,				xmm2xmm)
	ZEN3_FUNCDECL(ANDNPD x1<-x1 x2,			andnpd,				xmm2xmmRot)
	ZEN3_FUNCDECL(ANDNPS x1<-x1 x2,			andnps,				xmm2xmmRot)
	ZEN3_FUNCDECL(ORPD x1<-x1 x2,			orpd,				xmm2xmm)
	ZEN3_FUNCDECL(ORPS x1<-x1 x2,			orps,				xmm2xmm)
	ZEN3_FUNCDECL(XORPD x1<-x1 x2,			xorpd,				xmm2xmmRot)
	ZEN3_FUNCDECL(XORPS x1<-x1 x2,			xorps,				xmm2xmmRot)
	ZEN3_FUNCDECL(BLENDPD x1<-x1 x2,		blendpd,			xmmi2xmm)
	ZEN3_FUNCDECL(BLENDPS x1<-x1 x2,		blendps,			xmmi2xmm)

	ZEN3_FUNCDECL0(------- Port0123 Int ------)
	ZEN3_FUNCDECL(PAND x1<-x1 x2,			pand,				xmm2xmm)
	ZEN3_FUNCDECL(PANDN x1<-x1 x1,			pandn,				xmm2xmm)
	ZEN3_FUNCDECL(PANDN x1<-x1 x2,			pandn,				xmm2xmmRot)
	ZEN3_FUNCDECL(POR x1<-x1 x2,			por,				xmm2xmm)
	ZEN3_FUNCDECL(PXOR x1<-x1 x1,			pxor,				xmm2xmm)
	ZEN3_FUNCDECL(PXOR x1<-x1 x2,			pxor,				xmm2xmmRot)
	ZEN3_FUNCDECL(PBLENDW x1<-x1 x2,		pblendw,			xmmi2xmm)

	ZEN3_FUNCDECL(PADDB x1<-x1 x2,			paddb,				xmm2xmm)
	ZEN3_FUNCDECL(PADDW x1<-x1 x2,			paddw,				xmm2xmm)
	ZEN3_FUNCDECL(PADDD x1<-x1 x2,			paddd,				xmm2xmm)
	ZEN3_FUNCDECL(PADDQ x1<-x1 x2,			paddq,				xmm2xmm)
	ZEN3_FUNCDECL(PSUBB x1<-x1 x2,			psubb,				xmm2xmmRot)
	ZEN3_FUNCDECL(PSUBW x1<-x1 x2,			psubw,				xmm2xmmRot)
	ZEN3_FUNCDECL(PSUBD x1<-x1 x2,			psubd,				xmm2xmmRot)
	ZEN3_FUNCDECL(PSUBQ x1<-x1 x2,			psubq,				xmm2xmmRot)

	ZEN3_FUNCDECL(PCMPEQB x1<-x1 x2,		pcmpeqb,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPEQW x1<-x1 x2,		pcmpeqw,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPEQD x1<-x1 x2,		pcmpeqd,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPGTB x1<-x1 x2,		pcmpgtb,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPGTW x1<-x1 x2,		pcmpgtw,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPGTD x1<-x1 x2,		pcmpgtd,			xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPGTQ x1<-x1 x2,		pcmpgtq,			xmm2xmmRot)

	ZEN3_FUNCDECL(PMINSB x1<-x1 x2,			pminsb,				xmm2xmm)
	ZEN3_FUNCDECL(PMINUB x1<-x1 x2,			pminub,				xmm2xmm)
	ZEN3_FUNCDECL(PMINSW x1<-x1 x2,			pminsw,				xmm2xmm)
	ZEN3_FUNCDECL(PMINUW x1<-x1 x2,			pminuw,				xmm2xmm)
	ZEN3_FUNCDECL(PMINSD x1<-x1 x2,			pminsd,				xmm2xmm)
	ZEN3_FUNCDECL(PMINUD x1<-x1 x2,			pminud,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXSB x1<-x1 x2,			pmaxsb,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXUB x1<-x1 x2,			pmaxub,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXSW x1<-x1 x2,			pmaxsw,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXUW x1<-x1 x2,			pmaxuw,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXSD x1<-x1 x2,			pmaxsd,				xmm2xmm)
	ZEN3_FUNCDECL(PMAXUD x1<-x1 x2,			pmaxud,				xmm2xmm)

	ZEN3_FUNCDECL0(-------- Port01 Int -------)
	ZEN3_FUNCDECL(PADDSB x1<-x1 x2,			paddsb,				xmm2xmm)
	ZEN3_FUNCDECL(PADDSW x1<-x1 x2,			paddsw,				xmm2xmm)
	ZEN3_FUNCDECL(PSUBSB x1<-x1 x2,			psubsb,				xmm2xmmRot)
	ZEN3_FUNCDECL(PSUBSW x1<-x1 x2,			psubsw,				xmm2xmmRot)
	ZEN3_FUNCDECL(PCMPEQQ x1<-x1 x2,		pcmpeqq,			xmm2xmmRot)
	ZEN3_FUNCDECL(PABSB x1<-x1,				pabsb,				xmm2xmm)
	ZEN3_FUNCDECL(PABSW x1<-x1,				pabsw,				xmm2xmm)
	ZEN3_FUNCDECL(PABSD x1<-x1,				pabsd,				xmm2xmm)
	ZEN3_FUNCDECL(PAVGB x1<-x1 x2,			pavgb,				xmm2xmm)
	ZEN3_FUNCDECL(PAVGW x1<-x1 x2,			pavgw,				xmm2xmm)
	ZEN3_FUNCDECL(PSIGNB x1<-x1 x2,			psignb,				xmm2xmm)
	ZEN3_FUNCDECL(PSIGNW x1<-x1 x2,			psignw,				xmm2xmm)
	ZEN3_FUNCDECL(PSIGND x1<-x1 x2,			psignd,				xmm2xmm)

	ZEN3_FUNCDECL(AESENC x1<-x1 x2,			aesenc,				xmm2xmm)
	ZEN3_FUNCDECL(AESENCLAST x1<-x1 x2,		aesenclast,			xmm2xmm)
	ZEN3_FUNCDECL(AESDEC x1<-x1 x2,			aesdec,				xmm2xmm)
	ZEN3_FUNCDECL(AESDECLAST x1<-x1 x2,		aesdeclast,			xmm2xmm)
	ZEN3_FUNCDECL(AESENC x1<-x1 x2,			aesenc,				xmm2xmmRot)
	ZEN3_FUNCDECL(AESENCLAST x1<-x1 x2,		aesenclast,			xmm2xmmRot)
	ZEN3_FUNCDECL(AESDEC x1<-x1 x2,			aesdec,				xmm2xmmRot)
	ZEN3_FUNCDECL(AESDECLAST x1<-x1 x2,		aesdeclast,			xmm2xmmRot)
	ZEN3_FUNCDECL(AESIMC x<-x,				aesimc,				xmm2xmm)
	ZEN3_FUNCDECL(AESKEYGENASSIST x<-x i,	aeskeygenassist,	xmmi2xmm)
	ZEN3_FUNCDECL(PHMINPOSUW x<-x,			phminposuw,			xmm2xmm)
	ZEN3_FUNCDECL(EXTRQ x<-x,				extrq,				xmm2xmm)
	ZEN3_FUNCDECL(INSERTQ x<-x,				insertq,			xmm2xmm)

	ZEN3_FUNCDECL0(-------- Port12 Int -------)
	ZEN3_FUNCDECL(PSLLW x1<-x1 x2,			psllw,				xmm2xmm)
	ZEN3_FUNCDECL(PSRLW x1<-x1 x2,			psrlw,				xmm2xmm)
	ZEN3_FUNCDECL(PSRAW x1<-x1 x2,			psraw,				xmm2xmm)
	ZEN3_FUNCDECL(PSLLD x1<-x1 x2,			pslld,				xmm2xmm)
	ZEN3_FUNCDECL(PSRLD x1<-x1 x2,			psrld,				xmm2xmm)
	ZEN3_FUNCDECL(PSRAD x1<-x1 x2,			psrad,				xmm2xmm)
	ZEN3_FUNCDECL(PSLLQ x1<-x1 x2,			psllq,				xmm2xmm)
	ZEN3_FUNCDECL(PSRLQ x1<-x1 x2,			psrlq,				xmm2xmm)

	ZEN3_FUNCDECL(PSLLW x<-x i,				psllw,				i2xmm)
	ZEN3_FUNCDECL(PSRLW x<-x i,				psrlw,				i2xmm)
	ZEN3_FUNCDECL(PSRAW x<-x i,				psraw,				i2xmm)
	ZEN3_FUNCDECL(PSLLD x<-x i,				pslld,				i2xmm)
	ZEN3_FUNCDECL(PSRLD x<-x i,				psrld,				i2xmm)
	ZEN3_FUNCDECL(PSRAD x<-x i,				psrad,				i2xmm)
	ZEN3_FUNCDECL(PSLLQ x<-x i,				psllq,				i2xmm)
	ZEN3_FUNCDECL(PSRLQ x<-x i,				psrlq,				i2xmm)

	ZEN3_FUNCDECL(PSLLDQ x<-x i,			pslldq,				i2xmm)
	ZEN3_FUNCDECL(PSRLDQ x<-x i,			psrldq,				i2xmm)

	ZEN3_FUNCDECL(PUNPCKLBW x1<-x1 x2,		punpcklbw,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKHBW x1<-x1 x2,		punpckhbw,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKLWD x1<-x1 x2,		punpcklwd,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKHWD x1<-x1 x2,		punpckhwd,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKLDQ x1<-x1 x2,		punpckldq,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKHDQ x1<-x1 x2,		punpckhdq,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKLQDQ x1<-x1 x2,		punpcklqdq,			xmm2xmm)
	ZEN3_FUNCDECL(PUNPCKHQDQ x1<-x1 x2,		punpckhqdq,			xmm2xmm)
	ZEN3_FUNCDECL(UNPCKLPS x1<-x1 x2,		unpcklps,			xmm2xmm)
	ZEN3_FUNCDECL(UNPCKHPS x1<-x1 x2,		unpckhps,			xmm2xmm)
	ZEN3_FUNCDECL(UNPCKLPD x1<-x1 x2,		unpcklpd,			xmm2xmm)
	ZEN3_FUNCDECL(UNPCKHPD x1<-x1 x2,		unpckhpd,			xmm2xmm)
	ZEN3_FUNCDECL(MOVHLPS x1<-x1 x2,		movhlps,			xmm2xmm)
	ZEN3_FUNCDECL(MOVLHPS x1<-x1 x2,		movlhps,			xmm2xmm)
	ZEN3_FUNCDECL(PACKSSWB x1<-x1 x2,		packsswb,			xmm2xmm)
	ZEN3_FUNCDECL(PACKUSWB x1<-x1 x2,		packuswb,			xmm2xmm)
	ZEN3_FUNCDECL(PACKSSDW x1<-x1 x2,		packssdw,			xmm2xmm)
	ZEN3_FUNCDECL(PACKUSDW x1<-x1 x2,		packusdw,			xmm2xmm)
	ZEN3_FUNCDECL(SHUFPD x1<-x1 i,			shufpd,				xmmi2xmm)
	ZEN3_FUNCDECL(SHUFPS x1<-x1 i,			shufps,				xmmi2xmm)
	ZEN3_FUNCDECL(PSHUFB x1<-x1 x2,			pshufb,				xmm2xmm)
	ZEN3_FUNCDECL(PSHUFLW x1<-x1 i,			pshuflw,			xmmi2xmm)
	ZEN3_FUNCDECL(PSHUFHW x1<-x1 i,			pshufhw,			xmmi2xmm)
	ZEN3_FUNCDECL(PSHUFD x1<-x1 i,			pshufd,				xmmi2xmm)
	ZEN3_FUNCDECL(PALIGNR x1<-x1 i,			palignr,			xmmi2xmm)
	ZEN3_FUNCDECL(MOVDDUP x1<-x1 x2,		movddup,			xmm2xmm)
	ZEN3_FUNCDECL(MOVSLDUP x1<-x1 x2,		movsldup,			xmm2xmm)
	ZEN3_FUNCDECL(MOVSHDUP x1<-x1 x2,		movshdup,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXBW x1<-x1 x2,		pmovzxbw,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXBD x1<-x1 x2,		pmovzxbd,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXBQ x1<-x1 x2,		pmovzxbq,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXWD x1<-x1 x2,		pmovzxwd,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXWQ x1<-x1 x2,		pmovzxwq,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVZXDQ x1<-x1 x2,		pmovzxdq,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXBW x1<-x1 x2,		pmovsxbw,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXBD x1<-x1 x2,		pmovsxbd,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXBQ x1<-x1 x2,		pmovsxbq,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXWD x1<-x1 x2,		pmovsxwd,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXWQ x1<-x1 x2,		pmovsxwq,			xmm2xmm)
	ZEN3_FUNCDECL(PMOVSXDQ x1<-x1 x2,		pmovsxdq,			xmm2xmm)
	ZEN3_FUNCDECL(INSERTPS x1<-x1 x2,		insertps,			xmmi2xmm)

	ZEN3_FUNCDECL0(-------- Port03 Int -------)
	ZEN3_FUNCDECL(PMULHW x1<-x1 x2,			pmulhw,				xmm2xmm)
	ZEN3_FUNCDECL(PMULHUW x1<-x1 x2,		pmulhuw,			xmm2xmm)
	ZEN3_FUNCDECL(PMULHRSW x1<-x1 x2,		pmulhrsw,			xmm2xmm)
	ZEN3_FUNCDECL(PMULLW x1<-x1 x2,			pmullw,				xmm2xmm)
	ZEN3_FUNCDECL(PMULLD x1<-x1 x2,			pmulld,				xmm2xmm)
	ZEN3_FUNCDECL(PMULDQ x1<-x1 x2,			pmuldq,				xmm2xmm)
	ZEN3_FUNCDECL(PMULUDQ x1<-x1 x2,		pmuludq,			xmm2xmm)
	ZEN3_FUNCDECL(PMADDWD x1<-x1 x2,		pmaddwd,			xmm2xmm)
	ZEN3_FUNCDECL(PMADDUBSW x1<-x1 x2,		pmaddubsw,			xmm2xmm)
	ZEN3_FUNCDECL(PSADBW x1<-x1 x2,			psadbw,				xmm2xmm)
	ZEN3_FUNCDECL0(------ P1 (DIV/SQRT) ------)
	ZEN3_FUNCDECL(DIVPD x1<-x1 x2,			divpd,				xmm2xmm2)
	ZEN3_FUNCDECL(DIVPS x1<-x1 x2,			divps,				xmm2xmm2)
	ZEN3_FUNCDECL(DIVSD x1<-x1 x2,			divsd,				xmm2xmm2)
	ZEN3_FUNCDECL(DIVSS x1<-x1 x2,			divss,				xmm2xmm2)
	ZEN3_FUNCDECL(SQRTPD x<-x,				sqrtpd,				xmm2xmm1)
	ZEN3_FUNCDECL(SQRTPS x<-x,				sqrtps,				xmm2xmm1)
	ZEN3_FUNCDECL(SQRTSD x<-x,				sqrtsd,				xmm2xmm1)
	ZEN3_FUNCDECL(SQRTSS x<-x,				sqrtss,				xmm2xmm1)
	ZEN3_FUNCDECL0(-------- GPR<->VEC --------)
	ZEN3_FUNCDECL(MOVD gpr32<-x,			movd,				xmm2gpr32)
	ZEN3_FUNCDECL(MOVD gpr64<-x,			movd,				xmm2gpr64)
	ZEN3_FUNCDECL(MOVD x<-gpr32,			movd,				gpr32_2xmm)
	ZEN3_FUNCDECL(MOVD x<-gpr64,			movd,				gpr64_2xmm)

	ZEN3_FUNCDECL(PEXTRB gpr32<-x,			pextrb,				xmmi2gpr32)
	ZEN3_FUNCDECL(PEXTRB gpr64<-x,			pextrb,				xmmi2gpr64)
	ZEN3_FUNCDECL(PEXTRW gpr32<-x,			pextrw,				xmmi2gpr32)
	ZEN3_FUNCDECL(PEXTRW gpr64<-x,			pextrw,				xmmi2gpr64)
	ZEN3_FUNCDECL(PEXTRD gpr32<-x,			pextrd,				xmmi2gpr32)
	ZEN3_FUNCDECL(PEXTRQ gpr64<-x,			pextrq,				xmmi2gpr64)
	ZEN3_FUNCDECL(PINSRB x<-gpr32,			pinsrb,				gpr32i2xmm)
	ZEN3_FUNCDECL(PINSRW x<-gpr32,			pinsrw,				gpr32i2xmm)
	ZEN3_FUNCDECL(PINSRD x<-gpr32,			pinsrd,				gpr32i2xmm)
	ZEN3_FUNCDECL(PINSRQ x<-gpr64,			pinsrq,				gpr64i2xmm)

	ZEN3_FUNCDECL(CVTSS2SI gpr32<-x,		cvtss2si,			xmm2gpr32)
	ZEN3_FUNCDECL(CVTSS2SI gpr64<-x,		cvtss2si,			xmm2gpr64)
	ZEN3_FUNCDECL(CVTSD2SI gpr32<-x,		cvtsd2si,			xmm2gpr32)
	ZEN3_FUNCDECL(CVTSD2SI gpr64<-x,		cvtsd2si,			xmm2gpr64)
	ZEN3_FUNCDECL(CVTSI2SS x<-gpr32,		cvtsi2ss,			gpr32_2xmm)
	ZEN3_FUNCDECL(CVTSI2SS x<-gpr64,		cvtsi2ss,			gpr64_2xmm)
	ZEN3_FUNCDECL(CVTSI2SD x<-gpr32,		cvtsi2sd,			gpr32_2xmm)
	ZEN3_FUNCDECL(CVTSI2SD x<-gpr64,		cvtsi2sd,			gpr64_2xmm)
	ZEN3_FUNCDECL(EXTRACTPS gpr32<-x i,		extractps,			xmmi2gpr32)

	ZEN3_FUNCDECL(PMOVMSKB gpr32<-x,		pmovmskb,			xmm2gpr32)
	ZEN3_FUNCDECL(PMOVMSKB gpr64<-x,		pmovmskb,			xmm2gpr64)

	ZEN3_FUNCDECL(MOVMSKPD gpr32<-x,		movmskpd,			xmm2gpr32)
	ZEN3_FUNCDECL(MOVMSKPD gpr64<-x,		movmskpd,			xmm2gpr64)

	ZEN3_FUNCDECL(MOVMSKPS gpr32<-x,		movmskps,			xmm2gpr32)
	ZEN3_FUNCDECL(MOVMSKPS gpr64<-x,		movmskps,			xmm2gpr64)

	ZEN3_FUNCDECL(PTEST f<-x1 x1,			ptest,				xmm2F)

	ZEN3_FUNCDECL(COMISD f<-x1 x1,			comisd,				xmm2F)
	ZEN3_FUNCDECL(COMISS f<-x1 x1,			comiss,				xmm2F)
	ZEN3_FUNCDECL(UCOMISD f<-x1 x1,			ucomisd,			xmm2F)
	ZEN3_FUNCDECL(UCOMISS f<-x1 x1,			ucomiss,			xmm2F)

	ZEN3_FUNCDECL0(---------- uCode ----------)

	ZEN3_FUNCDECL(HADDPD x1<-x1 x2,			haddpd,				xmm2xmm)
	ZEN3_FUNCDECL(HADDPS x1<-x1 x2,			haddps,				xmm2xmm)
	ZEN3_FUNCDECL(HSUBPD x1<-x1 x2,			hsubpd,				xmm2xmm)
	ZEN3_FUNCDECL(HSUBPS x1<-x1 x2,			hsubps,				xmm2xmm)
	ZEN3_FUNCDECL(PHADDW x1<-x1 x2,			phaddw,				xmm2xmm)
	ZEN3_FUNCDECL(PHADDD x1<-x1 x2,			phaddd,				xmm2xmm)
	ZEN3_FUNCDECL(PHADDSW x1<-x1 x2,		phaddsw,			xmm2xmm)
	ZEN3_FUNCDECL(PHSUBW x1<-x1 x2,			phsubw,				xmm2xmm)
	ZEN3_FUNCDECL(PHSUBD x1<-x1 x2,			phsubd,				xmm2xmm)
	ZEN3_FUNCDECL(PHSUBSW x1<-x1 x2,		phsubsw,			xmm2xmm)

	ZEN3_FUNCDECL(DPPD x1<-x1 x2,			dppd,				xmmi2xmm)
	ZEN3_FUNCDECL(DPPS x1<-x1 x2,			dpps,				xmmi2xmm)
	ZEN3_FUNCDECL(PCLMULQDQ x1<-x1 x2 i,	pclmulqdq,			xmmi2xmm)
	ZEN3_FUNCDECL(MPSADBW x1<-x1 x2 i,		mpsadbw,			xmmi2xmm)
	ZEN3_FUNCDECL(EXTRQ x<-i i,				extrq,				ii2xmm)
	ZEN3_FUNCDECL(INSERTQ x<-x i i,			insertq,			xmmii2xmm)

	ZEN3_FUNCDECL0(---------- HW SHA ----------)
	ZEN3_FUNCDECL(SHA1MSG1 x1<-x1 x2,		sha1msg1,			xmm2xmm)
	ZEN3_FUNCDECL(SHA1MSG2 x1<-x1 x2,		sha1msg2,			xmm2xmm)
	ZEN3_FUNCDECL(SHA1NEXTE x1<-x1 x2,		sha1nexte,			xmm2xmm)
	ZEN3_FUNCDECL(SHA1RNDS4 x1<-x1 x2 i,	sha1rnds4,			xmmi2xmm1)
	ZEN3_FUNCDECL(SHA256MSG1 x1<-x1 x2,		sha256msg1,			xmm2xmm)
	ZEN3_FUNCDECL(SHA256MSG2 x1<-x1 x2,		sha256msg2,			xmm2xmm)
	ZEN3_FUNCDECL(SHA256RNDS2 x1<-x1 x2 x0,	sha256rnds2,		xmm0_2xmm1)

	ZEN3_FUNCDECL0(---------- SSE4.2 ----------)
	ZEN3_FUNCDECL(PCMPESTRI x0-<x1 x2 i,	pcmpestri,			xmmi2xmm)
	ZEN3_FUNCDECL(PCMPESTRM x0-<x1 x2 i,	pcmpestrm,			xmmi2xmm)
	ZEN3_FUNCDECL(PCMPISTRI x0-<x1 x2 i,	pcmpistri,			xmmi2xmm)
	ZEN3_FUNCDECL(PCMPISTRM x0-<x1 x2 i,	pcmpistrm,			xmmi2xmm)

	ZEN3_FUNCDECL0(----------  MMX  ----------)
	ZEN3_FUNCDECL0(--------  Port0123 --------)
	ZEN3_FUNCDECL(PAND m1<-m1 m2,			pand,				mm2mm)
	ZEN3_FUNCDECL(PANDN m1<-m1 m1,			pandn,				mm2mm)
	ZEN3_FUNCDECL(PANDN m1<-m1 m2,			pandn,				mm2mmRot)
	ZEN3_FUNCDECL(POR m1<-m1 m2,			por,				mm2mm)
	ZEN3_FUNCDECL(PXOR m1<-m1 m1,			pxor,				mm2mm)
	ZEN3_FUNCDECL(PXOR m1<-m1 m2,			pxor,				mm2mmRot)
	ZEN3_FUNCDECL(PADDB m1<-m1 m2,			paddb,				mm2mm)
	ZEN3_FUNCDECL(PADDW m1<-m1 m2,			paddw,				mm2mm)
	ZEN3_FUNCDECL(PADDD m1<-m1 m2,			paddd,				mm2mm)
	ZEN3_FUNCDECL(PADDQ m1<-m1 m2,			paddq,				mm2mm)
	ZEN3_FUNCDECL(PSUBB m1<-m1 m2,			psubb,				mm2mmRot)
	ZEN3_FUNCDECL(PSUBW m1<-m1 m2,			psubw,				mm2mmRot)
	ZEN3_FUNCDECL(PSUBD m1<-m1 m2,			psubd,				mm2mmRot)
	ZEN3_FUNCDECL(PSUBQ m1<-m1 m2,			psubq,				mm2mmRot)
	ZEN3_FUNCDECL0(--------  Port01 ----------)
	ZEN3_FUNCDECL(PADDSB m1<-m1 m2,			paddsb,				mm2mm)
	ZEN3_FUNCDECL(PADDSW m1<-m1 m2,			paddsw,				mm2mm)
	ZEN3_FUNCDECL(PSUBSB m1<-m1 m2,			psubsb,				mm2mmRot)
	ZEN3_FUNCDECL(PSUBSW m1<-m1 m2,			psubsw,				mm2mmRot)
	ZEN3_FUNCDECL(PABSB m1<-m1,				pabsb,				mm2mm)
	ZEN3_FUNCDECL(PABSW m1<-m1,				pabsw,				mm2mm)
	ZEN3_FUNCDECL(PABSD m1<-m1,				pabsd,				mm2mm)
	ZEN3_FUNCDECL(PAVGB m1<-m1 m2,			pavgb,				mm2mm)
	ZEN3_FUNCDECL(PAVGW m1<-m1 m2,			pavgw,				mm2mm)
	ZEN3_FUNCDECL(PSIGNB m1<-m1 m2,			psignb,				mm2mm)
	ZEN3_FUNCDECL(PSIGNW m1<-m1 m2,			psignw,				mm2mm)
	ZEN3_FUNCDECL(PSIGND m1<-m1 m2,			psignd,				mm2mm)
	ZEN3_FUNCDECL0(---------- Port12 ---------)
	ZEN3_FUNCDECL(PSLLW m1<-m1 m2,			psllw,				mm2mm)
	ZEN3_FUNCDECL(PSRLW m1<-m1 m2,			psrlw,				mm2mm)
	ZEN3_FUNCDECL(PSRAW m1<-m1 m2,			psraw,				mm2mm)
	ZEN3_FUNCDECL(PSLLD m1<-m1 m2,			pslld,				mm2mm)
	ZEN3_FUNCDECL(PSRLD m1<-m1 m2,			psrld,				mm2mm)
	ZEN3_FUNCDECL(PSRAD m1<-m1 m2,			psrad,				mm2mm)
	ZEN3_FUNCDECL(PSLLQ m1<-m1 m2,			psllq,				mm2mm)
	ZEN3_FUNCDECL(PSRLQ m1<-m1 m2,			psrlq,				mm2mm)
	ZEN3_FUNCDECL(PSLLW m<-m i,				psllw,				i2mm)
	ZEN3_FUNCDECL(PSRLW m<-m i,				psrlw,				i2mm)
	ZEN3_FUNCDECL(PSRAW m<-m i,				psraw,				i2mm)
	ZEN3_FUNCDECL(PSLLD m<-m i,				pslld,				i2mm)
	ZEN3_FUNCDECL(PSRLD m<-m i,				psrld,				i2mm)
	ZEN3_FUNCDECL(PSRAD m<-m i,				psrad,				i2mm)
	ZEN3_FUNCDECL(PSLLQ m<-m i,				psllq,				i2mm)
	ZEN3_FUNCDECL(PSRLQ m<-m i,				psrlq,				i2mm)
	ZEN3_FUNCDECL(PSHUFD m1<-m1 i,			pshufw,				mmi2mm)
	ZEN3_FUNCDECL(PALIGNR m1<-m1 m2 i,		palignr,			mmi2mm)
	ZEN3_FUNCDECL(PUNPCKLBW m1<-m1 m2,		punpcklbw,			mm2mm)
	ZEN3_FUNCDECL(PUNPCKHBW m1<-m1 m2,		punpckhbw,			mm2mm)
	ZEN3_FUNCDECL(PUNPCKLWD m1<-m1 m2,		punpcklwd,			mm2mm)
	ZEN3_FUNCDECL(PUNPCKHWD m1<-m1 m2,		punpckhwd,			mm2mm)
	ZEN3_FUNCDECL(PUNPCKLDQ m1<-m1 m2,		punpckldq,			mm2mm)
	ZEN3_FUNCDECL(PUNPCKHDQ m1<-m1 m2,		punpckhdq,			mm2mm)
	ZEN3_FUNCDECL(PACKSSWB m1<-m1 m2,		packsswb,			mm2mm)
	ZEN3_FUNCDECL(PACKUSWB m1<-m1 m2,		packuswb,			mm2mm)
	ZEN3_FUNCDECL(PACKSSDW m1<-m1 m2,		packssdw,			mm2mm)

	ZEN3_FUNCDECL0(--------- Port03 ----------)
	ZEN3_FUNCDECL(PMULHW m1<-m1 m2,			pmulhw,				mm2mm)
	ZEN3_FUNCDECL(PMULHUW m1<-m1 m2,		pmulhuw,			mm2mm)
	ZEN3_FUNCDECL(PMULLW m1<-m1 m2,			pmullw,				mm2mm)
	ZEN3_FUNCDECL(PMULUDQ m1<-m1 m2,		pmuludq,			mm2mm)
	ZEN3_FUNCDECL(PMADDWD m1<-m1 m2,		pmaddwd,			mm2mm)

	ZEN3_FUNCDECL0(-------- MMX<->GPR --------)
	ZEN3_FUNCDECL(PMOVMSKB gpr32<-m,		pmovmskb,			mm2gpr32)
	ZEN3_FUNCDECL(MOVD gpr32<-m,			movd,				mm2gpr32)
	ZEN3_FUNCDECL(MOVD m<-gpr32,			movd,				gpr32_2mm)
	ZEN3_FUNCDECL(PEXTRW gpr32<-m i,		pextrw,				mmi2gpr32)
	ZEN3_FUNCDECL(PINSRW m<-gpr32 i,		pinsrw,				gpr32i2mm)

	ZEN3_FUNCDECL0(-------- MMX<->XMM --------)
	ZEN3_FUNCDECL(MOVQ2DQ xmm<-mm,			movq2dq,			mm2xmm)
	ZEN3_FUNCDECL(MOVDQ2Q mm<-xmm,			movdq2q,			xmm2mm)
	ZEN3_FUNCDECL(CVTPS2PI m<-x,			cvtps2pi,			xmm2mm)
	ZEN3_FUNCDECL(CVTPD2PI m<-x,			cvtpd2pi,			xmm2mm)
	ZEN3_FUNCDECL(CVTPI2PS x<-m,			cvtpi2ps,			mm2xmm)
	ZEN3_FUNCDECL(CVTPI2PD x<-m,			cvtpi2pd,			mm2xmm)

	ZEN3_FUNCDECL0(----------- x87 -----------)
	ZEN3_FUNCDECL(FADD32,						fadd32,				x87_2op)
	ZEN3_FUNCDECL(FSUB32,						fsub32,				x87_2op)
	ZEN3_FUNCDECL(FMUL32,						fmul32,				x87_2op)
	ZEN3_FUNCDECL(FDIV32,						fdiv32,				x87_2op1)
	ZEN3_FUNCDECL(FSQRT32,						fsqrt32,			noop1)

	ZEN3_FUNCDECL(FADD64,						fadd64,				x87_2op)
	ZEN3_FUNCDECL(FSUB64,						fsub64,				x87_2op)
	ZEN3_FUNCDECL(FMUL64,						fmul64,				x87_2op)
	ZEN3_FUNCDECL(FDIV64,						fdiv64,				x87_2op1)
	ZEN3_FUNCDECL(FSQRT64,						fsqrt64,			noop1)

	ZEN3_FUNCDECL(FADD80,						fadd80,				x87_2op)
	ZEN3_FUNCDECL(FSUB80,						fsub80,				x87_2op)
	ZEN3_FUNCDECL(FMUL80,						fmul80,				x87_2op)
	ZEN3_FUNCDECL(FDIV80,						fdiv80,				x87_2op1)
	ZEN3_FUNCDECL(FSQRT80,						fsqrt80,			noop1)

	ZEN3_FUNCDECL(FXCH,							fxch,				x87_1op)
	ZEN3_FUNCDECL(FABS,							fabs,				noop)
	ZEN3_FUNCDECL(FCHS,							fchs,				noop)
	ZEN3_FUNCDECL(FTST,							ftst,				noop)
	ZEN3_FUNCDECL(FCOM,							fcom,				x87_1op)
	ZEN3_FUNCDECL(FCOMI,						fcomi,				x87_2opR)
	ZEN3_FUNCDECL(FLD + FSTP,					fld,				x87_1op_fstp)
	ZEN3_FUNCDECL(FLDZ + FSTP,					fldz,				x87_fstp)
	ZEN3_FUNCDECL(FLD1 + FSTP,					fld1,				x87_fstp)
	ZEN3_FUNCDECL(FLDPI + FSTP,					fldpi,				x87_fstp)
	ZEN3_FUNCDECL(FST,							fst,				x87_1op)
	ZEN3_FUNCDECL(FFREE,						ffree,				x87_1op)
	ZEN3_FUNCDECL(FXAM,							fxam,				noop)
	ZEN3_FUNCDECL(FDECSTP,						fdecstp,			noop)
	ZEN3_FUNCDECL(FINCSTP,						fincstp,			noop)
	ZEN3_FUNCDECL(FNOP,							fnop,				noop)

};

void Zen3_Test_SSE(int index) {
	volatile unsigned __int64 minres = ULONG_MAX;
	if (zen3_sse[index].funcs[0] != nullptr) {
		cout << setw(3) << right << dec << setfill(' ') << index << '|';
		cout << setw(27) << left << zen3_sse[index].name << '|' << right;
		for (int f = 0; f < ZEN3_FUNCS; f++) {
			minres = ULONG_MAX;
			(zen3_sse[index].funcs[f])();
			for (int rep = 0; rep < ZEN3_REPEATS; rep++) {
				minres = min(minres, (zen3_sse[index].funcs[f])());
			}
			cout << setw(9) << minres << ",";
		}
	} else {
		cout << "   |";
		cout << setw(27) << left << zen3_sse[index].name << '|' << right;
		cout << "--LATENCY--IIDOMAIN--FFDOMAIN--IFDOMAIN--FIDOMAIN-----GPR-------PORT0----PORT1-----PORT01----PORT03-----PORT2----PORT12----PORT23--PORT0123----PORT45------LDs-";
	}
	cout << endl;
};

void Zen3_Test_AVX(int index) {
	volatile unsigned __int64 minres = ULONG_MAX;
	if (zen3_avx[index].funcs[0] != nullptr) {
		cout << setw(3) << right << dec << setfill(' ') << index << '|';
		cout << setw(27) << left << zen3_avx[index].name << '|' << right;
		for (int f = 0; f < ZEN3_FUNCS; f++) {
			minres = ULONG_MAX;
			(zen3_avx[index].funcs[f])();
			for (int rep = 0; rep < ZEN3_REPEATS; rep++) {
				minres = min(minres, (zen3_avx[index].funcs[f])());
			}
			cout << setw(9) << minres << ",";
		}
	} else {
		cout << "   |";
		cout << setw(27) << left << zen3_avx[index].name << '|' << right;
		cout << "--LATENCY--IIDOMAIN--FFDOMAIN--IFDOMAIN--FIDOMAIN-----GPR-------PORT0----PORT1-----PORT01----PORT03-----PORT2----PORT12----PORT23--PORT0123----PORT45------LDs-";
	}
	cout << endl;
};

void Zen3_Test_ucode(int index) {
	volatile unsigned __int64 minres = ULONG_MAX;
	if (zen3_ucode[index].funcs[0] != nullptr) {
		cout << setw(3) << right << index << '|';
		cout << setw(27) << left << zen3_ucode[index].name << '|' << right;
		for (int f = 0; f < ZEN3_FUNCS_UCODE; f++) {
			minres = ULONG_MAX;
			(zen3_ucode[index].funcs[f])();
			for (int rep = 0; rep < ZEN3_REPEATS; rep++) {
				minres = min(minres, (zen3_ucode[index].funcs[f])());
			}
			cout << setw(9) << minres << ",";
		}
	} else {
		cout << "   |";
		cout << setw(27) << left << zen3_ucode[index].name << '|' << right;
		cout << "--LATENCY--IIDOMAIN--FFDOMAIN--IFDOMAIN--FIDOMAIN---P0_1_23----P01_23----P03_12-----PORT0-----PORT1----PORT01";
	}
	cout << endl;
};

void Zen3_Demo(void)
{
	SetProcessAffinityMask(GetCurrentProcess(), 8);
	SetThreadAffinityMask(GetCurrentThread(), 8);
	Sleep(0);
	for (int b = 0; b < sizeof(zen3_avx) / sizeof(zen3_methods); b++) {
		Zen3_Test_AVX(b);
	}
	for (int b = 0; b < sizeof(zen3_sse) / sizeof(zen3_methods); b++) {
		Zen3_Test_SSE(b);
	}
	for (int b2 = 0; b2 < sizeof(zen3_ucode) / sizeof(zen3_methods_ucode); b2++) {
		Zen3_Test_ucode(b2);
	}
}
