#include "stdafx.h"
using namespace std;

methods m[] = {
	FUNCDECL0(-- Port01 FP (2 read op) --)
	FUNCDECL(VMULPD x<-x1 x1,				vmulpd,				2xmm2xmm)
	FUNCDECL(VMULPD y<-y1 y1,				vmulpd,				2ymm2ymm)
	FUNCDECL(VMULPS x<-x1 x1,				vmulps,				2xmm2xmm)
	FUNCDECL(VMULPS y<-y1 y1,				vmulps,				2ymm2ymm)
	FUNCDECL(VMULSD x<-x1 x1,				vmulsd,				2xmm2xmm)
	FUNCDECL(VMULSS x<-x1 x1,				vmulss,				2xmm2xmm)
	FUNCDECL(VRCPPS x<-x,					vrcpps,				xmm2xmm)
	FUNCDECL(VRCPPS y<-y,					vrcpps,				ymm2ymm)
	FUNCDECL(VRCPSS x<-x1 x1,				vrcpss,				2xmm2xmm)
	FUNCDECL(VRSQRTPS x<-x,					vrsqrtps,			xmm2xmm)
	FUNCDECL(VRSQRTPS y<-y,					vrsqrtps,			ymm2ymm)
	FUNCDECL(VRSQRTSS x<-x1 x1,				vrsqrtss,			2xmm2xmm)
	FUNCDECL0(---- Port01 (3 read op) ---)
	FUNCDECL(VPBLENDVB x1<-x1 x1 x1,		vpblendvb,			3xmm2xmm)
	FUNCDECL(VPBLENDVB y1<-y1 y1 y1,		vpblendvb,			3ymm2ymm)
	FUNCDECL(VBLENDVPD x1<-x1 x1 x1,		vblendvpd,			3xmm2xmm)
	FUNCDECL(VBLENDVPD y1<-y1 y1 y1,		vblendvpd,			3ymm2ymm)
	FUNCDECL(VBLENDVPS x1<-x1 x1 x1,		vblendvps,			3xmm2xmm)
	FUNCDECL(VBLENDVPS y1<-y1 y1 y1,		vblendvps,			3ymm2ymm)
	FUNCDECL(VPBLENDVB x1<-x1 x2 x3,		vpblendvb,			3xmm2xmmRot)
	FUNCDECL(VPBLENDVB y1<-x1 y2 y3,		vpblendvb,			3ymm2ymmRot)
	FUNCDECL(VBLENDVPD x1<-x1 x2 x3,		vblendvpd,			3xmm2xmmRot)
	FUNCDECL(VBLENDVPD y1<-x1 y2 y3,		vblendvpd,			3ymm2ymmRot)
	FUNCDECL(VBLENDVPS x1<-x1 x2 x3,		vblendvps,			3xmm2xmmRot)
	FUNCDECL(VBLENDVPS y1<-x1 y2 y3,		vblendvps,			3ymm2ymmRot)
	FUNCDECL(VFMADDSUB132PD x1<-x1 x1 x1,	vfmaddsub132pd,		2xmm2xmm)
	FUNCDECL(VFMADDSUB132PD y1<-y1 y1 y1,	vfmaddsub132pd,		2ymm2ymm)
	FUNCDECL(VFMADDSUB132PS x1<-x1 x1 x1,	vfmaddsub132ps,		2xmm2xmm)
	FUNCDECL(VFMADDSUB132PS y1<-y1 y1 y1,	vfmaddsub132ps,		2ymm2ymm)
	FUNCDECL(VFMADD132SD x1<-x1 x1 x1,		vfmadd132sd,		2xmm2xmm)
	FUNCDECL(VFMADD132SS x1<-x1 x1 x1,		vfmadd132ss,		2xmm2xmm)
	FUNCDECL(VFMADDSUB213PD x1<-x1 x1 x1,	vfmaddsub213pd,		2xmm2xmm)
	FUNCDECL(VFMADDSUB213PD y1<-y1 y1 y1,	vfmaddsub213pd,		2ymm2ymm)
	FUNCDECL(VFMADDSUB213PS x1<-x1 x1 x1,	vfmaddsub213ps,		2xmm2xmm)
	FUNCDECL(VFMADDSUB213PS y1<-y1 y1 y1,	vfmaddsub213ps,		2ymm2ymm)
	FUNCDECL(VFMADD213SD x1<-x1 x1 x1,		vfmadd213sd,		2xmm2xmm)
	FUNCDECL(VFMADD213SS x1<-x1 x1 x1,		vfmadd213ss,		2xmm2xmm)
	FUNCDECL(VFMADDSUB231PD x1<-x1 x1 x1,	vfmaddsub231pd,		2xmm2xmm)
	FUNCDECL(VFMADDSUB231PD y1<-y1 y1 y1,	vfmaddsub231pd,		2ymm2ymm)
	FUNCDECL(VFMADDSUB231PS x1<-x1 x1 x1,	vfmaddsub231ps,		2xmm2xmm)
	FUNCDECL(VFMADDSUB231PS y1<-y1 y1 y1,	vfmaddsub231ps,		2ymm2ymm)
	FUNCDECL(VFMADD231SD x1<-x1 x1 x1,		vfmadd231sd,		2xmm2xmm)
	FUNCDECL(VFMADD231SS x1<-x1 x1 x1,		vfmadd231ss,		2xmm2xmm)
	FUNCDECL(VFMADDSUB132PD x1<-x1 x2 x3,	vfmaddsub132pd,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB132PD y1<-y1 y2 y3,	vfmaddsub132pd,		2ymm2ymmRot)
	FUNCDECL(VFMADDSUB132PS x1<-x1 x2 x3,	vfmaddsub132ps,		2xmm2xmmRot)
	FUNCDECL(VFMADD132SD x1<-x1 x2 x3,		vfmadd132sd,		2xmm2xmmRot)
	FUNCDECL(VFMADD132SS x1<-x1 x2 x3,		vfmadd132ss,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB132PS y1<-y1 y2 y3,	vfmaddsub132ps,		2ymm2ymmRot)
	FUNCDECL(VFMADDSUB213PD x1<-x1 x2 x3,	vfmaddsub213pd,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB213PD y1<-y1 y2 y3,	vfmaddsub213pd,		2ymm2ymmRot)
	FUNCDECL(VFMADDSUB213PS x1<-x1 x2 x3,	vfmaddsub213ps,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB213PS y1<-y1 y2 y3,	vfmaddsub213ps,		2ymm2ymmRot)
	FUNCDECL(VFMADD213SD x1<-x1 x2 x3,		vfmadd213sd,		2xmm2xmmRot)
	FUNCDECL(VFMADD213SS x1<-x1 x2 x3,		vfmadd213ss,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB231PD x1<-x1 x2 x3,	vfmaddsub231pd,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB231PD y1<-y1 y2 y3,	vfmaddsub231pd,		2ymm2ymmRot)
	FUNCDECL(VFMADDSUB231PS x1<-x1 x2 x3,	vfmaddsub231ps,		2xmm2xmmRot)
	FUNCDECL(VFMADDSUB231PS y1<-y1 y2 y3,	vfmaddsub231ps,		2ymm2ymmRot)
	FUNCDECL(VFMADD231SD x1<-x1 x1 x1,		vfmadd231sd,		2xmm2xmmRot)
	FUNCDECL(VFMADD231SS x1<-x1 x1 x1,		vfmadd231ss,		2xmm2xmmRot)
	FUNCDECL0(-------- Port23 FP --------)
	FUNCDECL(VADDPD x<-x1 x1,				vaddpd,				2xmm2xmm)
	FUNCDECL(VADDPD y<-y1 y1,				vaddpd,				2ymm2ymm)
	FUNCDECL(VADDPS x<-x1 x1,				vaddps,				2xmm2xmm)
	FUNCDECL(VADDPS y<-y1 y1,				vaddps,				2ymm2ymm)
	FUNCDECL(VADDSD x<-x1 x1,				vaddsd,				2xmm2xmm)
	FUNCDECL(VADDSS x<-x1 x1,				vaddss,				2xmm2xmm)
	FUNCDECL(VSUBPD x<-x1 x1,				vsubpd,				2xmm2xmm)
	FUNCDECL(VSUBPD y<-y1 y1,				vsubpd,				2ymm2ymm)
	FUNCDECL(VSUBPS x<-x1 x1,				vsubps,				2xmm2xmm)
	FUNCDECL(VSUBPS y<-y1 y1,				vsubps,				2ymm2ymm)
	FUNCDECL(VSUBSD x<-x1 x1,				vsubsd,				2xmm2xmm)
	FUNCDECL(VSUBSS x<-x1 x1,				vsubss,				2xmm2xmm)
	FUNCDECL(VADDSUBPD x<-x1 x1,			vaddsubpd,			2xmm2xmm)
	FUNCDECL(VADDSUBPD y<-y1 y1,			vaddsubpd,			2ymm2ymm)
	FUNCDECL(VADDSUBPS x<-x1 x1,			vaddsubps,			2xmm2xmm)
	FUNCDECL(VADDSUBPS y<-y1 y1,			vaddsubps,			2ymm2ymm)
	FUNCDECL(VROUNDPD x<-x i,				vroundpd,			xmmi2xmm)
	FUNCDECL(VROUNDPD y<-y i,				vroundpd,			ymmi2ymm)
	FUNCDECL(VROUNDPS x<-x i,				vroundps,			xmmi2xmm)
	FUNCDECL(VROUNDPS y<-y i,				vroundps,			ymmi2ymm)
	FUNCDECL(VROUNDSD x<-x1 x1 i,			vroundsd,			2xmmi2xmm)
	FUNCDECL(VROUNDSS x<-x1 x1 i,			vroundss,			2xmmi2xmm)
	FUNCDECL(VCVTPS2DQ x<-x,				vcvtps2dq,			xmm2xmm)
	FUNCDECL(VCVTPS2DQ y<-y,				vcvtps2dq,			ymm2ymm)
	FUNCDECL(VCVTPS2PD x<-x,				vcvtps2pd,			xmm2xmm)
	FUNCDECL(VCVTPD2PS x<-x,				vcvtpd2ps,			xmm2xmm)
	FUNCDECL(VCVTPD2DQ x<-x,				vcvtpd2dq,			xmm2xmm)
	FUNCDECL(VCVTDQ2PS x<-x,				vcvtdq2ps,			xmm2xmm)
	FUNCDECL(VCVTDQ2PS y<-y,				vcvtdq2ps,			ymm2ymm)
	FUNCDECL(VCVTDQ2PD x<-x,				vcvtdq2pd,			xmm2xmm)
	FUNCDECL(VCVTPS2PH x<-x i,				vcvtps2ph,			xmmi2xmm)
	FUNCDECL(VCVTPH2PS x<-x,				vcvtph2ps,			xmm2xmm)
	FUNCDECL(VCVTSS2SD x<-x1 x1,			vcvtss2sd,			2xmm2xmm)
	FUNCDECL(VCVTSD2SS x<-x1 x1,			vcvtsd2ss,			2xmm2xmm)
	FUNCDECL(VMINPD x<-x1 x1,				vminpd,				2xmm2xmm)
	FUNCDECL(VMINPD y<-y1 y1,				vminpd,				2ymm2ymm)
	FUNCDECL(VMINPS x<-x1 x1,				vminps,				2xmm2xmm)
	FUNCDECL(VMINPS y<-y1 y1,				vminps,				2ymm2ymm)
	FUNCDECL(VMINSD x<-x1 x1,				vminsd,				2xmm2xmm)
	FUNCDECL(VMINSS x<-x1 x1,				vminss,				2xmm2xmm)
	FUNCDECL(VMAXPD x<-x1 x1,				vmaxpd,				2xmm2xmm)
	FUNCDECL(VMAXPD y<-y1 y1,				vmaxpd,				2ymm2ymm)
	FUNCDECL(VMAXPS x<-x1 x1,				vmaxps,				2xmm2xmm)
	FUNCDECL(VMAXPS y<-y1 y1,				vmaxps,				2ymm2ymm)
	FUNCDECL(VMAXSD x<-x1 x1,				vmaxsd,				2xmm2xmm)
	FUNCDECL(VMAXSS x<-x1 x1,				vmaxss,				2xmm2xmm)
	FUNCDECL(VCMPEQPD x<-x1 x1,				vcmpeqpd,			2xmm2xmm)
	FUNCDECL(VCMPEQPD y<-y1 y1,				vcmpeqpd,			2ymm2ymm)
	FUNCDECL(VCMPEQPS x<-x1 x1,				vcmpeqps,			2xmm2xmm)
	FUNCDECL(VCMPEQPS y<-y1 y1,				vcmpeqps,			2ymm2ymm)
	FUNCDECL(VCMPEQSD x<-x1 x1,				vcmpeqsd,			2xmm2xmm)
	FUNCDECL(VCMPEQPS x<-x1 x1,				vcmpeqss,			2xmm2xmm)
	FUNCDECL0(-------- Port0123 FP ------)
	FUNCDECL(VANDPD x<-x1 x1,				vandpd,				2xmm2xmm)
	FUNCDECL(VANDPD y<-y1 y1,				vandpd,				2ymm2ymm)
	FUNCDECL(VANDPS x<-x1 x1,				vandps,				2xmm2xmm)
	FUNCDECL(VANDPS y<-y1 y1,				vandps,				2ymm2ymm)
	FUNCDECL(VANDNPD x<-x1 x2,				vandnpd,			2xmm2xmmRot)
	FUNCDECL(VANDNPD y<-y1 y2,				vandnpd,			2ymm2ymmRot)
	FUNCDECL(VANDNPS x<-x1 x2,				vandnps,			2xmm2xmmRot)
	FUNCDECL(VANDNPS y<-y1 y2,				vandnps,			2ymm2ymmRot)
	FUNCDECL(VORPD x<-x1 x1,				vorpd,				2xmm2xmm)
	FUNCDECL(VORPD y<-y1 y1,				vorpd,				2ymm2ymm)
	FUNCDECL(VORPS x<-x1 x1,				vorps,				2xmm2xmm)
	FUNCDECL(VORPS y<-y1 y1,				vorps,				2ymm2ymm)
	FUNCDECL(VXORPD x<-x1 x2,				vxorpd,				2xmm2xmmRot)
	FUNCDECL(VXORPD y<-y1 y2,				vxorpd,				2ymm2ymmRot)
	FUNCDECL(VXORPS x<-x1 x2,				vxorps,				2xmm2xmmRot)
	FUNCDECL(VXORPS y<-y1 y2,				vxorps,				2ymm2ymmRot)
	FUNCDECL(VBLENDPD x<-x1 x1 i,			vblendpd,			2xmmi2xmm)
	FUNCDECL(VBLENDPD y<-y1 y1 i,			vblendpd,			2ymmi2ymm)
	FUNCDECL0(------- Port0123 Int ------)
	FUNCDECL(VPAND x<-x1 x1,				vpand,				2xmm2xmm)
	FUNCDECL(VPAND y<-y1 y1,				vpand,				2ymm2ymm)
	FUNCDECL(VPANDN x<-x1 x2,				vpandn,				2xmm2xmmRot)
	FUNCDECL(VPANDN y<-y1 y2,				vpandn,				2ymm2ymmRot)
	FUNCDECL(VPOR x<-x1 x1,					vpor,				2xmm2xmm)
	FUNCDECL(VPOR y<-y1 y1,					vpor,				2ymm2ymm)
	FUNCDECL(VPXOR x<-x1 x2,				vpxor,				2xmm2xmmRot)
	FUNCDECL(VPXOR y<-y1 y2,				vpxor,				2ymm2ymmRot)
	FUNCDECL(VPBLENDD x<-x1 x1 i,			vpblendd,			2xmmi2xmm)
	FUNCDECL(VPBLENDD y<-y1 y1 i,			vpblendd,			2ymmi2ymm)
	FUNCDECL(VPBLENDW x<-x1 x1 i,			vpblendw,			2xmmi2xmm)
	FUNCDECL(VPBLENDW y<-y1 y1 i,			vpblendw,			2ymmi2ymm)
	FUNCDECL(VBLENDPS x<-x1 x1 i,			vblendps,			2xmmi2xmm)
	FUNCDECL(VBLENDPS y<-y1 y1 i,			vblendps,			2ymmi2ymm)
	FUNCDECL(VPADDB x<-x1 x1,				vpaddb,				2xmm2xmm)
	FUNCDECL(VPADDB y<-y1 y1,				vpaddb,				2ymm2ymm)
	FUNCDECL(VPADDW x<-x1 x1,				vpaddw,				2xmm2xmm)
	FUNCDECL(VPADDW y<-y1 y1,				vpaddw,				2ymm2ymm)
	FUNCDECL(VPADDD x<-x1 x1,				vpaddd,				2xmm2xmm)
	FUNCDECL(VPADDD y<-y1 y1,				vpaddd,				2ymm2ymm)
	FUNCDECL(VPADDQ x<-x1 x1,				vpaddq,				2xmm2xmm)
	FUNCDECL(VPADDQ y<-y1 y1,				vpaddq,				2ymm2ymm)
	FUNCDECL(VPSUBB x<-x1 x2,				vpsubb,				2xmm2xmmRot)
	FUNCDECL(VPSUBB y<-y1 y2,				vpsubb,				2ymm2ymmRot)
	FUNCDECL(VPSUBW x<-x1 x2,				vpsubw,				2xmm2xmmRot)
	FUNCDECL(VPSUBW y<-y1 y2,				vpsubw,				2ymm2ymmRot)
	FUNCDECL(VPSUBD x<-x1 x2,				vpsubd,				2xmm2xmmRot)
	FUNCDECL(VPSUBD y<-y1 y2,				vpsubd,				2ymm2ymmRot)
	FUNCDECL(VPSUBQ x<-x1 x2,				vpsubq,				2xmm2xmmRot)
	FUNCDECL(VPSUBQ y<-y1 y2,				vpsubq,				2ymm2ymmRot)
	FUNCDECL(VPCMPEQB x<-x1 x2,				vpcmpeqb,			2xmm2xmmRot)
	FUNCDECL(VPCMPEQB y<-y1 y2,				vpcmpeqb,			2ymm2ymmRot)
	FUNCDECL(VPCMPEQW x<-x1 x2,				vpcmpeqw,			2xmm2xmmRot)
	FUNCDECL(VPCMPEQW y<-y1 y2,				vpcmpeqw,			2ymm2ymmRot)
	FUNCDECL(VPCMPEQD x<-x1 x2,				vpcmpeqd,			2xmm2xmmRot)
	FUNCDECL(VPCMPEQD y<-y1 y2,				vpcmpeqd,			2ymm2ymmRot)
	FUNCDECL(VPCMPGTB x<-x1 x2,				vpcmpgtb,			2xmm2xmmRot)
	FUNCDECL(VPCMPGTB y<-y1 y2,				vpcmpgtb,			2ymm2ymmRot)
	FUNCDECL(VPCMPGTW x<-x1 x2,				vpcmpgtw,			2xmm2xmmRot)
	FUNCDECL(VPCMPGTW y<-y1 y2,				vpcmpgtw,			2ymm2ymmRot)
	FUNCDECL(VPCMPGTD x<-x1 x2,				vpcmpgtd,			2xmm2xmmRot)
	FUNCDECL(VPCMPGTD y<-y1 y2,				vpcmpgtd,			2ymm2ymmRot)
	FUNCDECL(VPCMPGTQ x<-x1 x2,				vpcmpgtq,			2xmm2xmmRot)
	FUNCDECL(VPCMPGTQ y<-y1 y2,				vpcmpgtq,			2ymm2ymmRot)
	FUNCDECL(VPMINSB x<-x1 x1,				vpminsb,			2xmm2xmm)
	FUNCDECL(VPMINSB y<-y1 y1,				vpminsb,			2ymm2ymm)
	FUNCDECL(VPMINUB x<-x1 x1,				vpminub,			2xmm2xmm)
	FUNCDECL(VPMINUB y<-y1 y1,				vpminub,			2ymm2ymm)
	FUNCDECL(VPMINSW x<-x1 x1,				vpminsw,			2xmm2xmm)
	FUNCDECL(VPMINSW y<-y1 y1,				vpminsw,			2ymm2ymm)
	FUNCDECL(VPMINUW x<-x1 x1,				vpminuw,			2xmm2xmm)
	FUNCDECL(VPMINUW y<-y1 y1,				vpminuw,			2ymm2ymm)
	FUNCDECL(VPMINSD x<-x1 x1,				vpminsd,			2xmm2xmm)
	FUNCDECL(VPMINSD y<-y1 y1,				vpminsd,			2ymm2ymm)
	FUNCDECL(VPMINUD x<-x1 x1,				vpminud,			2xmm2xmm)
	FUNCDECL(VPMINUD y<-y1 y1,				vpminud,			2ymm2ymm)
	FUNCDECL(VPMAXSB x<-x1 x1,				vpmaxsb,			2xmm2xmm)
	FUNCDECL(VPMAXSB y<-y1 y1,				vpmaxsb,			2ymm2ymm)
	FUNCDECL(VPMAXUB x<-x1 x1,				vpmaxub,			2xmm2xmm)
	FUNCDECL(VPMAXUB y<-y1 y1,				vpmaxub,			2ymm2ymm)
	FUNCDECL(VPMAXSW x<-x1 x1,				vpmaxsw,			2xmm2xmm)
	FUNCDECL(VPMAXSW y<-y1 y1,				vpmaxsw,			2ymm2ymm)
	FUNCDECL(VPMAXUW x<-x1 x1,				vpmaxuw,			2xmm2xmm)
	FUNCDECL(VPMAXUW y<-y1 y1,				vpmaxuw,			2ymm2ymm)
	FUNCDECL(VPMAXSD x<-x1 x1,				vpmaxsd,			2xmm2xmm)
	FUNCDECL(VPMAXSD y<-y1 y1,				vpmaxsd,			2ymm2ymm)
	FUNCDECL(VPMAXUD x<-x1 x1,				vpmaxud,			2xmm2xmm)
	FUNCDECL(VPMAXUD y<-y1 y1,				vpmaxud,			2ymm2ymm)
	FUNCDECL0(-------- Port01 Int -------)
	FUNCDECL(VPADDSB x<-x1 x1,				vpaddsb,			2xmm2xmm)
	FUNCDECL(VPADDSB y<-y1 y1,				vpaddsb,			2ymm2ymm)
	FUNCDECL(VPADDSW x<-x1 x1,				vpaddsw,			2xmm2xmm)
	FUNCDECL(VPADDSW y<-y1 y1,				vpaddsw,			2ymm2ymm)
	FUNCDECL(VPSUBSB x<-x1 x2,				vpsubsb,			2xmm2xmmRot)
	FUNCDECL(VPSUBSB y<-y1 y2,				vpsubsb,			2ymm2ymmRot)
	FUNCDECL(VPSUBSW x<-x1 x2,				vpsubsw,			2xmm2xmmRot)
	FUNCDECL(VPSUBSW y<-y1 y2,				vpsubsw,			2ymm2ymmRot)
	FUNCDECL(VPCMPEQQ x<-x1 x2,				vpcmpeqq,			2xmm2xmmRot)
	FUNCDECL(VPCMPEQQ y<-y1 y2,				vpcmpeqq,			2ymm2ymmRot)
	FUNCDECL(VPABSB x<-x,					vpabsb,				xmm2xmm)
	FUNCDECL(VPABSB y<-y,					vpabsb,				ymm2ymm)
	FUNCDECL(VPABSW x<-x,					vpabsw,				xmm2xmm)
	FUNCDECL(VPABSW y<-y,					vpabsw,				ymm2ymm)
	FUNCDECL(VPABSD x<-x,					vpabsd,				xmm2xmm)
	FUNCDECL(VPABSD y<-y,					vpabsd,				ymm2ymm)
	FUNCDECL(VPAVGB x<-x1 x1,				vpavgb,				2xmm2xmm)
	FUNCDECL(VPAVGB y<-y1 y1,				vpavgb,				2ymm2ymm)
	FUNCDECL(VPAVGW x<-x1 x1,				vpavgw,				2xmm2xmm)
	FUNCDECL(VPAVGW y<-y1 y1,				vpavgw,				2ymm2ymm)
	FUNCDECL(VPSIGNB x<-x1 x1,				vpsignb,			2xmm2xmm)
	FUNCDECL(VPSIGNB y<-y1 y1,				vpsignb,			2ymm2ymm)
	FUNCDECL(VPSIGNW x<-x1 x1,				vpsignw,			2xmm2xmm)
	FUNCDECL(VPSIGNW y<-y1 y1,				vpsignw,			2ymm2ymm)
	FUNCDECL(VPSIGND x<-x1 x1,				vpsignd,			2xmm2xmm)
	FUNCDECL(VPSIGND y<-y1 y1,				vpsignd,			2ymm2ymm)
	FUNCDECL(VAESENC x<-x1 x1,				vaesenc,			2xmm2xmm)
	FUNCDECL(VAESENC y<-y1 y1,				vaesenc,			2ymm2ymm)
	FUNCDECL(VAESENCLAST x<-x1 x1,			vaesenclast,		2xmm2xmm)
	FUNCDECL(VAESENCLAST y<-y1 y1,			vaesenclast,		2ymm2ymm)
	FUNCDECL(VAESDEC x<-x1 x1,				vaesdec,			2xmm2xmm)
	FUNCDECL(VAESDEC y<-y1 y1,				vaesdec,			2ymm2ymm)
	FUNCDECL(VAESDECLAST x<-x1 x1,			vaesdeclast,		2xmm2xmm)
	FUNCDECL(VAESDECLAST y<-y1 y1,			vaesdeclast,		2ymm2ymm)
	FUNCDECL(VAESENC x<-x1 x2,				vaesenc,			2xmm2xmmRot)
	FUNCDECL(VAESENC y<-y1 y2,				vaesenc,			2ymm2ymmRot)
	FUNCDECL(VAESENCLAST x<-x1 x2,			vaesenclast,		2xmm2xmmRot)
	FUNCDECL(VAESENCLAST y<-y1 y2,			vaesenclast,		2ymm2ymmRot)
	FUNCDECL(VAESDEC x<-x1 x2,				vaesdec,			2xmm2xmmRot)
	FUNCDECL(VAESDEC y<-y1 y2,				vaesdec,			2ymm2ymmRot)
	FUNCDECL(VAESDECLAST x<-x1 x2,			vaesdeclast,		2xmm2xmmRot)
	FUNCDECL(VAESDECLAST y<-y1 y2,			vaesdeclast,		2ymm2ymmRot)
	FUNCDECL(VAESIMC x<-x,					vaesimc,			xmm2xmm)
	FUNCDECL(VAESKEYGENASSIST x-<x i,		vaeskeygenassist,	xmmi2xmm)
	FUNCDECL(VPHMINPOSUW x<-x,				vphminposuw,		xmm2xmm)
	FUNCDECL(VPERMILPD x<-x1 x1,			vpermilpd,			2xmm2xmm)
	FUNCDECL(VPERMILPD y<-y1 y1,			vpermilpd,			2ymm2ymm)
	FUNCDECL(VPERMILPS x<-x1 x1,			vpermilps,			2xmm2xmm)
	FUNCDECL(VPERMILPS y<-y1 y1,			vpermilps,			2ymm2ymm)
	FUNCDECL0(-------- Port12 Int -------)
	FUNCDECL(VPSLLVD x<-x1 x1,				vpsllvd,			2xmm2xmm)
	FUNCDECL(VPSLLVD y<-y1 y1,				vpsllvd,			2ymm2ymm)
	FUNCDECL(VPSRLVD x<-x1 x1,				vpsrlvd,			2xmm2xmm)
	FUNCDECL(VPSRLVD y<-y1 y1,				vpsrlvd,			2ymm2ymm)
	FUNCDECL(VPSRAVD x<-x1 x1,				vpsravd,			2xmm2xmm)
	FUNCDECL(VPSRAVD y<-y1 y1,				vpsravd,			2ymm2ymm)
	FUNCDECL(VPSLLVQ x<-x1 x1,				vpsllvq,			2xmm2xmm)
	FUNCDECL(VPSLLVQ y<-y1 y1,				vpsllvq,			2ymm2ymm)
	FUNCDECL(VPSRLVQ x<-x1 x1,				vpsrlvq,			2xmm2xmm)
	FUNCDECL(VPSRLVQ y<-y1 y1,				vpsrlvq,			2ymm2ymm)
	FUNCDECL(VPSLLW x<-x i,					vpsllw,				xmmi2xmm)
	FUNCDECL(VPSLLW y<-y i,					vpsllw,				ymmi2ymm)
	FUNCDECL(VPSRLW x<-x i,					vpsrlw,				xmmi2xmm)
	FUNCDECL(VPSRLW y<-y i,					vpsrlw,				ymmi2ymm)
	FUNCDECL(VPSRAW x<-x i,					vpsraw,				xmmi2xmm)
	FUNCDECL(VPSRAW y<-y i,					vpsraw,				ymmi2ymm)
	FUNCDECL(VPSLLD x<-x i,					vpslld,				xmmi2xmm)
	FUNCDECL(VPSLLD y<-y i,					vpslld,				ymmi2ymm)
	FUNCDECL(VPSRLD x<-x i,					vpsrld,				xmmi2xmm)
	FUNCDECL(VPSRLD y<-y i,					vpsrld,				ymmi2ymm)
	FUNCDECL(VPSRAD x<-x i,					vpsrad,				xmmi2xmm)
	FUNCDECL(VPSRAD y<-y i,					vpsrad,				ymmi2ymm)
	FUNCDECL(VPSLLQ x<-x i,					vpsllq,				xmmi2xmm)
	FUNCDECL(VPSLLQ y<-y i,					vpsllq,				ymmi2ymm)
	FUNCDECL(VPSRLQ x<-x i,					vpsrlq,				xmmi2xmm)
	FUNCDECL(VPSRLQ y<-y i,					vpsrlq,				ymmi2ymm)
	FUNCDECL(VPSLLDQ x<-x i,				vpslldq,			xmmi2xmm)
	FUNCDECL(VPSLLDQ y<-y i,				vpslldq,			ymmi2ymm)
	FUNCDECL(VPSRLDQ x<-x i,				vpsrldq,			xmmi2xmm)
	FUNCDECL(VPSRLDQ y<-y i,				vpsrldq,			ymmi2ymm)
	FUNCDECL(VPUNPCKLBW x<-x1 x1,			vpunpcklbw,			2xmm2xmm)
	FUNCDECL(VPUNPCKLBW y<-y1 y1,			vpunpcklbw,			2ymm2ymm)
	FUNCDECL(VPUNPCKHBW x<-x1 x1,			vpunpckhbw,			2xmm2xmm)
	FUNCDECL(VPUNPCKHBW y<-y1 y1,			vpunpckhbw,			2ymm2ymm)
	FUNCDECL(VPUNPCKLWD x<-x1 x1,			vpunpcklwd,			2xmm2xmm)
	FUNCDECL(VPUNPCKLWD y<-y1 y1,			vpunpcklwd,			2ymm2ymm)
	FUNCDECL(VPUNPCKHWD x<-x1 x1,			vpunpckhwd,			2xmm2xmm)
	FUNCDECL(VPUNPCKHWD y<-y1 y1,			vpunpckhwd,			2ymm2ymm)
	FUNCDECL(VPUNPCKLDQ x<-x1 x1,			vpunpckldq,			2xmm2xmm)
	FUNCDECL(VPUNPCKLDQ y<-y1 y1,			vpunpckldq,			2ymm2ymm)
	FUNCDECL(VPUNPCKHDQ x<-x1 x1,			vpunpckhdq,			2xmm2xmm)
	FUNCDECL(VPUNPCKHDQ y<-y1 y1,			vpunpckhdq,			2ymm2ymm)
	FUNCDECL(VPUNPCKLQDQ x<-x1 x1,			vpunpcklqdq,		2xmm2xmm)
	FUNCDECL(VPUNPCKLQDQ y<-y1 y1,			vpunpcklqdq,		2ymm2ymm)
	FUNCDECL(VPUNPCKHQDQ x<-x1 x1,			vpunpckhqdq,		2xmm2xmm)
	FUNCDECL(VPUNPCKHQDQ y<-y1 y1,			vpunpckhqdq,		2ymm2ymm)
	FUNCDECL(VUNPCKLPS x<-x1 x1,			vunpcklps,			2xmm2xmm)
	FUNCDECL(VUNPCKLPS y<-y1 y1,			vunpcklps,			2ymm2ymm)
	FUNCDECL(VUNPCKHPS x<-x1 x1,			vunpckhps,			2xmm2xmm)
	FUNCDECL(VUNPCKHPS y<-y1 y1,			vunpckhps,			2ymm2ymm)
	FUNCDECL(VUNPCKLPD x<-x1 x1,			vunpcklpd,			2xmm2xmm)
	FUNCDECL(VUNPCKLPD y<-y1 y1,			vunpcklpd,			2ymm2ymm)
	FUNCDECL(VUNPCKHPD x<-x1 x1,			vunpckhpd,			2xmm2xmm)
	FUNCDECL(VUNPCKHPD y<-y1 y1,			vunpckhpd,			2ymm2ymm)
	FUNCDECL(VMOVHLPS x<-x1 x1,				vmovhlps,			2xmm2xmm)
	FUNCDECL(VMOVLHPS x<-x1 x1,				vmovlhps,			2xmm2xmm)
	FUNCDECL(VPACKSSWB x<-x1 x1,			vpacksswb,			2xmm2xmm)
	FUNCDECL(VPACKSSWB y<-y1 y1,			vpacksswb,			2ymm2ymm)
	FUNCDECL(VPACKUSWB x<-x1 x1,			vpackuswb,			2xmm2xmm)
	FUNCDECL(VPACKUSWB y<-y1 y1,			vpackuswb,			2ymm2ymm)
	FUNCDECL(VPACKSSDW x<-x1 x1,			vpackssdw,			2xmm2xmm)
	FUNCDECL(VPACKSSDW y<-y1 y1,			vpackssdw,			2ymm2ymm)
	FUNCDECL(VPACKUSDW x<-x1 x1,			vpackusdw,			2xmm2xmm)
	FUNCDECL(VPACKUSDW y<-y1 y1,			vpackusdw,			2ymm2ymm)
	FUNCDECL(VPERMILPD x<-x i,				vpermilpd,			xmmi2xmm)
	FUNCDECL(VPERMILPD y<-y i,				vpermilpd,			ymmi2ymm)
	FUNCDECL(VPERMILPS x<-x i,				vpermilps,			xmmi2xmm)
	FUNCDECL(VPERMILPS y<-y i,				vpermilps,			ymmi2ymm)
	FUNCDECL(VSHUFPD x<-x1 x1 i,			vshufpd,			2xmmi2xmm)
	FUNCDECL(VSHUFPD y<-y1 y1 i,			vshufpd,			2ymmi2ymm)
	FUNCDECL(VSHUFPS x<-x1 x1 i,			vshufps,			2xmmi2xmm)
	FUNCDECL(VSHUFPS y<-y1 y1 i,			vshufps,			2ymmi2ymm)
	FUNCDECL(VPSHUFB x<-x1 x1,				vpshufb,			2xmm2xmm)
	FUNCDECL(VPSHUFB y<-y1 y1,				vpshufb,			2ymm2ymm)
	FUNCDECL(VPSHUFLW x<-x i,				vpshuflw,			xmmi2xmm)
	FUNCDECL(VPSHUFLW y<-y i,				vpshuflw,			ymmi2ymm)
	FUNCDECL(VPSHUFHW x<-x i,				vpshufhw,			xmmi2xmm)
	FUNCDECL(VPSHUFHW y<-y i,				vpshufhw,			ymmi2ymm)
	FUNCDECL(VPSHUFD x<-x i,				vpshufd,			xmmi2xmm)
	FUNCDECL(VPSHUFD y<-y i,				vpshufd,			ymmi2ymm)
	FUNCDECL(VPALIGNR x<-x1 x1 i,			vpalignr,			2xmmi2xmm)
	FUNCDECL(VPALIGNR y<-y1 y1 i,			vpalignr,			2ymmi2ymm)
	FUNCDECL(VMOVDDUP x<-x,					vmovddup,			xmm2xmm)
	FUNCDECL(VMOVDDUP y<-y,					vmovddup,			ymm2ymm)
	FUNCDECL(VMOVSLDUP x<-x,				vmovsldup,			xmm2xmm)
	FUNCDECL(VMOVSLDUP y<-y,				vmovsldup,			ymm2ymm)
	FUNCDECL(VMOVSHDUP x<-x,				vmovshdup,			xmm2xmm)
	FUNCDECL(VMOVSHDUP y<-y,				vmovshdup,			ymm2ymm)
	FUNCDECL(VPBROADCASTB x<-x,				vpbroadcastb,		xmm2xmm)
	FUNCDECL(VPBROADCASTW x<-x,				vpbroadcastw,		xmm2xmm)
	FUNCDECL(VPBROADCASTD x<-x,				vpbroadcastd,		xmm2xmm)
	FUNCDECL(VPBROADCASTQ x<-x,				vpbroadcastq,		xmm2xmm)
	FUNCDECL(VPMOVZXBW x<-x,				vpmovzxbw,			xmm2xmm)
	FUNCDECL(VPMOVZXBD x<-x,				vpmovzxbd,			xmm2xmm)
	FUNCDECL(VPMOVZXBQ x<-x,				vpmovzxbq,			xmm2xmm)
	FUNCDECL(VPMOVZXWD x<-x,				vpmovzxwd,			xmm2xmm)
	FUNCDECL(VPMOVZXWQ x<-x,				vpmovzxwq,			xmm2xmm)
	FUNCDECL(VPMOVZXDQ x<-x,				vpmovzxdq,			xmm2xmm)
	FUNCDECL(VPMOVSXBW x<-x,				vpmovsxbw,			xmm2xmm)
	FUNCDECL(VPMOVSXBD x<-x,				vpmovsxbd,			xmm2xmm)
	FUNCDECL(VPMOVSXBQ x<-x,				vpmovsxbq,			xmm2xmm)
	FUNCDECL(VPMOVSXWD x<-x,				vpmovsxwd,			xmm2xmm)
	FUNCDECL(VPMOVSXWQ x<-x,				vpmovsxwq,			xmm2xmm)
	FUNCDECL(VPMOVSXDQ x<-x,				vpmovsxdq,			xmm2xmm)
	FUNCDECL(VINSERTPS x<-x1 x1 i,			vinsertps,			2xmmi2xmm)
	FUNCDECL0(-------- Port03 Int -------)
	FUNCDECL(VPMULHW x<-x1 x1,				vpmulhw,			2xmm2xmm)
	FUNCDECL(VPMULHW y<-y1 y1,				vpmulhw,			2ymm2ymm)
	FUNCDECL(VPMULHUW x<-x1 x1,				vpmulhuw,			2xmm2xmm)
	FUNCDECL(VPMULHUW y<-y1 y1,				vpmulhuw,			2ymm2ymm)
	FUNCDECL(VPMULHRSW x<-x1 x1,			vpmulhrsw,			2xmm2xmm)
	FUNCDECL(VPMULHRSW y<-y1 y1,			vpmulhrsw,			2ymm2ymm)
	FUNCDECL(VPMULLW x<-x1 x1,				vpmullw,			2xmm2xmm)
	FUNCDECL(VPMULLW y<-y1 y1,				vpmullw,			2ymm2ymm)
	FUNCDECL(VPMULLD x<-x1 x1,				vpmulld,			2xmm2xmm)
	FUNCDECL(VPMULLD y<-y1 y1,				vpmulld,			2ymm2ymm)
	FUNCDECL(VPMULDQ x<-x1 x1,				vpmuldq,			2xmm2xmm)
	FUNCDECL(VPMULDQ y<-y1 y1,				vpmuldq,			2ymm2ymm)
	FUNCDECL(VPMULUDQ x<-x1 x1,				vpmuludq,			2xmm2xmm)
	FUNCDECL(VPMULUDQ y<-y1 y1,				vpmuludq,			2ymm2ymm)
	FUNCDECL(VPMADDWD x<-x1 x1,				vpmaddwd,			2xmm2xmm)
	FUNCDECL(VPMADDWD y<-y1 y1,				vpmaddwd,			2ymm2ymm)
	FUNCDECL(VPMADDUBSW x<-x1 x1,			vpmaddubsw,			2xmm2xmm)
	FUNCDECL(VPMADDUBSW y<-y1 y1,			vpmaddubsw,			2ymm2ymm)
	FUNCDECL(VPSADBW x<-x1 x1,				vpsadbw,			2xmm2xmm)
	FUNCDECL(VPSADBW y<-y1 y1,				vpsadbw,			2ymm2ymm)
	FUNCDECL0(----- P0 (Cross-lanes) ----)
	FUNCDECL(VINSERTI128 y<-y x i,			vinserti128,		xmmymmi2ymm)
	FUNCDECL(VINSERTF128 y<-y x i,			vinsertf128,		xmmymmi2ymm)
	FUNCDECL(VEXTRACTI128 x<-y i,			vextracti128,		ymmi2xmm)
	FUNCDECL(VEXTRACTF128 x<-y i,			vextractf128,		ymmi2xmm)
	FUNCDECL(VPERM2I128 y<-y y i,			vperm2i128,			2ymmi2ymm)
	FUNCDECL(VPERM2F128 y<-y y i,			vperm2f128,			2ymmi2ymm)
	FUNCDECL(VBROADCASTSS y<-x,				vbroadcastss,		xmm2ymm)
	FUNCDECL(VBROADCASTSD y<-x,				vbroadcastsd,		xmm2ymm)
	FUNCDECL(VPBROADCASTB y<-x,				vpbroadcastb,		xmm2ymm)
	FUNCDECL(VPBROADCASTW y<-x,				vpbroadcastw,		xmm2ymm)
	FUNCDECL(VPBROADCASTD y<-x,				vpbroadcastd,		xmm2ymm)
	FUNCDECL(VPBROADCASTQ y<-x,				vpbroadcastq,		xmm2ymm)
	FUNCDECL0(------ P1 (DIV/SQRT) ------)
	FUNCDECL(VDIVPD x<-x1 x1,				vdivpd,				2xmm2xmm2)
	FUNCDECL(VDIVPD y<-y1 y1,				vdivpd,				2ymm2ymm2)
	FUNCDECL(VDIVSD x<-x1 x1,				vdivsd,				2xmm2xmm2)
	FUNCDECL(VDIVPS x<-x1 x1,				vdivps,				2xmm2xmm2)
	FUNCDECL(VDIVPS y<-y1 y1,				vdivps,				2ymm2ymm2)
	FUNCDECL(VDIVSS y<-y1 y1,				vdivss,				2xmm2xmm2)
	FUNCDECL(VSQRTPD x<-x,					vsqrtpd,			xmm2xmm1)
	FUNCDECL(VSQRTPD y<-y,					vsqrtpd,			ymm2ymm1)
	FUNCDECL(VSQRTSD x<-x1 x1,				vsqrtsd,			2xmm2xmm1)
	FUNCDECL(VSQRTPS x<-x,					vsqrtps,			xmm2xmm1)
	FUNCDECL(VSQRTPS y<-y,					vsqrtps,			ymm2ymm1)
	FUNCDECL(VSQRTSS y<-y1 y1,				vsqrtss,			2xmm2xmm1)
	FUNCDECL0(-------- GPR<->VEC --------)
	FUNCDECL(VMOVD gpr32<-x,				vmovd,				xmm2gpr32)
	FUNCDECL(VMOVD gpr64<-x,				vmovd,				xmm2gpr64)
	FUNCDECL(VMOVD x<-gpr32,				vmovd,				gpr32_2xmm)
	FUNCDECL(VMOVD x<-gpr64,				vmovd,				gpr64_2xmm)
	FUNCDECL(VPEXTRB gpr32<-x,				vpextrb,			xmmi2gpr32)
	FUNCDECL(VPEXTRB gpr64<-x,				vpextrb,			xmmi2gpr64)
	FUNCDECL(VPEXTRW gpr32<-x,				vpextrw,			xmmi2gpr32)
	FUNCDECL(VPEXTRW gpr64<-x,				vpextrw,			xmmi2gpr64)
	FUNCDECL(VPEXTRD gpr32<-x,				vpextrd,			xmmi2gpr32)
	FUNCDECL(VPEXTRD gpr64<-x,				vpextrd,			xmmi2gpr64)
	FUNCDECL(VPEXTRQ gpr64<-x,				vpextrq,			xmmi2gpr64)
	FUNCDECL(VPINSRB x<-gpr32,				vpinsrb,			gpr32i2xmm)
	FUNCDECL(VPINSRW x<-gpr32,				vpinsrw,			gpr32i2xmm)
	FUNCDECL(VPINSRD x<-gpr32,				vpinsrd,			gpr32i2xmm)
	FUNCDECL(VPINSRQ x<-gpr64,				vpinsrq,			gpr64i2xmm)
	FUNCDECL(VCVTSS2SI gpr32<-x,			vcvtss2si,			xmm2gpr32)
	FUNCDECL(VCVTSS2SI gpr64<-x,			vcvtss2si,			xmm2gpr64)
	FUNCDECL(VCVTSD2SI gpr32<-x,			vcvtsd2si,			xmm2gpr32)
	FUNCDECL(VCVTSD2SI gpr64<-x,			vcvtsd2si,			xmm2gpr64)
	FUNCDECL(VCVTSI2SS x<-gpr32,			vcvtsi2ss,			gpr32xmm2xmm)
	FUNCDECL(VCVTSI2SS x<-gpr64,			vcvtsi2ss,			gpr64xmm2xmm)
	FUNCDECL(VCVTSI2SD x<-gpr32,			vcvtsi2sd,			gpr32xmm2xmm)
	FUNCDECL(VCVTSI2SD x<-gpr64,			vcvtsi2sd,			gpr64xmm2xmm)
	FUNCDECL(VEXTRACTPS gpr32<-x i,			vextractps,			xmmi2gpr32)
	FUNCDECL(VPMOVMSKB gpr32<-x,			vpmovmskb,			xmm2gpr32)
	FUNCDECL(VPMOVMSKB gpr64<-x,			vpmovmskb,			xmm2gpr64)
	FUNCDECL(VPMOVMSKB gpr32<-y,			vpmovmskb,			ymm2gpr32)
	FUNCDECL(VPMOVMSKB gpr64<-y,			vpmovmskb,			ymm2gpr64)
	FUNCDECL(VMOVMSKPD gpr32<-x,			vmovmskpd,			xmm2gpr32)
	FUNCDECL(VMOVMSKPD gpr64<-x,			vmovmskpd,			xmm2gpr64)
	FUNCDECL(VMOVMSKPD gpr32<-y,			vmovmskpd,			ymm2gpr32)
	FUNCDECL(VMOVMSKPD gpr64<-y,			vmovmskpd,			ymm2gpr64)
	FUNCDECL(VMOVMSKPS gpr32<-x,			vmovmskps,			xmm2gpr32)
	FUNCDECL(VMOVMSKPS gpr64<-x,			vmovmskps,			xmm2gpr64)
	FUNCDECL(VMOVMSKPS gpr32<-y,			vmovmskps,			ymm2gpr32)
	FUNCDECL(VMOVMSKPS gpr64<-y,			vmovmskps,			ymm2gpr64)
	FUNCDECL(VPTEST f<-x1 x1,				vptest,				xmm2F)
	FUNCDECL(VPTEST f<-y1 y1,				vptest,				ymm2F)
	FUNCDECL(VTESTPD f<-x1 x1,				vtestpd,			xmm2F)
	FUNCDECL(VTESTPD f<-y1 y1,				vtestpd,			ymm2F)
	FUNCDECL(VTESTPS f<-x1 x1,				vtestps,			xmm2F)
	FUNCDECL(VTESTPS f<-y1 y1,				vtestps,			ymm2F)
	FUNCDECL(VCOMISD f<-x1 x1,				vcomisd,			xmm2F)
	FUNCDECL(VCOMISS f<-y1 y1,				vcomiss,			xmm2F)
	FUNCDECL(VUCOMISD f<-x1 x1,				vucomisd,			xmm2F)
	FUNCDECL(VUCOMISS f<-y1 y1,				vucomiss,			xmm2F)
	FUNCDECL0(---------- uCode ----------)
	FUNCDECL(VPERMQ y<-y i,					vpermq,				ymmi2ymm)
	FUNCDECL(VPERMPD y<-y i,				vpermpd,			ymmi2ymm)
	FUNCDECL(VPERMD y<-y1 y1,				vpermd,				2ymm2ymm)
	FUNCDECL(VPERMPS y<-y1 y1,				vpermps,			2ymm2ymm)
	FUNCDECL(VPMOVZXBW y<-x,				vpmovzxbw,			xmm2ymm)
	FUNCDECL(VPMOVZXBD y<-x,				vpmovzxbd,			xmm2ymm)
	FUNCDECL(VPMOVZXBQ y<-x,				vpmovzxbq,			xmm2ymm)
	FUNCDECL(VPMOVZXWD y<-x,				vpmovzxwd,			xmm2ymm)
	FUNCDECL(VPMOVZXWQ y<-x,				vpmovzxwq,			xmm2ymm)
	FUNCDECL(VPMOVZXDQ y<-x,				vpmovzxdq,			xmm2ymm)
	FUNCDECL(VPMOVSXBW y<-x,				vpmovsxbw,			xmm2ymm)
	FUNCDECL(VPMOVSXBD y<-x,				vpmovsxbd,			xmm2ymm)
	FUNCDECL(VPMOVSXBQ y<-x,				vpmovsxbq,			xmm2ymm)
	FUNCDECL(VPMOVSXWD y<-x,				vpmovsxwd,			xmm2ymm)
	FUNCDECL(VPMOVSXWQ y<-x,				vpmovsxwq,			xmm2ymm)
	FUNCDECL(VPMOVSXDQ y<-x,				vpmovsxdq,			xmm2ymm)
	FUNCDECL(VCVTPS2PD y<-x,				vcvtps2pd,			xmm2ymm)
	FUNCDECL(VCVTPD2PS x<-y,				vcvtpd2ps,			ymm2xmm)
	FUNCDECL(VCVTDQ2PD y<-x,				vcvtdq2pd,			xmm2ymm)
	FUNCDECL(VCVTPD2DQ x<-y,				vcvtpd2dq,			ymm2xmm)
	FUNCDECL(VCVTPH2PS y<-x,				vcvtph2ps,			xmm2ymm)
	FUNCDECL(VCVTPS2PH x<-y i,				vcvtps2ph,			ymmi2xmm)
	FUNCDECL(VHADDPD x<-x1 x1,				vhaddpd,			2xmm2xmm)
	FUNCDECL(VHADDPD y<-y1 y1,				vhaddpd,			2ymm2ymm)
	FUNCDECL(VHADDPS x<-x1 x1,				vhaddps,			2xmm2xmm)
	FUNCDECL(VHADDPS y<-y1 y1,				vhaddps,			2ymm2ymm)
	FUNCDECL(VHSUBPD x<-x1 x1,				vhsubpd,			2xmm2xmm)
	FUNCDECL(VHSUBPD y<-y1 y1,				vhsubpd,			2ymm2ymm)
	FUNCDECL(VHSUBPS x<-x1 x1,				vhsubps,			2xmm2xmm)
	FUNCDECL(VHSUBPS y<-y1 y1,				vhsubps,			2ymm2ymm)
	FUNCDECL(VHADDW x<-x1 x1,				vphaddw,			2xmm2xmm)
	FUNCDECL(VHADDW y<-y1 y1,				vphaddw,			2ymm2ymm)
	FUNCDECL(VHADDD x<-x1 x1,				vphaddd,			2xmm2xmm)
	FUNCDECL(VHADDD y<-y1 y1,				vphaddd,			2ymm2ymm)
	FUNCDECL(VHSUBSW x<-x1 x1,				vphaddsw,			2xmm2xmm)
	FUNCDECL(VHSUBSW y<-y1 y1,				vphaddsw,			2ymm2ymm)
	FUNCDECL(VHSUBW x<-x1 x1,				vphsubw,			2xmm2xmm)
	FUNCDECL(VHSUBW y<-y1 y1,				vphsubw,			2ymm2ymm)
	FUNCDECL(VHSUBD x<-x1 x1,				vphsubd,			2xmm2xmm)
	FUNCDECL(VHSUBD y<-y1 y1,				vphsubd,			2ymm2ymm)
	FUNCDECL(VHSUBSW x<-x1 x1,				vphsubsw,			2xmm2xmm)
	FUNCDECL(VHSUBSW y<-y1 y1,				vphsubsw,			2ymm2ymm)
	FUNCDECL(VDPPD x<-x1 x1 i,				vdppd,				2xmmi2xmm)
	FUNCDECL(VDPPS x<-x1 x1 i,				vdpps,				2xmmi2xmm)
	FUNCDECL(VDPPS y<-y1 y1 i,				vdpps,				2ymmi2ymm)
	FUNCDECL(VPCLMULQDQ x<-x1 x1 i,			vpclmulqdq,			2xmmi2xmm)
	FUNCDECL(VPCLMULQDQ y<-y1 y1 i,			vpclmulqdq,			2ymmi2ymm)
	FUNCDECL(VMPSADBW x<-x1 x1 i,			vmpsadbw,			2xmmi2xmm)
	FUNCDECL(VMPSADBW y<-y1 y1 i,			vmpsadbw,			2ymmi2ymm)
	FUNCDECL0(----------- x87 -----------)
	FUNCDECL(FADD,							fadd,				x87_2op)
	FUNCDECL(FSUB,							fsub,				x87_2op)
	FUNCDECL(FMUL,							fmul,				x87_2op)
	FUNCDECL(FDIV,							fdiv,				x87_2op1)
	FUNCDECL(FSQRT,							fsqrt,				noop1)
	FUNCDECL(FXCH,							fxch,				x87_1op)
	FUNCDECL(FABS,							fabs,				noop)
	FUNCDECL(FCHS,							fchs,				noop)
	FUNCDECL(FTST,							ftst,				noop)
	FUNCDECL(FCOM,							fcom,				x87_1op)
	FUNCDECL(FCOMI,							fcomi,				x87_2opR)
	FUNCDECL(FLD + FSTP,					fld,				x87_1op_fstp)
	FUNCDECL(FLDZ + FSTP,					fldz,				x87_fstp)
	FUNCDECL(FLD1 + FSTP,					fld1,				x87_fstp)
	FUNCDECL(FLDPI + FSTP,					fldpi,				x87_fstp)
	FUNCDECL(FST,							fst,				x87_1op)
	FUNCDECL(FXAM,							fxam,				noop)
	FUNCDECL(FDECSTP,						fdecstp,			noop)
	FUNCDECL(FINCSTP,						fincstp,			noop)
	FUNCDECL(FNOP,							fnop,				noop)
};

methods_ucode m2[] = {
	FUNCDECL_UCODE0(---------- uCode ----------)
	FUNCDECL_UCODE(VPERMQ y<-y1 i,				vpermq)
	FUNCDECL_UCODE(VPERMD y<-y1 y1,				vpermd)
	FUNCDECL_UCODE(VPMOVZXBQ y<-x,				vpmovzxbq)
	FUNCDECL_UCODE(VPCLMULQDQ y<-y1 y1 0,		vpclmulqdq)
	FUNCDECL_UCODE(VMPSADBW y<-y1 y1 0,			vmpsadbw)
	FUNCDECL_UCODE(VDPPD x<-x1 x1 i,			vdppd)
	FUNCDECL_UCODE(VPHADDD y<-y1 y1,			vphaddd)
	FUNCDECL_UCODE(VHADDPD y<-y1 y1,			vhaddpd)
	FUNCDECL_UCODE(VCVTPS2PD y<-x,				vcvtps2pd)
	FUNCDECL_UCODE(VCVTPD2PS x<-y,				vcvtpd2ps)
	FUNCDECL_UCODE(VDIVPD y<-y1 y1,				vdivpd)
	FUNCDECL_UCODE(VDIVPS y<-y1 y1,				vdivps)
	FUNCDECL_UCODE(VDIVSD x<-x1 x1,				vdivsd)
	FUNCDECL_UCODE(VDIVSS x<-x1 x1,				vdivss)
	FUNCDECL_UCODE(VSQRTPD y<-y1,				vsqrtpd)
	FUNCDECL_UCODE(VSQRTPS y<-y1,				vsqrtps)
	FUNCDECL_UCODE(VSQRTSD x<-x1 x1,			vsqrtsd)
	FUNCDECL_UCODE(VSQRTSS x<-x1 x1,			vsqrtss)
	FUNCDECL_UCODE(FSQRT32,						fsqrt32)
	FUNCDECL_UCODE(FSQRT64,						fsqrt64)
	FUNCDECL_UCODE(FSQRT80,						fsqrt80)
	FUNCDECL_UCODE(FDIV32,						fdiv32)
	FUNCDECL_UCODE(FDIV64,						fdiv64)
	FUNCDECL_UCODE(FDIV80,						fdiv80)
};

void Test(int index) {
	volatile unsigned __int64 minres = ULONG_MAX;
	if (m[index].funcs[0] != nullptr) {
		cout << setw(3) << right << dec << setfill(' ') << index << '|';
		cout << setw(27) << left << m[index].name << '|' << right;
		for (int f = 0; f < FUNCS; f++) {
			minres = ULONG_MAX;
			(m[index].funcs[f])();
			for (int rep = 0; rep < REPEATS; rep++) {
				minres = min(minres, (m[index].funcs[f])());
			}
			cout << setw(9) << minres << ",";
		}
	} else {
		cout << "   |";
		cout << setw(27) << left << m[index].name << '|' << right;
		cout << "--LATENCY--IIDOMAIN--FFDOMAIN--IFDOMAIN--FIDOMAIN-----PORT0----PORT1-----PORT01----PORT03-----PORT2----PORT12----PORT23--PORT0123----PORT45------LDs-";
	}
	cout << endl;
};

void Test_ucode(int index) {
	volatile unsigned __int64 minres = ULONG_MAX;
	if (m2[index].funcs[0] != nullptr) {
		cout << setw(3) << right << index << '|';
		cout << setw(27) << left << m2[index].name << '|' << right;
		for (int f = 0; f < FUNCS_UCODE; f++) {
			minres = ULONG_MAX;
			(m2[index].funcs[f])();
			for (int rep = 0; rep < REPEATS; rep++) {
				minres = min(minres, (m2[index].funcs[f])());
			}
			cout << setw(9) << minres << ",";
		}
	} else {
		cout << "   |";
		cout << setw(27) << left << m2[index].name << '|' << right;
		cout << "--LATENCY--IIDOMAIN--FFDOMAIN--IFDOMAIN--FIDOMAIN---P0_1_23----P01_23----P03_12-----PORT0-----PORT1----PORT01";
	}
	cout << endl;
};

void Zen3_Demo(void)
{
	SetProcessAffinityMask(GetCurrentProcess(), 8);
	SetThreadAffinityMask(GetCurrentThread(), 8);
	Sleep(0);
	for (int b = 0; b < sizeof(m) / sizeof(methods); b++) {
		Test(b);
	}
	for (int b2 = 0; b2 < sizeof(m2) / sizeof(methods_ucode); b2++) {
		Test_ucode(b2);
	}
}
