#pragma once

ZEN3_FUNCDEF(mulpd,				xmm2xmm)	
ZEN3_FUNCDEF(mulps,				xmm2xmm)	
ZEN3_FUNCDEF(mulsd,				xmm2xmm)	
ZEN3_FUNCDEF(mulss,				xmm2xmm)	
ZEN3_FUNCDEF(rcpps,				xmm2xmm)	
ZEN3_FUNCDEF(rcpss,				xmm2xmm)	
ZEN3_FUNCDEF(rsqrtps,			xmm2xmm)	
ZEN3_FUNCDEF(rsqrtss,			xmm2xmm)	
ZEN3_FUNCDEF(pblendvb,			xmm0_2xmm)	
ZEN3_FUNCDEF(blendvpd,			xmm0_2xmm)	
ZEN3_FUNCDEF(blendvps,			xmm0_2xmm)	

ZEN3_FUNCDEF(addpd,				xmm2xmm)	
ZEN3_FUNCDEF(addps,				xmm2xmm)	
ZEN3_FUNCDEF(addsd,				xmm2xmm)	
ZEN3_FUNCDEF(addss,				xmm2xmm)	
ZEN3_FUNCDEF(subpd,				xmm2xmm)	
ZEN3_FUNCDEF(subps,				xmm2xmm)	
ZEN3_FUNCDEF(subsd,				xmm2xmm)	
ZEN3_FUNCDEF(subss,				xmm2xmm)	
ZEN3_FUNCDEF(addsubpd,			xmm2xmm)	
ZEN3_FUNCDEF(addsubps,			xmm2xmm)	
ZEN3_FUNCDEF(roundpd,			xmmi2xmm)	
ZEN3_FUNCDEF(roundps,			xmmi2xmm)	
ZEN3_FUNCDEF(roundsd,			xmmi2xmm)	
ZEN3_FUNCDEF(roundss,			xmmi2xmm)	
ZEN3_FUNCDEF(cvtps2dq,			xmm2xmm)	
ZEN3_FUNCDEF(cvtps2pd,			xmm2xmm)	
ZEN3_FUNCDEF(cvtpd2ps,			xmm2xmm)	
ZEN3_FUNCDEF(cvtpd2dq,			xmm2xmm)	
ZEN3_FUNCDEF(cvtdq2pd,			xmm2xmm)	
ZEN3_FUNCDEF(cvtdq2ps,			xmm2xmm)	
ZEN3_FUNCDEF(cvtss2sd,			xmm2xmm)	
ZEN3_FUNCDEF(cvtsd2ss,			xmm2xmm)	

ZEN3_FUNCDEF(minpd,				xmm2xmm)	
ZEN3_FUNCDEF(minps,				xmm2xmm)	
ZEN3_FUNCDEF(minsd,				xmm2xmm)	
ZEN3_FUNCDEF(minss,				xmm2xmm)	
ZEN3_FUNCDEF(maxpd,				xmm2xmm)	
ZEN3_FUNCDEF(maxps,				xmm2xmm)	
ZEN3_FUNCDEF(maxsd,				xmm2xmm)	
ZEN3_FUNCDEF(maxss,				xmm2xmm)	
ZEN3_FUNCDEF(cmpeqpd,			xmm2xmm)	
ZEN3_FUNCDEF(cmpeqps,			xmm2xmm)	
ZEN3_FUNCDEF(cmpeqsd,			xmm2xmm)	
ZEN3_FUNCDEF(cmpeqss,			xmm2xmm)	

ZEN3_FUNCDEF(andpd,				xmm2xmm)	
ZEN3_FUNCDEF(andps,				xmm2xmm)	
ZEN3_FUNCDEF(andnpd,			xmm2xmmRot)	
ZEN3_FUNCDEF(andnps,			xmm2xmmRot)	
ZEN3_FUNCDEF(orpd,				xmm2xmm)	
ZEN3_FUNCDEF(orps,				xmm2xmm)	
ZEN3_FUNCDEF(xorpd,				xmm2xmmRot)	
ZEN3_FUNCDEF(xorps,				xmm2xmmRot)	
ZEN3_FUNCDEF(blendpd,			xmmi2xmm)	
ZEN3_FUNCDEF(blendps,			xmmi2xmm)	

ZEN3_FUNCDEF(pand,				xmm2xmm)	
ZEN3_FUNCDEF(pandn,				xmm2xmm)	
ZEN3_FUNCDEF(pandn,				xmm2xmmRot)	
ZEN3_FUNCDEF(por,				xmm2xmm)	
ZEN3_FUNCDEF(pxor,				xmm2xmm)	
ZEN3_FUNCDEF(pxor,				xmm2xmmRot)	
ZEN3_FUNCDEF(pblendw,			xmmi2xmm)	

ZEN3_FUNCDEF(paddb,				xmm2xmm)	
ZEN3_FUNCDEF(paddw,				xmm2xmm)	
ZEN3_FUNCDEF(paddd,				xmm2xmm)	
ZEN3_FUNCDEF(paddq,				xmm2xmm)	
ZEN3_FUNCDEF(psubb,				xmm2xmmRot)	
ZEN3_FUNCDEF(psubw,				xmm2xmmRot)	
ZEN3_FUNCDEF(psubd,				xmm2xmmRot)	
ZEN3_FUNCDEF(psubq,				xmm2xmmRot)	

ZEN3_FUNCDEF(pcmpeqb,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpeqw,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpeqd,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpgtb,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpgtw,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpgtd,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpgtq,			xmm2xmmRot)	

ZEN3_FUNCDEF(pminsb,			xmm2xmm)	
ZEN3_FUNCDEF(pminub,			xmm2xmm)	
ZEN3_FUNCDEF(pminsw,			xmm2xmm)	
ZEN3_FUNCDEF(pminuw,			xmm2xmm)	
ZEN3_FUNCDEF(pminsd,			xmm2xmm)	
ZEN3_FUNCDEF(pminud,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxsb,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxub,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxsw,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxuw,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxsd,			xmm2xmm)	
ZEN3_FUNCDEF(pmaxud,			xmm2xmm)	

ZEN3_FUNCDEF(paddsb,			xmm2xmm)	
ZEN3_FUNCDEF(paddsw,			xmm2xmm)	
ZEN3_FUNCDEF(psubsb,			xmm2xmmRot)	
ZEN3_FUNCDEF(psubsw,			xmm2xmmRot)	
ZEN3_FUNCDEF(pcmpeqq,			xmm2xmmRot)	
ZEN3_FUNCDEF(pabsb,				xmm2xmm)	
ZEN3_FUNCDEF(pabsw,				xmm2xmm)	
ZEN3_FUNCDEF(pabsd,				xmm2xmm)	
ZEN3_FUNCDEF(pavgb,				xmm2xmm)	
ZEN3_FUNCDEF(pavgw,				xmm2xmm)	
ZEN3_FUNCDEF(psignb,			xmm2xmm)	
ZEN3_FUNCDEF(psignw,			xmm2xmm)	
ZEN3_FUNCDEF(psignd,			xmm2xmm)	

ZEN3_FUNCDEF(aesenc,			xmm2xmm)	
ZEN3_FUNCDEF(aesenclast,		xmm2xmm)	
ZEN3_FUNCDEF(aesdec,			xmm2xmm)	
ZEN3_FUNCDEF(aesdeclast,		xmm2xmm)	
ZEN3_FUNCDEF(aesenc,			xmm2xmmRot)	
ZEN3_FUNCDEF(aesenclast,		xmm2xmmRot)	
ZEN3_FUNCDEF(aesdec,			xmm2xmmRot)	
ZEN3_FUNCDEF(aesdeclast,		xmm2xmmRot)	
ZEN3_FUNCDEF(aesimc,			xmm2xmm)	
ZEN3_FUNCDEF(aeskeygenassist,	xmmi2xmm)	
ZEN3_FUNCDEF(phminposuw,		xmm2xmm)	
ZEN3_FUNCDEF(extrq,				xmm2xmm)	
ZEN3_FUNCDEF(insertq	,		xmm2xmm)	

ZEN3_FUNCDEF(psllw,				xmm2xmm)	
ZEN3_FUNCDEF(psrlw,				xmm2xmm)	
ZEN3_FUNCDEF(psraw,				xmm2xmm)	
ZEN3_FUNCDEF(pslld,				xmm2xmm)	
ZEN3_FUNCDEF(psrld,				xmm2xmm)	
ZEN3_FUNCDEF(psrad,				xmm2xmm)	
ZEN3_FUNCDEF(psllq,				xmm2xmm)	
ZEN3_FUNCDEF(psrlq,				xmm2xmm)	

ZEN3_FUNCDEF(psllw,				i2xmm)		
ZEN3_FUNCDEF(psrlw,				i2xmm)		
ZEN3_FUNCDEF(psraw,				i2xmm)		
ZEN3_FUNCDEF(pslld,				i2xmm)		
ZEN3_FUNCDEF(psrld,				i2xmm)		
ZEN3_FUNCDEF(psrad,				i2xmm)		
ZEN3_FUNCDEF(psllq,				i2xmm)		
ZEN3_FUNCDEF(psrlq,				i2xmm)		

ZEN3_FUNCDEF(pslldq,			i2xmm)		
ZEN3_FUNCDEF(psrldq,			i2xmm)		

ZEN3_FUNCDEF(punpcklbw,			xmm2xmm)	
ZEN3_FUNCDEF(punpckhbw,			xmm2xmm)	
ZEN3_FUNCDEF(punpcklwd,			xmm2xmm)	
ZEN3_FUNCDEF(punpckhwd,			xmm2xmm)	
ZEN3_FUNCDEF(punpckldq,			xmm2xmm)	
ZEN3_FUNCDEF(punpckhdq,			xmm2xmm)	
ZEN3_FUNCDEF(punpcklqdq,		xmm2xmm)	
ZEN3_FUNCDEF(punpckhqdq,		xmm2xmm)	
ZEN3_FUNCDEF(unpcklps,			xmm2xmm)	
ZEN3_FUNCDEF(unpckhps,			xmm2xmm)	
ZEN3_FUNCDEF(unpcklpd,			xmm2xmm)	
ZEN3_FUNCDEF(unpckhpd,			xmm2xmm)	
ZEN3_FUNCDEF(movhlps,			xmm2xmm)	
ZEN3_FUNCDEF(movlhps,			xmm2xmm)	
ZEN3_FUNCDEF(packsswb,			xmm2xmm)	
ZEN3_FUNCDEF(packuswb,			xmm2xmm)	
ZEN3_FUNCDEF(packssdw,			xmm2xmm)	
ZEN3_FUNCDEF(packusdw,			xmm2xmm)	
ZEN3_FUNCDEF(shufpd,			xmmi2xmm)	
ZEN3_FUNCDEF(shufps,			xmmi2xmm)	
ZEN3_FUNCDEF(pshufb,			xmm2xmm)	
ZEN3_FUNCDEF(pshuflw,			xmmi2xmm)	
ZEN3_FUNCDEF(pshufhw,			xmmi2xmm)	
ZEN3_FUNCDEF(pshufd,			xmmi2xmm)	
ZEN3_FUNCDEF(palignr,			xmmi2xmm)	
ZEN3_FUNCDEF(movddup,			xmm2xmm)	
ZEN3_FUNCDEF(movsldup,			xmm2xmm)	
ZEN3_FUNCDEF(movshdup,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxbw,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxbd,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxbq,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxwd,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxwq,			xmm2xmm)	
ZEN3_FUNCDEF(pmovzxdq,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxbw,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxbd,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxbq,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxwd,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxwq,			xmm2xmm)	
ZEN3_FUNCDEF(pmovsxdq,			xmm2xmm)	
ZEN3_FUNCDEF(insertps,			xmmi2xmm)	

ZEN3_FUNCDEF(pmulhw,			xmm2xmm)	
ZEN3_FUNCDEF(pmulhuw,			xmm2xmm)	
ZEN3_FUNCDEF(pmulhrsw,			xmm2xmm)	
ZEN3_FUNCDEF(pmullw,			xmm2xmm)	
ZEN3_FUNCDEF(pmulld,			xmm2xmm)	
ZEN3_FUNCDEF(pmuldq,			xmm2xmm)	
ZEN3_FUNCDEF(pmuludq,			xmm2xmm)	
ZEN3_FUNCDEF(pmaddwd,			xmm2xmm)	
ZEN3_FUNCDEF(pmaddubsw,			xmm2xmm)	
ZEN3_FUNCDEF(psadbw,			xmm2xmm)	

ZEN3_FUNCDEF(divpd,				xmm2xmm2)	
ZEN3_FUNCDEF(divps,				xmm2xmm2)	
ZEN3_FUNCDEF(divsd,				xmm2xmm2)	
ZEN3_FUNCDEF(divss,				xmm2xmm2)	
ZEN3_FUNCDEF(sqrtpd,			xmm2xmm1)	
ZEN3_FUNCDEF(sqrtps,			xmm2xmm1)	
ZEN3_FUNCDEF(sqrtsd,			xmm2xmm1)	
ZEN3_FUNCDEF(sqrtss,			xmm2xmm1)	

ZEN3_FUNCDEF(movd,				xmm2gpr32)	
ZEN3_FUNCDEF(movd,				xmm2gpr64)	
ZEN3_FUNCDEF(movd,				gpr32_2xmm)	
ZEN3_FUNCDEF(movd,				gpr64_2xmm)	
ZEN3_FUNCDEF(movq2dq,			mm2xmm)	
ZEN3_FUNCDEF(movdq2q,			xmm2mm)	

ZEN3_FUNCDEF(pextrb,			xmmi2gpr32)	
ZEN3_FUNCDEF(pextrb,			xmmi2gpr64)	
ZEN3_FUNCDEF(pextrw,			xmmi2gpr32)	
ZEN3_FUNCDEF(pextrw,			xmmi2gpr64)	
ZEN3_FUNCDEF(pextrd,			xmmi2gpr32)	
ZEN3_FUNCDEF(pextrq,			xmmi2gpr64)	
ZEN3_FUNCDEF(pinsrb,			gpr32i2xmm)	
ZEN3_FUNCDEF(pinsrw,			gpr32i2xmm)	
ZEN3_FUNCDEF(pinsrd,			gpr32i2xmm)	
ZEN3_FUNCDEF(pinsrq,			gpr64i2xmm)	

ZEN3_FUNCDEF(cvtss2si,			xmm2gpr32)	
ZEN3_FUNCDEF(cvtss2si,			xmm2gpr64)	
ZEN3_FUNCDEF(cvtsd2si,			xmm2gpr32)	
ZEN3_FUNCDEF(cvtsd2si,			xmm2gpr64)	
ZEN3_FUNCDEF(cvtsi2ss,			gpr32_2xmm)	
ZEN3_FUNCDEF(cvtsi2ss,			gpr64_2xmm)	
ZEN3_FUNCDEF(cvtsi2sd,			gpr32_2xmm)	
ZEN3_FUNCDEF(cvtsi2sd,			gpr64_2xmm)	
ZEN3_FUNCDEF(extractps,			xmmi2gpr32)	

ZEN3_FUNCDEF(pmovmskb,			xmm2gpr32)	
ZEN3_FUNCDEF(pmovmskb,			xmm2gpr64)	

ZEN3_FUNCDEF(movmskpd,			xmm2gpr32)	
ZEN3_FUNCDEF(movmskpd,			xmm2gpr64)	

ZEN3_FUNCDEF(movmskps,			xmm2gpr32)	
ZEN3_FUNCDEF(movmskps,			xmm2gpr64)	

ZEN3_FUNCDEF(ptest,				xmm2F)		

ZEN3_FUNCDEF(comisd,			xmm2F)		
ZEN3_FUNCDEF(comiss,			xmm2F)		
ZEN3_FUNCDEF(ucomisd,			xmm2F)		
ZEN3_FUNCDEF(ucomiss,			xmm2F)		

ZEN3_FUNCDEF(haddpd,			xmm2xmm)	
ZEN3_FUNCDEF(haddps,			xmm2xmm)	
ZEN3_FUNCDEF(hsubpd,			xmm2xmm)	
ZEN3_FUNCDEF(hsubps,			xmm2xmm)	
ZEN3_FUNCDEF(phaddw,			xmm2xmm)	
ZEN3_FUNCDEF(phaddd,			xmm2xmm)	
ZEN3_FUNCDEF(phaddsw,			xmm2xmm)	
ZEN3_FUNCDEF(phsubw,			xmm2xmm)	
ZEN3_FUNCDEF(phsubd,			xmm2xmm)	
ZEN3_FUNCDEF(phsubsw,			xmm2xmm)	

ZEN3_FUNCDEF(dppd,				xmmi2xmm)	
ZEN3_FUNCDEF(dpps,				xmmi2xmm)	
ZEN3_FUNCDEF(pclmulqdq,			xmmi2xmm)	
ZEN3_FUNCDEF(mpsadbw,			xmmi2xmm)	
ZEN3_FUNCDEF(extrq,				ii2xmm)
ZEN3_FUNCDEF(insertq,			xmmii2xmm)

ZEN3_FUNCDEF(sha1msg1,			xmm2xmm)
ZEN3_FUNCDEF(sha1msg2,			xmm2xmm)
ZEN3_FUNCDEF(sha1nexte,			xmm2xmm)
ZEN3_FUNCDEF(sha1rnds4,			xmmi2xmm1)
ZEN3_FUNCDEF(sha256msg1,		xmm2xmm)
ZEN3_FUNCDEF(sha256msg2,		xmm2xmm)
ZEN3_FUNCDEF(sha256rnds2,		xmm0_2xmm1)

ZEN3_FUNCDEF(pcmpestri,			xmmi2xmm)
ZEN3_FUNCDEF(pcmpestrm,			xmmi2xmm)
ZEN3_FUNCDEF(pcmpistri,			xmmi2xmm)
ZEN3_FUNCDEF(pcmpistrm,			xmmi2xmm)

ZEN3_FUNCDEF(pand,				mm2mm)		
ZEN3_FUNCDEF(pandn,				mm2mm)		
ZEN3_FUNCDEF(pandn,				mm2mmRot)	
ZEN3_FUNCDEF(por,				mm2mm)		
ZEN3_FUNCDEF(pxor,				mm2mm)		
ZEN3_FUNCDEF(pxor,				mm2mmRot)	
ZEN3_FUNCDEF(paddb,				mm2mm)		
ZEN3_FUNCDEF(paddw,				mm2mm)		
ZEN3_FUNCDEF(paddd,				mm2mm)		
ZEN3_FUNCDEF(paddq,				mm2mm)		
ZEN3_FUNCDEF(psubb,				mm2mmRot)	
ZEN3_FUNCDEF(psubw,				mm2mmRot)	
ZEN3_FUNCDEF(psubd,				mm2mmRot)	
ZEN3_FUNCDEF(psubq,				mm2mmRot)	

ZEN3_FUNCDEF(paddsb,			mm2mm)
ZEN3_FUNCDEF(paddsw,			mm2mm)
ZEN3_FUNCDEF(psubsb,			mm2mmRot)
ZEN3_FUNCDEF(psubsw,			mm2mmRot)

ZEN3_FUNCDEF(pabsb,				mm2mm)
ZEN3_FUNCDEF(pabsw,				mm2mm)
ZEN3_FUNCDEF(pabsd,				mm2mm)
ZEN3_FUNCDEF(pavgb,				mm2mm)
ZEN3_FUNCDEF(pavgw,				mm2mm)
ZEN3_FUNCDEF(psignb,			mm2mm)
ZEN3_FUNCDEF(psignw,			mm2mm)
ZEN3_FUNCDEF(psignd,			mm2mm)

ZEN3_FUNCDEF(psllw,				mm2mm)
ZEN3_FUNCDEF(psrlw,				mm2mm)
ZEN3_FUNCDEF(psraw,				mm2mm)
ZEN3_FUNCDEF(pslld,				mm2mm)
ZEN3_FUNCDEF(psrld,				mm2mm)
ZEN3_FUNCDEF(psrad,				mm2mm)
ZEN3_FUNCDEF(psllq,				mm2mm)
ZEN3_FUNCDEF(psrlq,				mm2mm)

ZEN3_FUNCDEF(psllw,				i2mm)
ZEN3_FUNCDEF(psrlw,				i2mm)
ZEN3_FUNCDEF(psraw,				i2mm)
ZEN3_FUNCDEF(pslld,				i2mm)
ZEN3_FUNCDEF(psrld,				i2mm)
ZEN3_FUNCDEF(psrad,				i2mm)
ZEN3_FUNCDEF(psllq,				i2mm)
ZEN3_FUNCDEF(psrlq,				i2mm)

ZEN3_FUNCDEF(pshufw,			mmi2mm)
ZEN3_FUNCDEF(palignr,			mmi2mm)
ZEN3_FUNCDEF(punpcklbw,			mm2mm)
ZEN3_FUNCDEF(punpckhbw,			mm2mm)
ZEN3_FUNCDEF(punpcklwd,			mm2mm)
ZEN3_FUNCDEF(punpckhwd,			mm2mm)
ZEN3_FUNCDEF(punpckldq,			mm2mm)
ZEN3_FUNCDEF(punpckhdq,			mm2mm)
ZEN3_FUNCDEF(packsswb,			mm2mm)
ZEN3_FUNCDEF(packuswb,			mm2mm)
ZEN3_FUNCDEF(packssdw,			mm2mm)

ZEN3_FUNCDEF(pmulhw,			mm2mm)
ZEN3_FUNCDEF(pmulhuw,			mm2mm)
ZEN3_FUNCDEF(pmullw,			mm2mm)
ZEN3_FUNCDEF(pmuludq,			mm2mm)
ZEN3_FUNCDEF(pmaddwd,			mm2mm)

ZEN3_FUNCDEF(pmovmskb,			mm2gpr32)
ZEN3_FUNCDEF(movd,				mm2gpr32)
ZEN3_FUNCDEF(movd,				gpr32_2mm)
ZEN3_FUNCDEF(pextrw,			mmi2gpr32)
ZEN3_FUNCDEF(pinsrw,			gpr32i2mm)

ZEN3_FUNCDEF(movq2dq,			mm2xmm)
ZEN3_FUNCDEF(movdq2q,			xmm2mm)
ZEN3_FUNCDEF(cvtps2pi,			xmm2mm)
ZEN3_FUNCDEF(cvtpd2pi,			xmm2mm)
ZEN3_FUNCDEF(cvtpi2ps,			mm2xmm)
ZEN3_FUNCDEF(cvtpi2pd,			mm2xmm)

ZEN3_FUNCDEF(fadd32,			x87_2op)
ZEN3_FUNCDEF(fsub32,			x87_2op)
ZEN3_FUNCDEF(fmul32,			x87_2op)
ZEN3_FUNCDEF(fdiv32,			x87_2op1)
ZEN3_FUNCDEF(fsqrt32,			noop1)

ZEN3_FUNCDEF(fadd64,			x87_2op)
ZEN3_FUNCDEF(fsub64,			x87_2op)
ZEN3_FUNCDEF(fmul64,			x87_2op)
ZEN3_FUNCDEF(fdiv64,			x87_2op1)
ZEN3_FUNCDEF(fsqrt64,			noop1)

ZEN3_FUNCDEF(fadd80,			x87_2op)
ZEN3_FUNCDEF(fsub80,			x87_2op)
ZEN3_FUNCDEF(fmul80,			x87_2op)
ZEN3_FUNCDEF(fdiv80,			x87_2op1)
ZEN3_FUNCDEF(fsqrt80,			noop1)

ZEN3_FUNCDEF(fxch,				x87_1op)
ZEN3_FUNCDEF(fabs,				noop)
ZEN3_FUNCDEF(fchs,				noop)
ZEN3_FUNCDEF(ftst,				noop)
ZEN3_FUNCDEF(fcom,				x87_1op)
ZEN3_FUNCDEF(fcomi,				x87_2opR)
ZEN3_FUNCDEF(fld,				x87_1op_fstp)
ZEN3_FUNCDEF(fldz,				x87_fstp)
ZEN3_FUNCDEF(fld1,				x87_fstp)
ZEN3_FUNCDEF(fldpi,				x87_fstp)
ZEN3_FUNCDEF(fst,				x87_1op)
ZEN3_FUNCDEF(ffree,				x87_1op)
ZEN3_FUNCDEF(fxam,				noop)
ZEN3_FUNCDEF(fdecstp,			noop)
ZEN3_FUNCDEF(fincstp,			noop)
ZEN3_FUNCDEF(fnop,				noop)
