#pragma once

ZEN5_FUNCDEF(vmovaps,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovaps,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovaps,				zmm2zmm)
ZEN5_FUNCDEF(vmovapd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovapd,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovapd,				zmm2zmm)
ZEN5_FUNCDEF(vmovups,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovups,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovups,				zmm2zmm)
ZEN5_FUNCDEF(vmovupd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovupd,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovupd,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqa32,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqa32,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqa32,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqa64,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqa64,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqa64,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqu8,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqu8,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqu8,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqu16,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqu16,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqu16,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqu32,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqu32,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqu32,				zmm2zmm)
ZEN5_FUNCDEF(vmovdqu64,				xmm2xmm)
ZEN5_FUNCDEF(vmovdqu64,				ymm2ymm)
ZEN5_FUNCDEF(vmovdqu64,				zmm2zmm)

ZEN5_FUNCDEF(vmovaps,				xmm2kxmm)
ZEN5_FUNCDEF(vmovaps,				ymm2kymm)
ZEN5_FUNCDEF(vmovaps,				zmm2kzmm)
ZEN5_FUNCDEF(vmovapd,				xmm2kxmm)
ZEN5_FUNCDEF(vmovapd,				ymm2kymm)
ZEN5_FUNCDEF(vmovapd,				zmm2kzmm)
ZEN5_FUNCDEF(vmovups,				xmm2kxmm)
ZEN5_FUNCDEF(vmovups,				ymm2kymm)
ZEN5_FUNCDEF(vmovups,				zmm2kzmm)
ZEN5_FUNCDEF(vmovupd,				xmm2kxmm)
ZEN5_FUNCDEF(vmovupd,				ymm2kymm)
ZEN5_FUNCDEF(vmovupd,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqa32,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqa32,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqa32,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqa64,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqa64,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqa64,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqu8,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqu8,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqu8,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqu16,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqu16,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqu16,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqu32,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqu32,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqu32,				zmm2kzmm)
ZEN5_FUNCDEF(vmovdqu64,				xmm2kxmm)
ZEN5_FUNCDEF(vmovdqu64,				ymm2kymm)
ZEN5_FUNCDEF(vmovdqu64,				zmm2kzmm)

ZEN5_FUNCDEF(vmovaps,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovaps,				ymm2zkymm)
ZEN5_FUNCDEF(vmovaps,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovapd,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovapd,				ymm2zkymm)
ZEN5_FUNCDEF(vmovapd,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovups,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovups,				ymm2zkymm)
ZEN5_FUNCDEF(vmovups,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovupd,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovupd,				ymm2zkymm)
ZEN5_FUNCDEF(vmovupd,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqa32,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqa32,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqa32,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqa64,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqa64,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqa64,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqu8,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqu8,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqu8,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqu16,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqu16,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqu16,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqu32,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqu32,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqu32,				zmm2zkzmm)
ZEN5_FUNCDEF(vmovdqu64,				xmm2zkxmm)
ZEN5_FUNCDEF(vmovdqu64,				ymm2zkymm)
ZEN5_FUNCDEF(vmovdqu64,				zmm2zkzmm)

ZEN5_FUNCDEF(vpblendmb,				2xmm2xmm)
ZEN5_FUNCDEF(vpblendmb,				2ymm2ymm)
ZEN5_FUNCDEF(vpblendmb,				2zmm2zmm)
ZEN5_FUNCDEF(vpblendmw,				2xmm2xmm)
ZEN5_FUNCDEF(vpblendmw,				2ymm2ymm)
ZEN5_FUNCDEF(vpblendmw,				2zmm2zmm)
ZEN5_FUNCDEF(vpblendmd,				2xmm2xmm)
ZEN5_FUNCDEF(vpblendmd,				2ymm2ymm)
ZEN5_FUNCDEF(vpblendmd,				2zmm2zmm)
ZEN5_FUNCDEF(vpblendmq,				2xmm2xmm)
ZEN5_FUNCDEF(vpblendmq,				2ymm2ymm)
ZEN5_FUNCDEF(vpblendmq,				2zmm2zmm)

ZEN5_FUNCDEF(vpblendmb,				2xmm2kxmm)
ZEN5_FUNCDEF(vpblendmb,				2ymm2kymm)
ZEN5_FUNCDEF(vpblendmb,				2zmm2kzmm)
ZEN5_FUNCDEF(vpblendmw,				2xmm2kxmm)
ZEN5_FUNCDEF(vpblendmw,				2ymm2kymm)
ZEN5_FUNCDEF(vpblendmw,				2zmm2kzmm)
ZEN5_FUNCDEF(vpblendmd,				2xmm2kxmm)
ZEN5_FUNCDEF(vpblendmd,				2ymm2kymm)
ZEN5_FUNCDEF(vpblendmd,				2zmm2kzmm)
ZEN5_FUNCDEF(vpblendmq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpblendmq,				2ymm2kymm)
ZEN5_FUNCDEF(vpblendmq,				2zmm2kzmm)

ZEN5_FUNCDEF(vpblendmb,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpblendmb,				2ymm2zkymm)
ZEN5_FUNCDEF(vpblendmb,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpblendmw,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpblendmw,				2ymm2zkymm)
ZEN5_FUNCDEF(vpblendmw,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpblendmd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpblendmd,				2ymm2zkymm)
ZEN5_FUNCDEF(vpblendmd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpblendmq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpblendmq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpblendmq,				2zmm2zkzmm)

ZEN5_FUNCDEF(vpaddb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddb,				2zmm2zmm)
ZEN5_FUNCDEF(vpaddw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddw,				2zmm2zmm)
ZEN5_FUNCDEF(vpaddd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddd,				2zmm2zmm)
ZEN5_FUNCDEF(vpaddq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddq,				2zmm2zmm)

ZEN5_FUNCDEF(vpaddb,				2xmm2kxmm)
ZEN5_FUNCDEF(vpaddb,				2ymm2kymm)
ZEN5_FUNCDEF(vpaddb,				2zmm2kzmm)
ZEN5_FUNCDEF(vpaddw,				2xmm2kxmm)
ZEN5_FUNCDEF(vpaddw,				2ymm2kymm)
ZEN5_FUNCDEF(vpaddw,				2zmm2kzmm)
ZEN5_FUNCDEF(vpaddd,				2xmm2kxmm)
ZEN5_FUNCDEF(vpaddd,				2ymm2kymm)
ZEN5_FUNCDEF(vpaddd,				2zmm2kzmm)
ZEN5_FUNCDEF(vpaddq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpaddq,				2ymm2kymm)
ZEN5_FUNCDEF(vpaddq,				2zmm2kzmm)

ZEN5_FUNCDEF(vpaddb,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpaddb,				2ymm2zkymm)
ZEN5_FUNCDEF(vpaddb,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpaddw,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpaddw,				2ymm2zkymm)
ZEN5_FUNCDEF(vpaddw,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpaddd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpaddd,				2ymm2zkymm)
ZEN5_FUNCDEF(vpaddd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpaddq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpaddq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpaddq,				2zmm2zkzmm)

ZEN5_FUNCDEF(vpsubb,				2xmm2kxmm)
ZEN5_FUNCDEF(vpsubb,				2ymm2kymm)
ZEN5_FUNCDEF(vpsubb,				2zmm2kzmm)
ZEN5_FUNCDEF(vpsubw,				2xmm2kxmm)
ZEN5_FUNCDEF(vpsubw,				2ymm2kymm)
ZEN5_FUNCDEF(vpsubw,				2zmm2kzmm)
ZEN5_FUNCDEF(vpsubd,				2xmm2kxmm)
ZEN5_FUNCDEF(vpsubd,				2ymm2kymm)
ZEN5_FUNCDEF(vpsubd,				2zmm2kzmm)
ZEN5_FUNCDEF(vpsubq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpsubq,				2ymm2kymm)
ZEN5_FUNCDEF(vpsubq,				2zmm2kzmm)

ZEN5_FUNCDEF(vpsubb,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpsubb,				2ymm2zkymm)
ZEN5_FUNCDEF(vpsubb,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpsubw,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpsubw,				2ymm2zkymm)
ZEN5_FUNCDEF(vpsubw,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpsubd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpsubd,				2ymm2zkymm)
ZEN5_FUNCDEF(vpsubd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpsubq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpsubq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpsubq,				2zmm2zkzmm)

ZEN5_FUNCDEF(vpaddsb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddsb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddsb,				2zmm2zmm)
ZEN5_FUNCDEF(vpaddsw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddsw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddsw,				2zmm2zmm)

ZEN5_FUNCDEF(vpaddusb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddusb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddusb,				2zmm2zmm)
ZEN5_FUNCDEF(vpaddusw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpaddusw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpaddusw,				2zmm2zmm)

ZEN5_FUNCDEF(vpsubsb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsubsb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsubsb,				2zmm2zmm)
ZEN5_FUNCDEF(vpsubsw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsubsw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsubsw,				2zmm2zmm)

ZEN5_FUNCDEF(vpsubusb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsubusb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsubusb,				2zmm2zmm)
ZEN5_FUNCDEF(vpsubusw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsubusw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsubusw,				2zmm2zmm)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2xmm)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2ymm)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2zmm)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2xmm)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2ymm)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2zmm)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2kxmm)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2kymm)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2kzmm)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2kxmm)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2kymm)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2kzmm)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2zkxmm)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2zkymm)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2zkzmm)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2zkxmm)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2zkymm)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2zkzmm)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2xmmRot)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2ymmRot)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2zmmRot)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2xmmRot)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2ymmRot)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2zmmRot)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2kxmmRot)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2kymmRot)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2kzmmRot)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2kxmmRot)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2kymmRot)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2kzmmRot)

ZEN5_FUNCDEF(vpternlogd,			2xmmi2zkxmmRot)
ZEN5_FUNCDEF(vpternlogd,			2ymmi2zkymmRot)
ZEN5_FUNCDEF(vpternlogd,			2zmmi2zkzmmRot)
ZEN5_FUNCDEF(vpternlogq,			2xmmi2zkxmmRot)
ZEN5_FUNCDEF(vpternlogq,			2ymmi2zkymmRot)
ZEN5_FUNCDEF(vpternlogq,			2zmmi2zkzmmRot)

ZEN5_FUNCDEF(vmulss,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmulps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmulps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vmulps,				2zmm2zmm)
ZEN5_FUNCDEF(vmulsd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmulpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmulpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vmulpd,				2zmm2zmm)

ZEN5_FUNCDEF(vaddss,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaddps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaddps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vaddps,				2zmm2zmm)
ZEN5_FUNCDEF(vaddsd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaddpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaddpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vaddpd,				2zmm2zmm)

ZEN5_FUNCDEF(vsubss,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vsubps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vsubps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vsubps,				2zmm2zmm)
ZEN5_FUNCDEF(vsubsd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vsubpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vsubpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vsubpd,				2zmm2zmm)

ZEN5_FUNCDEF(vfmadd132ss,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd132ps,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd132ps,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd132ps,			2zmm2zmm)
ZEN5_FUNCDEF(vfmadd132sd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd132pd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd132pd,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd132pd,			2zmm2zmm)

ZEN5_FUNCDEF(vfmadd132ss,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd132ps,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd132ps,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd132ps,			2zmm2zmmRot)
ZEN5_FUNCDEF(vfmadd132sd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd132pd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd132pd,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd132pd,			2zmm2zmmRot)

ZEN5_FUNCDEF(vfmadd213ss,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd213ps,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd213ps,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd213ps,			2zmm2zmm)
ZEN5_FUNCDEF(vfmadd213sd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd213pd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd213pd,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd213pd,			2zmm2zmm)

ZEN5_FUNCDEF(vfmadd213ss,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd213ps,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd213ps,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd213ps,			2zmm2zmmRot)
ZEN5_FUNCDEF(vfmadd213sd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd213pd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd213pd,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd213pd,			2zmm2zmmRot)

ZEN5_FUNCDEF(vfmadd231ss,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd231ps,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd231ps,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd231ps,			2zmm2zmm)
ZEN5_FUNCDEF(vfmadd231sd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd231pd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vfmadd231pd,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vfmadd231pd,			2zmm2zmm)

ZEN5_FUNCDEF(vfmadd231ss,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd231ps,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd231ps,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd231ps,			2zmm2zmmRot)
ZEN5_FUNCDEF(vfmadd231sd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd231pd,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vfmadd231pd,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vfmadd231pd,			2zmm2zmmRot)

ZEN5_FUNCDEF(vdivss,				2xmm2xmm)
ZEN5_FUNCDEF(vdivps,				2xmm2xmm)
ZEN5_FUNCDEF(vdivps,				2ymm2ymm)
ZEN5_FUNCDEF(vdivps,				2zmm2zmm)
ZEN5_FUNCDEF(vdivsd,				2xmm2xmm)
ZEN5_FUNCDEF(vdivpd,				2xmm2xmm)
ZEN5_FUNCDEF(vdivpd,				2ymm2ymm)
ZEN5_FUNCDEF(vdivpd,				2zmm2zmm)

ZEN5_FUNCDEF(vsqrtss,				2xmm2xmm)
ZEN5_FUNCDEF(vsqrtps,				xmm2xmm)
ZEN5_FUNCDEF(vsqrtps,				ymm2ymm)
ZEN5_FUNCDEF(vsqrtps,				zmm2zmm)
ZEN5_FUNCDEF(vsqrtsd,				2xmm2xmm)
ZEN5_FUNCDEF(vsqrtpd,				xmm2xmm)
ZEN5_FUNCDEF(vsqrtpd,				ymm2ymm)
ZEN5_FUNCDEF(vsqrtpd,				zmm2zmm)

ZEN5_FUNCDEF(vrcp14ss,				2xmm2xmm)
ZEN5_FUNCDEF(vrcp14ps,				xmm2xmm)
ZEN5_FUNCDEF(vrcp14ps,				ymm2ymm)
ZEN5_FUNCDEF(vrcp14ps,				zmm2zmm)
ZEN5_FUNCDEF(vrcp14sd,				2xmm2xmm)
ZEN5_FUNCDEF(vrcp14pd,				xmm2xmm)
ZEN5_FUNCDEF(vrcp14pd,				ymm2ymm)
ZEN5_FUNCDEF(vrcp14pd,				zmm2zmm)

ZEN5_FUNCDEF(vrsqrt14ss,			2xmm2xmm)
ZEN5_FUNCDEF(vrsqrt14ps,			xmm2xmm)
ZEN5_FUNCDEF(vrsqrt14ps,			ymm2ymm)
ZEN5_FUNCDEF(vrsqrt14ps,			zmm2zmm)
ZEN5_FUNCDEF(vrsqrt14sd,			2xmm2xmm)
ZEN5_FUNCDEF(vrsqrt14pd,			xmm2xmm)
ZEN5_FUNCDEF(vrsqrt14pd,			ymm2ymm)
ZEN5_FUNCDEF(vrsqrt14pd,			zmm2zmm)

ZEN5_FUNCDEF(vminss,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vminps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vminps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vminps,				2zmm2zmm)
ZEN5_FUNCDEF(vminsd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vminpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vminpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vminpd,				2zmm2zmm)

ZEN5_FUNCDEF(vmaxss,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmaxps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmaxps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vmaxps,				2zmm2zmm)
ZEN5_FUNCDEF(vmaxsd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmaxpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmaxpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vmaxpd,				2zmm2zmm)

ZEN5_FUNCDEF(vgetexpss,				2xmm2xmm)
ZEN5_FUNCDEF(vgetexpps,				xmm2xmm)
ZEN5_FUNCDEF(vgetexpps,				ymm2ymm)
ZEN5_FUNCDEF(vgetexpps,				zmm2zmm)
ZEN5_FUNCDEF(vgetexpsd,				2xmm2xmm)
ZEN5_FUNCDEF(vgetexppd,				xmm2xmm)
ZEN5_FUNCDEF(vgetexppd,				ymm2ymm)
ZEN5_FUNCDEF(vgetexppd,				zmm2zmm)

ZEN5_FUNCDEF(vgetmantss,			2xmmi2xmm)
ZEN5_FUNCDEF(vgetmantps,			xmmi2xmm)
ZEN5_FUNCDEF(vgetmantps,			ymmi2ymm)
ZEN5_FUNCDEF(vgetmantps,			zmmi2zmm)
ZEN5_FUNCDEF(vgetmantsd,			2xmmi2xmm)
ZEN5_FUNCDEF(vgetmantpd,			xmmi2xmm)
ZEN5_FUNCDEF(vgetmantpd,			ymmi2ymm)
ZEN5_FUNCDEF(vgetmantpd,			zmmi2zmm)

ZEN5_FUNCDEF(vreducess,				2xmmi2xmm)
ZEN5_FUNCDEF(vreduceps,				xmmi2xmm)
ZEN5_FUNCDEF(vreduceps,				ymmi2ymm)
ZEN5_FUNCDEF(vreduceps,				zmmi2zmm)
ZEN5_FUNCDEF(vreducesd,				2xmmi2xmm)
ZEN5_FUNCDEF(vreducepd,				xmmi2xmm)
ZEN5_FUNCDEF(vreducepd,				ymmi2ymm)
ZEN5_FUNCDEF(vreducepd,				zmmi2zmm)

ZEN5_FUNCDEF(vrndscaless,			2xmmi2xmm)
ZEN5_FUNCDEF(vrndscaleps,			xmmi2xmm)
ZEN5_FUNCDEF(vrndscaleps,			ymmi2ymm)
ZEN5_FUNCDEF(vrndscaleps,			zmmi2zmm)
ZEN5_FUNCDEF(vrndscalesd,			2xmmi2xmm)
ZEN5_FUNCDEF(vrndscalepd,			xmmi2xmm)
ZEN5_FUNCDEF(vrndscalepd,			ymmi2ymm)
ZEN5_FUNCDEF(vrndscalepd,			zmmi2zmm)

ZEN5_FUNCDEF(vscalefss,				2xmm2xmm)
ZEN5_FUNCDEF(vscalefps,				2xmm2xmm)
ZEN5_FUNCDEF(vscalefps,				2ymm2ymm)
ZEN5_FUNCDEF(vscalefps,				2zmm2zmm)
ZEN5_FUNCDEF(vscalefsd,				2xmm2xmm)
ZEN5_FUNCDEF(vscalefpd,				2xmm2xmm)
ZEN5_FUNCDEF(vscalefpd,				2ymm2ymm)
ZEN5_FUNCDEF(vscalefpd,				2zmm2zmm)

ZEN5_FUNCDEF(vrangess,				2xmmi2xmm)
ZEN5_FUNCDEF(vrangeps,				2xmmi2xmm)
ZEN5_FUNCDEF(vrangeps,				2ymmi2ymm)
ZEN5_FUNCDEF(vrangeps,				2zmmi2zmm)
ZEN5_FUNCDEF(vrangesd,				2xmmi2xmm)
ZEN5_FUNCDEF(vrangepd,				2xmmi2xmm)
ZEN5_FUNCDEF(vrangepd,				2ymmi2ymm)
ZEN5_FUNCDEF(vrangepd,				2zmmi2zmm)

ZEN5_FUNCDEF(vfixupimmss,			2xmmi2xmm)
ZEN5_FUNCDEF(vfixupimmps,			2xmmi2xmm)
ZEN5_FUNCDEF(vfixupimmps,			2ymmi2ymm)
ZEN5_FUNCDEF(vfixupimmps,			2zmmi2zmm)
ZEN5_FUNCDEF(vfixupimmsd,			2xmmi2xmm)
ZEN5_FUNCDEF(vfixupimmpd,			2xmmi2xmm)
ZEN5_FUNCDEF(vfixupimmpd,			2ymmi2ymm)
ZEN5_FUNCDEF(vfixupimmpd,			2zmmi2zmm)

ZEN5_FUNCDEF(vpminuq,				2xmm2xmm)
ZEN5_FUNCDEF(vpminuq,				2ymm2ymm)
ZEN5_FUNCDEF(vpminuq,				2zmm2zmm)
ZEN5_FUNCDEF(vpminsq,				2xmm2xmm)
ZEN5_FUNCDEF(vpminsq,				2ymm2ymm)
ZEN5_FUNCDEF(vpminsq,				2zmm2zmm)

ZEN5_FUNCDEF(vpmaxuq,				2xmm2xmm)
ZEN5_FUNCDEF(vpmaxuq,				2ymm2ymm)
ZEN5_FUNCDEF(vpmaxuq,				2zmm2zmm)
ZEN5_FUNCDEF(vpmaxsq,				2xmm2xmm)
ZEN5_FUNCDEF(vpmaxsq,				2ymm2ymm)
ZEN5_FUNCDEF(vpmaxsq,				2zmm2zmm)

ZEN5_FUNCDEF(vpabsq,				xmm2xmm)
ZEN5_FUNCDEF(vpabsq,				ymm2ymm)
ZEN5_FUNCDEF(vpabsq,				zmm2zmm)

ZEN5_FUNCDEF(vpopcntb,				xmm2xmm)
ZEN5_FUNCDEF(vpopcntb,				ymm2ymm)
ZEN5_FUNCDEF(vpopcntb,				zmm2zmm)

ZEN5_FUNCDEF(vpopcntw,				xmm2xmm)
ZEN5_FUNCDEF(vpopcntw,				ymm2ymm)
ZEN5_FUNCDEF(vpopcntw,				zmm2zmm)

ZEN5_FUNCDEF(vpopcntd,				xmm2xmm)
ZEN5_FUNCDEF(vpopcntd,				ymm2ymm)
ZEN5_FUNCDEF(vpopcntd,				zmm2zmm)

ZEN5_FUNCDEF(vpopcntq,				xmm2xmm)
ZEN5_FUNCDEF(vpopcntq,				ymm2ymm)
ZEN5_FUNCDEF(vpopcntq,				zmm2zmm)

ZEN5_FUNCDEF(vplzcntd,				xmm2xmm)
ZEN5_FUNCDEF(vplzcntd,				ymm2ymm)
ZEN5_FUNCDEF(vplzcntd,				zmm2zmm)

ZEN5_FUNCDEF(vplzcntq,				xmm2xmm)
ZEN5_FUNCDEF(vplzcntq,				ymm2ymm)
ZEN5_FUNCDEF(vplzcntq,				zmm2zmm)

ZEN5_FUNCDEF(vpmultishiftqb,		2xmm2xmm)
ZEN5_FUNCDEF(vpmultishiftqb,		2ymm2ymm)
ZEN5_FUNCDEF(vpmultishiftqb,		2zmm2zmm)

ZEN5_FUNCDEF(vgf2p8affineqb,		2xmmi2xmm)
ZEN5_FUNCDEF(vgf2p8affineqb,		2ymmi2ymm)
ZEN5_FUNCDEF(vgf2p8affineqb,		evex_2xmmi2xmm)
ZEN5_FUNCDEF(vgf2p8affineqb,		evex_2ymmi2ymm)
ZEN5_FUNCDEF(vgf2p8affineqb,		2zmmi2zmm)

ZEN5_FUNCDEF(vgf2p8affineinvqb,		2xmmi2xmm)
ZEN5_FUNCDEF(vgf2p8affineinvqb,		2ymmi2ymm)
ZEN5_FUNCDEF(vgf2p8affineinvqb,		evex_2xmmi2xmm)
ZEN5_FUNCDEF(vgf2p8affineinvqb,		evex_2ymmi2ymm)
ZEN5_FUNCDEF(vgf2p8affineinvqb,		2zmmi2zmm)

ZEN5_FUNCDEF(vgf2p8mulb,			2xmm2xmm)
ZEN5_FUNCDEF(vgf2p8mulb,			2ymm2ymm)
ZEN5_FUNCDEF(vgf2p8mulb,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vgf2p8mulb,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vgf2p8mulb,			2zmm2zmm)

ZEN5_FUNCDEF(vpmulhw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmulhw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmulhw,				2zmm2zmm)

ZEN5_FUNCDEF(vpmulhuw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmulhuw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmulhuw,				2zmm2zmm)

ZEN5_FUNCDEF(vpmulhrsw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmulhrsw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmulhrsw,				2zmm2zmm)

ZEN5_FUNCDEF(vpmullw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmullw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmullw,				2zmm2zmm)

ZEN5_FUNCDEF(vpmulld,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmulld,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmulld,				2zmm2zmm)

ZEN5_FUNCDEF(vpmuldq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmuldq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmuldq,				2zmm2zmm)

ZEN5_FUNCDEF(vpmuludq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmuludq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmuludq,				2zmm2zmm)

ZEN5_FUNCDEF(vpmaddwd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmaddwd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmaddwd,				2zmm2zmm)

ZEN5_FUNCDEF(vpmaddubsw,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmaddubsw,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmaddubsw,			2zmm2zmm)

ZEN5_FUNCDEF(vpmadd52huq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmadd52huq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmadd52huq,			2zmm2zmm)

ZEN5_FUNCDEF(vpmadd52luq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpmadd52luq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpmadd52luq,			2zmm2zmm)

ZEN5_FUNCDEF(vpmadd52huq,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpmadd52huq,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpmadd52huq,			2zmm2zmmRot)

ZEN5_FUNCDEF(vpmadd52luq,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpmadd52luq,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpmadd52luq,			2zmm2zmmRot)

ZEN5_FUNCDEF(vpdpbusd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpdpbusd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpdpbusd,				2zmm2zmm)

ZEN5_FUNCDEF(vpdpbusds,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpdpbusds,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpdpbusds,				2zmm2zmm)

ZEN5_FUNCDEF(vpdpwssd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpdpwssd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpdpwssd,				2zmm2zmm)

ZEN5_FUNCDEF(vpdpwssds,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpdpwssds,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpdpwssds,				2zmm2zmm)

ZEN5_FUNCDEF(vpdpbusd,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpdpbusd,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpdpbusd,				2zmm2zmmRot)

ZEN5_FUNCDEF(vpdpbusds,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpdpbusds,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpdpbusds,				2zmm2zmmRot)

ZEN5_FUNCDEF(vpdpwssd,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpdpwssd,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpdpwssd,				2zmm2zmmRot)

ZEN5_FUNCDEF(vpdpwssds,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vpdpwssds,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vpdpwssds,				2zmm2zmmRot)

ZEN5_FUNCDEF(vpsadbw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsadbw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsadbw,				2zmm2zmm)

ZEN5_FUNCDEF(vdbpsadbw,				2xmmi2xmm)
ZEN5_FUNCDEF(vdbpsadbw,				2ymmi2ymm)
ZEN5_FUNCDEF(vdbpsadbw,				2zmmi2zmm)

ZEN5_FUNCDEF(vpsllw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsllw,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsllw,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsrlw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrlw,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsrlw,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsraw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsraw,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsraw,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpslld,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpslld,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpslld,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsrld,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrld,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsrld,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsrad,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrad,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsrad,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsllq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsllq,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsllq,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsrlq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrlq,				evex_xmmymm2ymm)
ZEN5_FUNCDEF(vpsrlq,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsraq,				2xmm2xmm)
ZEN5_FUNCDEF(vpsraq,				xmmymm2ymm)
ZEN5_FUNCDEF(vpsraq,				xmmzmm2zmm)

ZEN5_FUNCDEF(vpsllvw,				2xmm2xmm)
ZEN5_FUNCDEF(vpsllvw,				2ymm2ymm)
ZEN5_FUNCDEF(vpsllvw,				2zmm2zmm)

ZEN5_FUNCDEF(vpsrlvw,				2xmm2xmm)
ZEN5_FUNCDEF(vpsrlvw,				2ymm2ymm)
ZEN5_FUNCDEF(vpsrlvw,				2zmm2zmm)

ZEN5_FUNCDEF(vpsravw,				2xmm2xmm)
ZEN5_FUNCDEF(vpsravw,				2ymm2ymm)
ZEN5_FUNCDEF(vpsravw,				2zmm2zmm)

ZEN5_FUNCDEF(vpsllvd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsllvd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsllvd,				2zmm2zmm)

ZEN5_FUNCDEF(vpsrlvd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrlvd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsrlvd,				2zmm2zmm)

ZEN5_FUNCDEF(vpsravd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsravd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsravd,				2zmm2zmm)

ZEN5_FUNCDEF(vpsllvq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsllvq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsllvq,				2zmm2zmm)

ZEN5_FUNCDEF(vpsrlvq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpsrlvq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpsrlvq,				2zmm2zmm)

ZEN5_FUNCDEF(vpsravq,				2xmm2xmm)
ZEN5_FUNCDEF(vpsravq,				2ymm2ymm)
ZEN5_FUNCDEF(vpsravq,				2zmm2zmm)

ZEN5_FUNCDEF(vpsllw,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsllw,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsllw,				zmmi2zmm)

ZEN5_FUNCDEF(vpsrlw,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsrlw,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsrlw,				zmmi2zmm)

ZEN5_FUNCDEF(vpsraw,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsraw,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsraw,				zmmi2zmm)

ZEN5_FUNCDEF(vpslld,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpslld,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpslld,				zmmi2zmm)

ZEN5_FUNCDEF(vpsrld,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsrld,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsrld,				zmmi2zmm)

ZEN5_FUNCDEF(vpsrad,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsrad,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsrad,				zmmi2zmm)

ZEN5_FUNCDEF(vpsllq,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsllq,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsllq,				zmmi2zmm)

ZEN5_FUNCDEF(vpsrlq,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsrlq,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsrlq,				zmmi2zmm)

ZEN5_FUNCDEF(vpsraq,				xmmi2xmm)
ZEN5_FUNCDEF(vpsraq,				ymmi2ymm)
ZEN5_FUNCDEF(vpsraq,				zmmi2zmm)

ZEN5_FUNCDEF(vpshldvw,				2xmm2xmm)
ZEN5_FUNCDEF(vpshldvw,				2ymm2ymm)
ZEN5_FUNCDEF(vpshldvw,				2zmm2zmm)

ZEN5_FUNCDEF(vpshrdvw,				2xmm2xmm)
ZEN5_FUNCDEF(vpshrdvw,				2ymm2ymm)
ZEN5_FUNCDEF(vpshrdvw,				2zmm2zmm)

ZEN5_FUNCDEF(vpshldvd,				2xmm2xmm)
ZEN5_FUNCDEF(vpshldvd,				2ymm2ymm)
ZEN5_FUNCDEF(vpshldvd,				2zmm2zmm)

ZEN5_FUNCDEF(vpshrdvd,				2xmm2xmm)
ZEN5_FUNCDEF(vpshrdvd,				2ymm2ymm)
ZEN5_FUNCDEF(vpshrdvd,				2zmm2zmm)

ZEN5_FUNCDEF(vpshldvq,				2xmm2xmm)
ZEN5_FUNCDEF(vpshldvq,				2ymm2ymm)
ZEN5_FUNCDEF(vpshldvq,				2zmm2zmm)

ZEN5_FUNCDEF(vpshrdvq,				2xmm2xmm)
ZEN5_FUNCDEF(vpshrdvq,				2ymm2ymm)
ZEN5_FUNCDEF(vpshrdvq,				2zmm2zmm)

ZEN5_FUNCDEF(vpshldw,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshldw,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshldw,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshrdw,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshrdw,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshrdw,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshldd,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshldd,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshldd,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshrdd,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshrdd,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshrdd,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshldq,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshldq,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshldq,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshrdq,				2xmmi2xmm)
ZEN5_FUNCDEF(vpshrdq,				2ymmi2ymm)
ZEN5_FUNCDEF(vpshrdq,				2zmmi2zmm)

ZEN5_FUNCDEF(vprolvd,				2xmm2xmm)
ZEN5_FUNCDEF(vprolvd,				2ymm2ymm)
ZEN5_FUNCDEF(vprolvd,				2zmm2zmm)

ZEN5_FUNCDEF(vprorvd,				2xmm2xmm)
ZEN5_FUNCDEF(vprorvd,				2ymm2ymm)
ZEN5_FUNCDEF(vprorvd,				2zmm2zmm)

ZEN5_FUNCDEF(vprolvq,				2xmm2xmm)
ZEN5_FUNCDEF(vprolvq,				2ymm2ymm)
ZEN5_FUNCDEF(vprolvq,				2zmm2zmm)

ZEN5_FUNCDEF(vprorvq,				2xmm2xmm)
ZEN5_FUNCDEF(vprorvq,				2ymm2ymm)
ZEN5_FUNCDEF(vprorvq,				2zmm2zmm)

ZEN5_FUNCDEF(vprold,				xmmi2xmm)
ZEN5_FUNCDEF(vprold,				ymmi2ymm)
ZEN5_FUNCDEF(vprold,				zmmi2zmm)

ZEN5_FUNCDEF(vprord,				xmmi2xmm)
ZEN5_FUNCDEF(vprord,				ymmi2ymm)
ZEN5_FUNCDEF(vprord,				zmmi2zmm)

ZEN5_FUNCDEF(vprolq,				xmmi2xmm)
ZEN5_FUNCDEF(vprolq,				ymmi2ymm)
ZEN5_FUNCDEF(vprolq,				zmmi2zmm)

ZEN5_FUNCDEF(vprorq,				xmmi2xmm)
ZEN5_FUNCDEF(vprorq,				ymmi2ymm)
ZEN5_FUNCDEF(vprorq,				zmmi2zmm)

ZEN5_FUNCDEF(vaesenc,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaesenc,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vaesenc,				2zmm2zmm)

ZEN5_FUNCDEF(vaesenclast,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vaesenclast,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vaesenclast,			2zmm2zmm)

ZEN5_FUNCDEF(vaesdec,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vaesdec,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vaesdec,				2zmm2zmm)

ZEN5_FUNCDEF(vaesdeclast,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vaesdeclast,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vaesdeclast,			2zmm2zmm)

ZEN5_FUNCDEF(vaesenc,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vaesenc,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vaesenc,				2zmm2zmmRot)

ZEN5_FUNCDEF(vaesenclast,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vaesenclast,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vaesenclast,			2zmm2zmmRot)

ZEN5_FUNCDEF(vaesdec,				evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vaesdec,				evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vaesdec,				2zmm2zmmRot)

ZEN5_FUNCDEF(vaesdeclast,			evex_2xmm2xmmRot)
ZEN5_FUNCDEF(vaesdeclast,			evex_2ymm2ymmRot)
ZEN5_FUNCDEF(vaesdeclast,			2zmm2zmmRot)

ZEN5_FUNCDEF(vpclmulqdq,			evex_2xmmi2xmm)
ZEN5_FUNCDEF(vpclmulqdq,			evex_2ymmi2ymm)
ZEN5_FUNCDEF(vpclmulqdq,			2zmmi2zmm)

ZEN5_FUNCDEF(vpacksswb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpacksswb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpacksswb,				2zmm2zmm)

ZEN5_FUNCDEF(vpackuswb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpackuswb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpackuswb,				2zmm2zmm)

ZEN5_FUNCDEF(vpackssdw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpackssdw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpackssdw,				2zmm2zmm)

ZEN5_FUNCDEF(vpackusdw,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpackusdw,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpackusdw,				2zmm2zmm)

ZEN5_FUNCDEF(vpslldq,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpslldq,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpslldq,				zmmi2zmm)

ZEN5_FUNCDEF(vpsrldq,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpsrldq,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpsrldq,				zmmi2zmm)

ZEN5_FUNCDEF(vpshufb,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpshufb,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpshufb,				2zmm2zmm)

ZEN5_FUNCDEF(vpalignr,				evex_2xmmi2xmm)
ZEN5_FUNCDEF(vpalignr,				evex_2ymmi2ymm)
ZEN5_FUNCDEF(vpalignr,				2zmmi2zmm)

ZEN5_FUNCDEF(vmovddup,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovddup,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovddup,				zmm2zmm)

ZEN5_FUNCDEF(vpermilpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpermilpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermilpd,				2zmm2zmm)

ZEN5_FUNCDEF(vpermilps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpermilps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermilps,				2zmm2zmm)

ZEN5_FUNCDEF(vpmovzxbw,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxbw,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxbw,				ymm2zmm)
ZEN5_FUNCDEF(vpmovzxbd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxbd,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxbd,				xmm2zmm)
ZEN5_FUNCDEF(vpmovzxbq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxbq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxbq,				xmm2zmm)
ZEN5_FUNCDEF(vpmovzxwd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxwd,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxwd,				ymm2zmm)
ZEN5_FUNCDEF(vpmovzxwq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxwq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxwq,				xmm2zmm)
ZEN5_FUNCDEF(vpmovzxdq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovzxdq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovzxdq,				ymm2zmm)

ZEN5_FUNCDEF(vpmovsxbw,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxbw,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxbw,				ymm2zmm)
ZEN5_FUNCDEF(vpmovsxbd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxbd,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxbd,				xmm2zmm)
ZEN5_FUNCDEF(vpmovsxbq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxbq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxbq,				xmm2zmm)
ZEN5_FUNCDEF(vpmovsxwd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxwd,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxwd,				ymm2zmm)
ZEN5_FUNCDEF(vpmovsxwq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxwq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxwq,				xmm2zmm)
ZEN5_FUNCDEF(vpmovsxdq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vpmovsxdq,				evex_xmm2ymm)
ZEN5_FUNCDEF(vpmovsxdq,				ymm2zmm)

ZEN5_FUNCDEF(vpmovwb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovwb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovwb,				zmm2ymm)
ZEN5_FUNCDEF(vpmovdb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovdb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovdb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovdw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovdw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovdw,				zmm2ymm)
ZEN5_FUNCDEF(vpmovqb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovqb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovqb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovqw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovqw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovqw,				zmm2xmm)
ZEN5_FUNCDEF(vpmovqd,				xmm2xmm)
ZEN5_FUNCDEF(vpmovqd,				ymm2xmm)
ZEN5_FUNCDEF(vpmovqd,				zmm2ymm)

ZEN5_FUNCDEF(vpmovswb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovswb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovswb,				zmm2ymm)
ZEN5_FUNCDEF(vpmovsdb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovsdb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovsdb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovsdw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovsdw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovsdw,				zmm2ymm)
ZEN5_FUNCDEF(vpmovsqb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovsqb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovsqb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovsqw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovsqw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovsqw,				zmm2xmm)
ZEN5_FUNCDEF(vpmovsqd,				xmm2xmm)
ZEN5_FUNCDEF(vpmovsqd,				ymm2xmm)
ZEN5_FUNCDEF(vpmovsqd,				zmm2ymm)

ZEN5_FUNCDEF(vpmovuswb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovuswb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovuswb,				zmm2ymm)
ZEN5_FUNCDEF(vpmovusdb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovusdb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovusdb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovusdw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovusdw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovusdw,				zmm2ymm)
ZEN5_FUNCDEF(vpmovusqb,				xmm2xmm)
ZEN5_FUNCDEF(vpmovusqb,				ymm2xmm)
ZEN5_FUNCDEF(vpmovusqb,				zmm2xmm)
ZEN5_FUNCDEF(vpmovusqw,				xmm2xmm)
ZEN5_FUNCDEF(vpmovusqw,				ymm2xmm)
ZEN5_FUNCDEF(vpmovusqw,				zmm2xmm)
ZEN5_FUNCDEF(vpmovusqd,				xmm2xmm)
ZEN5_FUNCDEF(vpmovusqd,				ymm2xmm)
ZEN5_FUNCDEF(vpmovusqd,				zmm2ymm)

ZEN5_FUNCDEF(vbroadcastss,			evex_xmm2xmm)
ZEN5_FUNCDEF(vbroadcastss,			evex_xmm2ymm)
ZEN5_FUNCDEF(vbroadcastss,			xmm2zmm)

;ZEN5_FUNCDEF(vbroadcastsd,			evex_xmm2xmm)
ZEN5_FUNCDEF(vbroadcastsd,			evex_xmm2ymm)
ZEN5_FUNCDEF(vbroadcastsd,			xmm2zmm)

ZEN5_FUNCDEF(vpbroadcastb,			evex_xmm2xmm)
ZEN5_FUNCDEF(vpbroadcastb,			evex_xmm2ymm)
ZEN5_FUNCDEF(vpbroadcastb,			xmm2zmm)

ZEN5_FUNCDEF(vpbroadcastw,			evex_xmm2xmm)
ZEN5_FUNCDEF(vpbroadcastw,			evex_xmm2ymm)
ZEN5_FUNCDEF(vpbroadcastw,			xmm2zmm)

ZEN5_FUNCDEF(vpbroadcastd,			evex_xmm2xmm)
ZEN5_FUNCDEF(vpbroadcastd,			evex_xmm2ymm)
ZEN5_FUNCDEF(vpbroadcastd,			xmm2zmm)

ZEN5_FUNCDEF(vpbroadcastq,			evex_xmm2xmm)
ZEN5_FUNCDEF(vpbroadcastq,			evex_xmm2ymm)
ZEN5_FUNCDEF(vpbroadcastq,			xmm2zmm)

ZEN5_FUNCDEF(valignd,				2xmmi2xmm)
ZEN5_FUNCDEF(valignd,				2ymmi2ymm)
ZEN5_FUNCDEF(valignd,				2zmmi2zmm)
ZEN5_FUNCDEF(valignq,				2xmmi2xmm)
ZEN5_FUNCDEF(valignq,				2ymmi2ymm)
ZEN5_FUNCDEF(valignq,				2zmmi2zmm)

ZEN5_FUNCDEF(vpermb,				2xmm2xmm)
ZEN5_FUNCDEF(vpermb,				2ymm2ymm)
ZEN5_FUNCDEF(vpermb,				2zmm2zmm)
ZEN5_FUNCDEF(vpermw,				2xmm2xmm)
ZEN5_FUNCDEF(vpermw,				2ymm2ymm)
ZEN5_FUNCDEF(vpermw,				2zmm2zmm)
;ZEN5_FUNCDEF(vpermd,				2xmm2xmm)
ZEN5_FUNCDEF(vpermd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermd,				2zmm2zmm)
;ZEN5_FUNCDEF(vpermq,				2xmm2xmm)
ZEN5_FUNCDEF(vpermq,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpermq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermq,				zmmi2zmm)
ZEN5_FUNCDEF(vpermq,				2zmm2zmm)
;ZEN5_FUNCDEF(vpermps,				2xmm2xmm)
ZEN5_FUNCDEF(vpermps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermps,				2zmm2zmm)
;ZEN5_FUNCDEF(vpermpd,				2xmm2xmm)
ZEN5_FUNCDEF(vpermpd,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpermpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpermpd,				zmmi2zmm)
ZEN5_FUNCDEF(vpermpd,				2zmm2zmm)

ZEN5_FUNCDEF(vpermi2b,				2xmm2xmm)
ZEN5_FUNCDEF(vpermi2b,				2ymm2ymm)
ZEN5_FUNCDEF(vpermi2b,				2zmm2zmm)
ZEN5_FUNCDEF(vpermt2b,				2xmm2xmm)
ZEN5_FUNCDEF(vpermt2b,				2ymm2ymm)
ZEN5_FUNCDEF(vpermt2b,				2zmm2zmm)
ZEN5_FUNCDEF(vpermi2w,				2xmm2xmm)
ZEN5_FUNCDEF(vpermi2w,				2ymm2ymm)
ZEN5_FUNCDEF(vpermi2w,				2zmm2zmm)
ZEN5_FUNCDEF(vpermt2w,				2xmm2xmm)
ZEN5_FUNCDEF(vpermt2w,				2ymm2ymm)
ZEN5_FUNCDEF(vpermt2w,				2zmm2zmm)
ZEN5_FUNCDEF(vpermi2d,				2xmm2xmm)
ZEN5_FUNCDEF(vpermi2d,				2ymm2ymm)
ZEN5_FUNCDEF(vpermi2d,				2zmm2zmm)
ZEN5_FUNCDEF(vpermt2d,				2xmm2xmm)
ZEN5_FUNCDEF(vpermt2d,				2ymm2ymm)
ZEN5_FUNCDEF(vpermt2d,				2zmm2zmm)
ZEN5_FUNCDEF(vpermi2q,				2xmm2xmm)
ZEN5_FUNCDEF(vpermi2q,				2ymm2ymm)
ZEN5_FUNCDEF(vpermi2q,				2zmm2zmm)
ZEN5_FUNCDEF(vpermt2q,				2xmm2xmm)
ZEN5_FUNCDEF(vpermt2q,				2ymm2ymm)
ZEN5_FUNCDEF(vpermt2q,				2zmm2zmm)

ZEN5_FUNCDEF(vinsertf32x4,			xmmymmi02ymm)
ZEN5_FUNCDEF(vinsertf32x4,			xmmzmmi02zmm)
ZEN5_FUNCDEF(vinserti32x4,			xmmymmi02ymm)
ZEN5_FUNCDEF(vinserti32x4,			xmmzmmi02zmm)
ZEN5_FUNCDEF(vinsertf64x2,			xmmymmi02ymm)
ZEN5_FUNCDEF(vinsertf64x2,			xmmzmmi02zmm)
ZEN5_FUNCDEF(vinserti64x2,			xmmymmi02ymm)
ZEN5_FUNCDEF(vinserti64x2,			xmmzmmi02zmm)
ZEN5_FUNCDEF(vinsertf32x8,			ymmzmmi02zmm)
ZEN5_FUNCDEF(vinserti32x8,			ymmzmmi02zmm)
ZEN5_FUNCDEF(vinsertf64x4,			ymmzmmi02zmm)
ZEN5_FUNCDEF(vinserti64x4,			ymmzmmi02zmm)

ZEN5_FUNCDEF(vinsertf32x4,			xmmymmi2ymm)
ZEN5_FUNCDEF(vinsertf32x4,			xmmzmmi2zmm)
ZEN5_FUNCDEF(vinserti32x4,			xmmymmi2ymm)
ZEN5_FUNCDEF(vinserti32x4,			xmmzmmi2zmm)
ZEN5_FUNCDEF(vinsertf64x2,			xmmymmi2ymm)
ZEN5_FUNCDEF(vinsertf64x2,			xmmzmmi2zmm)
ZEN5_FUNCDEF(vinserti64x2,			xmmymmi2ymm)
ZEN5_FUNCDEF(vinserti64x2,			xmmzmmi2zmm)
ZEN5_FUNCDEF(vinsertf32x8,			ymmzmmi2zmm)
ZEN5_FUNCDEF(vinserti32x8,			ymmzmmi2zmm)
ZEN5_FUNCDEF(vinsertf64x4,			ymmzmmi2zmm)
ZEN5_FUNCDEF(vinserti64x4,			ymmzmmi2zmm)

ZEN5_FUNCDEF(vextractf32x4,			ymmi02xmm)
ZEN5_FUNCDEF(vextractf32x4,			zmmi02xmm)
ZEN5_FUNCDEF(vextracti32x4,			ymmi02xmm)
ZEN5_FUNCDEF(vextracti32x4,			zmmi02xmm)
ZEN5_FUNCDEF(vextractf64x2,			ymmi02xmm)
ZEN5_FUNCDEF(vextractf64x2,			zmmi02xmm)
ZEN5_FUNCDEF(vextracti64x2,			ymmi02xmm)
ZEN5_FUNCDEF(vextracti64x2,			zmmi02xmm)
ZEN5_FUNCDEF(vextractf32x8,			zmmi02ymm)
ZEN5_FUNCDEF(vextracti32x8,			zmmi02ymm)
ZEN5_FUNCDEF(vextractf64x4,			zmmi02ymm)
ZEN5_FUNCDEF(vextracti64x4,			zmmi02ymm)

ZEN5_FUNCDEF(vextractf32x4,			ymmi2xmm)
ZEN5_FUNCDEF(vextractf32x4,			zmmi2xmm)
ZEN5_FUNCDEF(vextracti32x4,			ymmi2xmm)
ZEN5_FUNCDEF(vextracti32x4,			zmmi2xmm)
ZEN5_FUNCDEF(vextractf64x2,			ymmi2xmm)
ZEN5_FUNCDEF(vextractf64x2,			zmmi2xmm)
ZEN5_FUNCDEF(vextracti64x2,			ymmi2xmm)
ZEN5_FUNCDEF(vextracti64x2,			zmmi2xmm)
ZEN5_FUNCDEF(vextractf32x8,			zmmi2ymm)
ZEN5_FUNCDEF(vextracti32x8,			zmmi2ymm)
ZEN5_FUNCDEF(vextractf64x4,			zmmi2ymm)
ZEN5_FUNCDEF(vextracti64x4,			zmmi2ymm)

ZEN5_FUNCDEF(vshufi32x4,			2ymmi2ymm)
ZEN5_FUNCDEF(vshuff32x4,			2ymmi2ymm)
ZEN5_FUNCDEF(vshufi64x2,			2zmmi2zmm)
ZEN5_FUNCDEF(vshuff64x2,			2zmmi2zmm)

ZEN5_FUNCDEF(vpshufbitqmb,			2xmm2k)
ZEN5_FUNCDEF(vpshufbitqmb,			2ymm2k)
ZEN5_FUNCDEF(vpshufbitqmb,			2zmm2k)

ZEN5_FUNCDEF(vptestmb,				2xmm2k)
ZEN5_FUNCDEF(vptestmb,				2ymm2k)
ZEN5_FUNCDEF(vptestmb,				2zmm2k)
ZEN5_FUNCDEF(vptestmw,				2xmm2k)
ZEN5_FUNCDEF(vptestmw,				2ymm2k)
ZEN5_FUNCDEF(vptestmw,				2zmm2k)
ZEN5_FUNCDEF(vptestmd,				2xmm2k)
ZEN5_FUNCDEF(vptestmd,				2ymm2k)
ZEN5_FUNCDEF(vptestmd,				2zmm2k)
ZEN5_FUNCDEF(vptestmq,				2xmm2k)
ZEN5_FUNCDEF(vptestmq,				2ymm2k)
ZEN5_FUNCDEF(vptestmq,				2zmm2k)

ZEN5_FUNCDEF(vptestnmb,				2xmm2k)
ZEN5_FUNCDEF(vptestnmb,				2ymm2k)
ZEN5_FUNCDEF(vptestnmb,				2zmm2k)
ZEN5_FUNCDEF(vptestnmw,				2xmm2k)
ZEN5_FUNCDEF(vptestnmw,				2ymm2k)
ZEN5_FUNCDEF(vptestnmw,				2zmm2k)
ZEN5_FUNCDEF(vptestnmd,				2xmm2k)
ZEN5_FUNCDEF(vptestnmd,				2ymm2k)
ZEN5_FUNCDEF(vptestnmd,				2zmm2k)
ZEN5_FUNCDEF(vptestnmq,				2xmm2k)
ZEN5_FUNCDEF(vptestnmq,				2ymm2k)
ZEN5_FUNCDEF(vptestnmq,				2zmm2k)

ZEN5_FUNCDEF(vpcmpeqb,				2xmm2k)
ZEN5_FUNCDEF(vpcmpeqb,				2ymm2k)
ZEN5_FUNCDEF(vpcmpeqb,				2zmm2k)
ZEN5_FUNCDEF(vpcmpeqw,				2xmm2k)
ZEN5_FUNCDEF(vpcmpeqw,				2ymm2k)
ZEN5_FUNCDEF(vpcmpeqw,				2zmm2k)
ZEN5_FUNCDEF(vpcmpeqd,				2xmm2k)
ZEN5_FUNCDEF(vpcmpeqd,				2ymm2k)
ZEN5_FUNCDEF(vpcmpeqd,				2zmm2k)
ZEN5_FUNCDEF(vpcmpeqq,				2xmm2k)
ZEN5_FUNCDEF(vpcmpeqq,				2ymm2k)
ZEN5_FUNCDEF(vpcmpeqq,				2zmm2k)

ZEN5_FUNCDEF(vpcmpgtb,				2xmm2k)
ZEN5_FUNCDEF(vpcmpgtb,				2ymm2k)
ZEN5_FUNCDEF(vpcmpgtb,				2zmm2k)
ZEN5_FUNCDEF(vpcmpgtw,				2xmm2k)
ZEN5_FUNCDEF(vpcmpgtw,				2ymm2k)
ZEN5_FUNCDEF(vpcmpgtw,				2zmm2k)
ZEN5_FUNCDEF(vpcmpgtd,				2xmm2k)
ZEN5_FUNCDEF(vpcmpgtd,				2ymm2k)
ZEN5_FUNCDEF(vpcmpgtd,				2zmm2k)
ZEN5_FUNCDEF(vpcmpgtq,				2xmm2k)
ZEN5_FUNCDEF(vpcmpgtq,				2ymm2k)
ZEN5_FUNCDEF(vpcmpgtq,				2zmm2k)

ZEN5_FUNCDEF(vpcmpgtb,				2xmm2kRot)
ZEN5_FUNCDEF(vpcmpgtb,				2ymm2kRot)
ZEN5_FUNCDEF(vpcmpgtb,				2zmm2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2xmm2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2ymm2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2zmm2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2xmm2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2ymm2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2zmm2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2xmm2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2ymm2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2zmm2kRot)

ZEN5_FUNCDEF(vpcmpb,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpb,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpb,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpw,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpw,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpw,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpd,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpd,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpd,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpq,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpq,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpq,				2zmmi2k)

ZEN5_FUNCDEF(vpcmpub,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpub,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpub,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpuw,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpuw,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpuw,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpud,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpud,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpud,				2zmmi2k)
ZEN5_FUNCDEF(vpcmpuq,				2xmmi2k)
ZEN5_FUNCDEF(vpcmpuq,				2ymmi2k)
ZEN5_FUNCDEF(vpcmpuq,				2zmmi2k)

ZEN5_FUNCDEF(vp2intersectd,			2xmm2k)
ZEN5_FUNCDEF(vp2intersectd,			2ymm2k)
ZEN5_FUNCDEF(vp2intersectd,			2zmm2k)
ZEN5_FUNCDEF(vp2intersectq,			2xmm2k)
ZEN5_FUNCDEF(vp2intersectq,			2ymm2k)
ZEN5_FUNCDEF(vp2intersectq,			2zmm2k)

ZEN5_FUNCDEF(vcmpss,				2xmmi2k)
ZEN5_FUNCDEF(vcmpps,				2xmmi2k)
ZEN5_FUNCDEF(vcmpps,				2ymmi2k)
ZEN5_FUNCDEF(vcmpps,				2zmmi2k)

ZEN5_FUNCDEF(vcmpsd,				2xmmi2k)
ZEN5_FUNCDEF(vcmppd,				2xmmi2k)
ZEN5_FUNCDEF(vcmppd,				2ymmi2k)
ZEN5_FUNCDEF(vcmppd,				2zmmi2k)

ZEN5_FUNCDEF(vfpclassss,			xmmi2k)
ZEN5_FUNCDEF(vfpclassps,			xmmi2k)
ZEN5_FUNCDEF(vfpclassps,			ymmi2k)
ZEN5_FUNCDEF(vfpclassps,			zmmi2k)

ZEN5_FUNCDEF(vfpclasssd,			xmmi2k)
ZEN5_FUNCDEF(vfpclasspd,			xmmi2k)
ZEN5_FUNCDEF(vfpclasspd,			ymmi2k)
ZEN5_FUNCDEF(vfpclasspd,			zmmi2k)

ZEN5_FUNCDEF(vpmovb2m,				xmm2k)
ZEN5_FUNCDEF(vpmovb2m,				ymm2k)
ZEN5_FUNCDEF(vpmovb2m,				zmm2k)
ZEN5_FUNCDEF(vpmovw2m,				xmm2k)
ZEN5_FUNCDEF(vpmovw2m,				ymm2k)
ZEN5_FUNCDEF(vpmovw2m,				zmm2k)
ZEN5_FUNCDEF(vpmovd2m,				xmm2k)
ZEN5_FUNCDEF(vpmovd2m,				ymm2k)
ZEN5_FUNCDEF(vpmovd2m,				zmm2k)
ZEN5_FUNCDEF(vpmovq2m,				xmm2k)
ZEN5_FUNCDEF(vpmovq2m,				ymm2k)
ZEN5_FUNCDEF(vpmovq2m,				zmm2k)

ZEN5_FUNCDEF(vpmovm2b,				k2xmm)
ZEN5_FUNCDEF(vpmovm2b,				k2ymm)
ZEN5_FUNCDEF(vpmovm2b,				k2zmm)
ZEN5_FUNCDEF(vpmovm2w,				k2xmm)
ZEN5_FUNCDEF(vpmovm2w,				k2ymm)
ZEN5_FUNCDEF(vpmovm2w,				k2zmm)
ZEN5_FUNCDEF(vpmovm2d,				k2xmm)
ZEN5_FUNCDEF(vpmovm2d,				k2ymm)
ZEN5_FUNCDEF(vpmovm2d,				k2zmm)
ZEN5_FUNCDEF(vpmovm2q,				k2xmm)
ZEN5_FUNCDEF(vpmovm2q,				k2ymm)
ZEN5_FUNCDEF(vpmovm2q,				k2zmm)

ZEN5_FUNCDEF(vpbroadcastmb2q,		k2xmm)
ZEN5_FUNCDEF(vpbroadcastmb2q,		k2ymm)
ZEN5_FUNCDEF(vpbroadcastmb2q,		k2zmm)
ZEN5_FUNCDEF(vpbroadcastmw2d,		k2xmm)
ZEN5_FUNCDEF(vpbroadcastmw2d,		k2ymm)
ZEN5_FUNCDEF(vpbroadcastmw2d,		k2zmm)

ZEN5_FUNCDEF(vpermilpd,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpermilpd,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpermilpd,				zmmi2zmm)

ZEN5_FUNCDEF(vpermilps,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpermilps,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpermilps,				zmmi2zmm)

ZEN5_FUNCDEF(vpunpcklbw,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpcklbw,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpcklbw,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpckhbw,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpckhbw,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpckhbw,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpcklwd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpcklwd,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpcklwd,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpckhwd,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpckhwd,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpckhwd,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpckldq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpckldq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpckldq,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpckhdq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpckhdq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpckhdq,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpcklqdq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpcklqdq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpcklqdq,			2zmm2zmm)

ZEN5_FUNCDEF(vpunpckhqdq,			evex_2xmm2xmm)
ZEN5_FUNCDEF(vpunpckhqdq,			evex_2ymm2ymm)
ZEN5_FUNCDEF(vpunpckhqdq,			2zmm2zmm)

ZEN5_FUNCDEF(vunpcklps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vunpcklps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vunpcklps,				2zmm2zmm)

ZEN5_FUNCDEF(vunpckhps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vunpckhps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vunpckhps,				2zmm2zmm)

ZEN5_FUNCDEF(vunpcklpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vunpcklpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vunpcklpd,				2zmm2zmm)

ZEN5_FUNCDEF(vunpckhpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vunpckhpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vunpckhpd,				2zmm2zmm)

ZEN5_FUNCDEF(vmovhlps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vmovlhps,				evex_2xmm2xmm)
	
ZEN5_FUNCDEF(vshufpd,				evex_2xmmi2xmm)
ZEN5_FUNCDEF(vshufpd,				evex_2ymmi2ymm)
ZEN5_FUNCDEF(vshufpd,				2zmmi2zmm)

ZEN5_FUNCDEF(vshufps,				evex_2xmmi2xmm)
ZEN5_FUNCDEF(vshufps,				evex_2ymmi2ymm)
ZEN5_FUNCDEF(vshufps,				2zmmi2zmm)

ZEN5_FUNCDEF(vpshuflw,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpshuflw,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpshuflw,				zmmi2zmm)

ZEN5_FUNCDEF(vpshufhw,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpshufhw,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpshufhw,				zmmi2zmm)

ZEN5_FUNCDEF(vpshufd,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vpshufd,				evex_ymmi2ymm)
ZEN5_FUNCDEF(vpshufd,				zmmi2zmm)

ZEN5_FUNCDEF(vmovsldup,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovsldup,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovsldup,				zmm2zmm)

ZEN5_FUNCDEF(vmovshdup,				evex_xmm2xmm)
ZEN5_FUNCDEF(vmovshdup,				evex_ymm2ymm)
ZEN5_FUNCDEF(vmovshdup,				zmm2zmm)

ZEN5_FUNCDEF(vinsertps,				evex_2xmmi2xmm)

ZEN5_FUNCDEF(kandb,					2k2k)
ZEN5_FUNCDEF(kandw,					2k2k)
ZEN5_FUNCDEF(kandd,					2k2k)
ZEN5_FUNCDEF(kandq,					2k2k)
ZEN5_FUNCDEF(kandnb,				2k2k)
ZEN5_FUNCDEF(kandnw,				2k2k)
ZEN5_FUNCDEF(kandnd,				2k2k)
ZEN5_FUNCDEF(kandnq,				2k2k)
ZEN5_FUNCDEF(kandnb,				2k2kRot)
ZEN5_FUNCDEF(kandnw,				2k2kRot)
ZEN5_FUNCDEF(kandnd,				2k2kRot)
ZEN5_FUNCDEF(kandnq,				2k2kRot)
ZEN5_FUNCDEF(kaddb,					2k2k)
ZEN5_FUNCDEF(kaddw,					2k2k)
ZEN5_FUNCDEF(kaddd,					2k2k)
ZEN5_FUNCDEF(kaddq,					2k2k)
ZEN5_FUNCDEF(korb,					2k2k)
ZEN5_FUNCDEF(korw,					2k2k)
ZEN5_FUNCDEF(kord,					2k2k)
ZEN5_FUNCDEF(korq,					2k2k)
ZEN5_FUNCDEF(korb,					2k2kRot)
ZEN5_FUNCDEF(korw,					2k2kRot)
ZEN5_FUNCDEF(kord,					2k2kRot)
ZEN5_FUNCDEF(korq,					2k2kRot)
ZEN5_FUNCDEF(kxorb,					2k2k)
ZEN5_FUNCDEF(kxorw,					2k2k)
ZEN5_FUNCDEF(kxord,					2k2k)
ZEN5_FUNCDEF(kxorq,					2k2k)
ZEN5_FUNCDEF(kxorb,					2k2kRot)
ZEN5_FUNCDEF(kxorw,					2k2kRot)
ZEN5_FUNCDEF(kxord,					2k2kRot)
ZEN5_FUNCDEF(kxorq,					2k2kRot)
ZEN5_FUNCDEF(kxnorb,				2k2k)
ZEN5_FUNCDEF(kxnorw,				2k2k)
ZEN5_FUNCDEF(kxnord,				2k2k)
ZEN5_FUNCDEF(kxnorq,				2k2k)
ZEN5_FUNCDEF(kxnorb,				2k2kRot)
ZEN5_FUNCDEF(kxnorw,				2k2kRot)
ZEN5_FUNCDEF(kxnord,				2k2kRot)
ZEN5_FUNCDEF(kxnorq,				2k2kRot)
ZEN5_FUNCDEF(knotb,					k2k)
ZEN5_FUNCDEF(knotw,					k2k)
ZEN5_FUNCDEF(knotd,					k2k)
ZEN5_FUNCDEF(knotq,					k2k)
ZEN5_FUNCDEF(kmovb,					k2k)
ZEN5_FUNCDEF(kmovw,					k2k)
ZEN5_FUNCDEF(kmovd,					k2k)
ZEN5_FUNCDEF(kmovq,					k2k)

ZEN5_FUNCDEF(kshiftlb,				ki2k)
ZEN5_FUNCDEF(kshiftlw,				ki2k)
ZEN5_FUNCDEF(kshiftld,				ki2k)
ZEN5_FUNCDEF(kshiftlq,				ki2k)
ZEN5_FUNCDEF(kshiftrb,				ki2k)
ZEN5_FUNCDEF(kshiftrw,				ki2k)
ZEN5_FUNCDEF(kshiftrd,				ki2k)
ZEN5_FUNCDEF(kshiftrq,				ki2k)

ZEN5_FUNCDEF(ktestb,				2k2c)
ZEN5_FUNCDEF(ktestw,				2k2c)
ZEN5_FUNCDEF(ktestd,				2k2c)
ZEN5_FUNCDEF(ktestq,				2k2c)
ZEN5_FUNCDEF(kortestb,				2k2c)
ZEN5_FUNCDEF(kortestw,				2k2c)
ZEN5_FUNCDEF(kortestd,				2k2c)
ZEN5_FUNCDEF(kortestq,				2k2c)

ZEN5_FUNCDEF(vcvtps2dq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vcvtps2dq,				evex_ymm2ymm)
ZEN5_FUNCDEF(vcvtps2dq,				zmm2zmm)

ZEN5_FUNCDEF(vcvtpd2qq,				evex_xmm2xmm)
ZEN5_FUNCDEF(vcvtpd2qq,				evex_ymm2ymm)
ZEN5_FUNCDEF(vcvtpd2qq,				zmm2zmm)

ZEN5_FUNCDEF(vcvtps2pd,				evex_xmm2xmm)
ZEN5_FUNCDEF(vcvtps2pd,				evex_xmm2ymm)
ZEN5_FUNCDEF(vcvtps2pd,				ymm2zmm)

ZEN5_FUNCDEF(vcvtph2ps,				evex_xmm2xmm)
ZEN5_FUNCDEF(vcvtph2ps,				evex_xmm2ymm)
ZEN5_FUNCDEF(vcvtph2ps,				ymm2zmm)

ZEN5_FUNCDEF(vcvtpd2ps,				evex_xmm2xmm)
ZEN5_FUNCDEF(vcvtpd2ps,				evex_ymm2xmm)
ZEN5_FUNCDEF(vcvtpd2ps,				zmm2ymm)

ZEN5_FUNCDEF(vcvtps2ph,				evex_xmmi2xmm)
ZEN5_FUNCDEF(vcvtps2ph,				evex_ymmi2xmm)
ZEN5_FUNCDEF(vcvtps2ph,				zmmi2ymm)

ZEN5_FUNCDEF(vcvtneps2bf16,			xmm2xmm)
ZEN5_FUNCDEF(vcvtneps2bf16,			ymm2xmm)
ZEN5_FUNCDEF(vcvtneps2bf16,			zmm2ymm)

ZEN5_FUNCDEF(vcvtne2ps2bf16,		2xmm2xmm)
ZEN5_FUNCDEF(vcvtne2ps2bf16,		2ymm2ymm)
ZEN5_FUNCDEF(vcvtne2ps2bf16,		2zmm2zmm)

ZEN5_FUNCDEF(vdpbf16ps,				2xmm2xmm)
ZEN5_FUNCDEF(vdpbf16ps,				2ymm2ymm)
ZEN5_FUNCDEF(vdpbf16ps,				2zmm2zmm)

ZEN5_FUNCDEF(vpconflictd,			xmm2xmm)
ZEN5_FUNCDEF(vpconflictd,			ymm2ymm)
ZEN5_FUNCDEF(vpconflictd,			zmm2zmm)

ZEN5_FUNCDEF(vpconflictq,			xmm2xmm)
ZEN5_FUNCDEF(vpconflictq,			ymm2ymm)
ZEN5_FUNCDEF(vpconflictq,			zmm2zmm)

ZEN5_FUNCDEF(vpcompressb,			xmm2xmm)
ZEN5_FUNCDEF(vpcompressw,			xmm2xmm)
ZEN5_FUNCDEF(vpcompressd,			xmm2xmm)
ZEN5_FUNCDEF(vpcompressq,			xmm2xmm)
ZEN5_FUNCDEF(vcompressps,			xmm2xmm)
ZEN5_FUNCDEF(vcompresspd,			xmm2xmm)

ZEN5_FUNCDEF(vpexpandb,				xmm2xmm)
ZEN5_FUNCDEF(vpexpandw,				xmm2xmm)
ZEN5_FUNCDEF(vpexpandd,				xmm2xmm)
ZEN5_FUNCDEF(vpexpandq,				xmm2xmm)
ZEN5_FUNCDEF(vexpandps,				xmm2xmm)
ZEN5_FUNCDEF(vexpandpd,				xmm2xmm)

ZEN5_FUNCDEF(vpcompressb,			ymm2ymm)
ZEN5_FUNCDEF(vpcompressw,			ymm2ymm)
ZEN5_FUNCDEF(vpcompressd,			ymm2ymm)
ZEN5_FUNCDEF(vpcompressq,			ymm2ymm)
ZEN5_FUNCDEF(vcompressps,			ymm2ymm)
ZEN5_FUNCDEF(vcompresspd,			ymm2ymm)

ZEN5_FUNCDEF(vpexpandb,				ymm2ymm)
ZEN5_FUNCDEF(vpexpandw,				ymm2ymm)
ZEN5_FUNCDEF(vpexpandd,				ymm2ymm)
ZEN5_FUNCDEF(vpexpandq,				ymm2ymm)
ZEN5_FUNCDEF(vexpandps,				ymm2ymm)
ZEN5_FUNCDEF(vexpandpd,				ymm2ymm)

ZEN5_FUNCDEF(vpcompressb,			zmm2zmm)
ZEN5_FUNCDEF(vpcompressw,			zmm2zmm)
ZEN5_FUNCDEF(vpcompressd,			zmm2zmm)
ZEN5_FUNCDEF(vpcompressq,			zmm2zmm)
ZEN5_FUNCDEF(vcompressps,			zmm2zmm)
ZEN5_FUNCDEF(vcompresspd,			zmm2zmm)

ZEN5_FUNCDEF(vpexpandb,				zmm2zmm)
ZEN5_FUNCDEF(vpexpandw,				zmm2zmm)
ZEN5_FUNCDEF(vpexpandd,				zmm2zmm)
ZEN5_FUNCDEF(vpexpandq,				zmm2zmm)
ZEN5_FUNCDEF(vexpandps,				zmm2zmm)
ZEN5_FUNCDEF(vexpandpd,				zmm2zmm)

ZEN5_FUNCDEF(vpshufbitqmb,			2xmmk2k)
ZEN5_FUNCDEF(vpshufbitqmb,			2ymmk2k)
ZEN5_FUNCDEF(vpshufbitqmb,			2zmmk2k)

ZEN5_FUNCDEF(vptestmb,				2xmmk2k)
ZEN5_FUNCDEF(vptestmb,				2ymmk2k)
ZEN5_FUNCDEF(vptestmb,				2zmmk2k)
ZEN5_FUNCDEF(vptestmw,				2xmmk2k)
ZEN5_FUNCDEF(vptestmw,				2ymmk2k)
ZEN5_FUNCDEF(vptestmw,				2zmmk2k)
ZEN5_FUNCDEF(vptestmd,				2xmmk2k)
ZEN5_FUNCDEF(vptestmd,				2ymmk2k)
ZEN5_FUNCDEF(vptestmd,				2zmmk2k)
ZEN5_FUNCDEF(vptestmq,				2xmmk2k)
ZEN5_FUNCDEF(vptestmq,				2ymmk2k)
ZEN5_FUNCDEF(vptestmq,				2zmmk2k)

ZEN5_FUNCDEF(vptestnmb,				2xmmk2k)
ZEN5_FUNCDEF(vptestnmb,				2ymmk2k)
ZEN5_FUNCDEF(vptestnmb,				2zmmk2k)
ZEN5_FUNCDEF(vptestnmw,				2xmmk2k)
ZEN5_FUNCDEF(vptestnmw,				2ymmk2k)
ZEN5_FUNCDEF(vptestnmw,				2zmmk2k)
ZEN5_FUNCDEF(vptestnmd,				2xmmk2k)
ZEN5_FUNCDEF(vptestnmd,				2ymmk2k)
ZEN5_FUNCDEF(vptestnmd,				2zmmk2k)
ZEN5_FUNCDEF(vptestnmq,				2xmmk2k)
ZEN5_FUNCDEF(vptestnmq,				2ymmk2k)
ZEN5_FUNCDEF(vptestnmq,				2zmmk2k)

ZEN5_FUNCDEF(vpcmpeqb,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpeqb,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpeqb,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpeqw,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpeqw,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpeqw,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpeqd,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpeqd,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpeqd,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpeqq,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpeqq,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpeqq,				2zmmk2k)

ZEN5_FUNCDEF(vpcmpgtb,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpgtb,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpgtb,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpgtw,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpgtw,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpgtw,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpgtd,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpgtd,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpgtd,				2zmmk2k)
ZEN5_FUNCDEF(vpcmpgtq,				2xmmk2k)
ZEN5_FUNCDEF(vpcmpgtq,				2ymmk2k)
ZEN5_FUNCDEF(vpcmpgtq,				2zmmk2k)

ZEN5_FUNCDEF(vpcmpgtb,				2xmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtb,				2ymmk2kRot)
ZEN5_FUNCDEF(vpcmpgtb,				2zmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2xmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2ymmk2kRot)
ZEN5_FUNCDEF(vpcmpgtw,				2zmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2xmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2ymmk2kRot)
ZEN5_FUNCDEF(vpcmpgtd,				2zmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2xmmk2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2ymmk2kRot)
ZEN5_FUNCDEF(vpcmpgtq,				2zmmk2kRot)

ZEN5_FUNCDEF(vpcmpb,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpb,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpb,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpw,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpw,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpw,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpd,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpd,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpd,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpq,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpq,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpq,				2zmmik2k)

ZEN5_FUNCDEF(vpcmpub,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpub,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpub,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpuw,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpuw,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpuw,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpud,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpud,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpud,				2zmmik2k)
ZEN5_FUNCDEF(vpcmpuq,				2xmmik2k)
ZEN5_FUNCDEF(vpcmpuq,				2ymmik2k)
ZEN5_FUNCDEF(vpcmpuq,				2zmmik2k)

ZEN5_FUNCDEF(vcmpss,				2xmmik2k)
ZEN5_FUNCDEF(vcmpps,				2xmmik2k)
ZEN5_FUNCDEF(vcmpps,				2ymmik2k)
ZEN5_FUNCDEF(vcmpps,				2zmmik2k)

ZEN5_FUNCDEF(vcmpsd,				2xmmik2k)
ZEN5_FUNCDEF(vcmppd,				2xmmik2k)
ZEN5_FUNCDEF(vcmppd,				2ymmik2k)
ZEN5_FUNCDEF(vcmppd,				2zmmik2k)

ZEN5_FUNCDEF(vfpclassss,			xmmik2k)
ZEN5_FUNCDEF(vfpclassps,			xmmik2k)
ZEN5_FUNCDEF(vfpclassps,			ymmik2k)
ZEN5_FUNCDEF(vfpclassps,			zmmik2k)

ZEN5_FUNCDEF(vfpclasssd,			xmmik2k)
ZEN5_FUNCDEF(vfpclasspd,			xmmik2k)
ZEN5_FUNCDEF(vfpclasspd,			ymmik2k)
ZEN5_FUNCDEF(vfpclasspd,			zmmik2k)

ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2xmm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2ymm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2zmm)

ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2xmm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2ymm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2zmm)

ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2xmm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2ymm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2zmm)

ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2xmm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2ymm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2zmm)

ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2kxmm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2kymm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2kzmm)

ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2kxmm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2kymm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2kzmm)

ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2kxmm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2kymm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2kzmm)

ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2kxmm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2kymm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2kzmm)

ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2zkxmm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2zkymm)
ZEN5_FUNCDEF(vpbroadcastb,			gpr32_2zkzmm)

ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2zkxmm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2zkymm)
ZEN5_FUNCDEF(vpbroadcastw,			gpr32_2zkzmm)

ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2zkxmm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2zkymm)
ZEN5_FUNCDEF(vpbroadcastd,			gpr32_2zkzmm)

ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2zkxmm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2zkymm)
ZEN5_FUNCDEF(vpbroadcastq,			gpr64_2zkzmm)

ZEN5_FUNCDEF(vpandnd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpandnd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpandnd,				2zmm2zmm)
ZEN5_FUNCDEF(vpandnq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpandnq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpandnq,				2zmm2zmm)
ZEN5_FUNCDEF(vpandd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpandd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpandd,				2zmm2zmm)
ZEN5_FUNCDEF(vpandq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpandq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpandq,				2zmm2zmm)

ZEN5_FUNCDEF(vpandnd,				2xmm2kxmm)
ZEN5_FUNCDEF(vpandnd,				2ymm2kymm)
ZEN5_FUNCDEF(vpandnd,				2zmm2kzmm)
ZEN5_FUNCDEF(vpandnq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpandnq,				2ymm2kymm)
ZEN5_FUNCDEF(vpandnq,				2zmm2kzmm)
ZEN5_FUNCDEF(vpandd,				2xmm2kxmm)
ZEN5_FUNCDEF(vpandd,				2ymm2kymm)
ZEN5_FUNCDEF(vpandd,				2zmm2kzmm)
ZEN5_FUNCDEF(vpandq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpandq,				2ymm2kymm)
ZEN5_FUNCDEF(vpandq,				2zmm2kzmm)

ZEN5_FUNCDEF(vpandnd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpandnd,				2ymm2zkymm)
ZEN5_FUNCDEF(vpandnd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpandnq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpandnq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpandnq,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpandd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpandd,				2ymm2zkymm)
ZEN5_FUNCDEF(vpandd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpandq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpandq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpandq,				2zmm2zkzmm)

ZEN5_FUNCDEF(vpxord,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpxord,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpxord,				2zmm2zmm)
ZEN5_FUNCDEF(vpxorq,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vpxorq,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vpxorq,				2zmm2zmm)
ZEN5_FUNCDEF(vpord,					evex_2xmm2xmm)
ZEN5_FUNCDEF(vpord,					evex_2ymm2ymm)
ZEN5_FUNCDEF(vpord,					2zmm2zmm)
ZEN5_FUNCDEF(vporq,					evex_2xmm2xmm)
ZEN5_FUNCDEF(vporq,					evex_2ymm2ymm)
ZEN5_FUNCDEF(vporq,					2zmm2zmm)

ZEN5_FUNCDEF(vpxord,				2xmm2kxmm)
ZEN5_FUNCDEF(vpxord,				2ymm2kymm)
ZEN5_FUNCDEF(vpxord,				2zmm2kzmm)
ZEN5_FUNCDEF(vpxorq,				2xmm2kxmm)
ZEN5_FUNCDEF(vpxorq,				2ymm2kymm)
ZEN5_FUNCDEF(vpxorq,				2zmm2kzmm)
ZEN5_FUNCDEF(vpord,					2xmm2kxmm)
ZEN5_FUNCDEF(vpord,					2ymm2kymm)
ZEN5_FUNCDEF(vpord,					2zmm2kzmm)
ZEN5_FUNCDEF(vporq,					2xmm2kxmm)
ZEN5_FUNCDEF(vporq,					2ymm2kymm)
ZEN5_FUNCDEF(vporq,					2zmm2kzmm)

ZEN5_FUNCDEF(vpxord,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpxord,				2ymm2zkymm)
ZEN5_FUNCDEF(vpxord,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpxorq,				2xmm2zkxmm)
ZEN5_FUNCDEF(vpxorq,				2ymm2zkymm)
ZEN5_FUNCDEF(vpxorq,				2zmm2zkzmm)
ZEN5_FUNCDEF(vpord,					2xmm2zkxmm)
ZEN5_FUNCDEF(vpord,					2ymm2zkymm)
ZEN5_FUNCDEF(vpord,					2zmm2zkzmm)
ZEN5_FUNCDEF(vporq,					2xmm2zkxmm)
ZEN5_FUNCDEF(vporq,					2ymm2zkymm)
ZEN5_FUNCDEF(vporq,					2zmm2zkzmm)

ZEN5_FUNCDEF(vandnps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vandnps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vandnps,				2zmm2zmm)
ZEN5_FUNCDEF(vandnpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vandnpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vandnpd,				2zmm2zmm)
ZEN5_FUNCDEF(vandps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vandps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vandps,				2zmm2zmm)
ZEN5_FUNCDEF(vandpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vandpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vandpd,				2zmm2zmm)

ZEN5_FUNCDEF(vandnps,				2xmm2kxmm)
ZEN5_FUNCDEF(vandnps,				2ymm2kymm)
ZEN5_FUNCDEF(vandnps,				2zmm2kzmm)
ZEN5_FUNCDEF(vandnpd,				2xmm2kxmm)
ZEN5_FUNCDEF(vandnpd,				2ymm2kymm)
ZEN5_FUNCDEF(vandnpd,				2zmm2kzmm)
ZEN5_FUNCDEF(vandps,				2xmm2kxmm)
ZEN5_FUNCDEF(vandps,				2ymm2kymm)
ZEN5_FUNCDEF(vandps,				2zmm2kzmm)
ZEN5_FUNCDEF(vandpd,				2xmm2kxmm)
ZEN5_FUNCDEF(vandpd,				2ymm2kymm)
ZEN5_FUNCDEF(vandpd,				2zmm2kzmm)

ZEN5_FUNCDEF(vandnps,				2xmm2zkxmm)
ZEN5_FUNCDEF(vandnps,				2ymm2zkymm)
ZEN5_FUNCDEF(vandnps,				2zmm2zkzmm)
ZEN5_FUNCDEF(vandnpd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vandnpd,				2ymm2zkymm)
ZEN5_FUNCDEF(vandnpd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vandps,				2xmm2zkxmm)
ZEN5_FUNCDEF(vandps,				2ymm2zkymm)
ZEN5_FUNCDEF(vandps,				2zmm2zkzmm)
ZEN5_FUNCDEF(vandpd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vandpd,				2ymm2zkymm)
ZEN5_FUNCDEF(vandpd,				2zmm2zkzmm)

ZEN5_FUNCDEF(vxorps,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vxorps,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vxorps,				2zmm2zmm)
ZEN5_FUNCDEF(vxorpd,				evex_2xmm2xmm)
ZEN5_FUNCDEF(vxorpd,				evex_2ymm2ymm)
ZEN5_FUNCDEF(vxorpd,				2zmm2zmm)
ZEN5_FUNCDEF(vorps,					evex_2xmm2xmm)
ZEN5_FUNCDEF(vorps,					evex_2ymm2ymm)
ZEN5_FUNCDEF(vorps,					2zmm2zmm)
ZEN5_FUNCDEF(vorpd,					evex_2xmm2xmm)
ZEN5_FUNCDEF(vorpd,					evex_2ymm2ymm)
ZEN5_FUNCDEF(vorpd,					2zmm2zmm)

ZEN5_FUNCDEF(vxorps,				2xmm2kxmm)
ZEN5_FUNCDEF(vxorps,				2ymm2kymm)
ZEN5_FUNCDEF(vxorps,				2zmm2kzmm)
ZEN5_FUNCDEF(vxorpd,				2xmm2kxmm)
ZEN5_FUNCDEF(vxorpd,				2ymm2kymm)
ZEN5_FUNCDEF(vxorpd,				2zmm2kzmm)
ZEN5_FUNCDEF(vorps,					2xmm2kxmm)
ZEN5_FUNCDEF(vorps,					2ymm2kymm)
ZEN5_FUNCDEF(vorps,					2zmm2kzmm)
ZEN5_FUNCDEF(vorpd,					2xmm2kxmm)
ZEN5_FUNCDEF(vorpd,					2ymm2kymm)
ZEN5_FUNCDEF(vorpd,					2zmm2kzmm)

ZEN5_FUNCDEF(vxorps,				2xmm2zkxmm)
ZEN5_FUNCDEF(vxorps,				2ymm2zkymm)
ZEN5_FUNCDEF(vxorps,				2zmm2zkzmm)
ZEN5_FUNCDEF(vxorpd,				2xmm2zkxmm)
ZEN5_FUNCDEF(vxorpd,				2ymm2zkymm)
ZEN5_FUNCDEF(vxorpd,				2zmm2zkzmm)
ZEN5_FUNCDEF(vorps,					2xmm2zkxmm)
ZEN5_FUNCDEF(vorps,					2ymm2zkymm)
ZEN5_FUNCDEF(vorps,					2zmm2zkzmm)
ZEN5_FUNCDEF(vorpd,					2xmm2zkxmm)
ZEN5_FUNCDEF(vorpd,					2ymm2zkymm)
ZEN5_FUNCDEF(vorpd,					2zmm2zkzmm)

ZEN5_FUNCDEF(kmovb,					gpr32_2k)
ZEN5_FUNCDEF(kmovw,					gpr32_2k)
ZEN5_FUNCDEF(kmovd,					gpr32_2k)
ZEN5_FUNCDEF(kmovq,					gpr64_2k)

ZEN5_FUNCDEF(kmovb,					k2gpr32)
ZEN5_FUNCDEF(kmovw,					k2gpr32)
ZEN5_FUNCDEF(kmovd,					k2gpr32)
ZEN5_FUNCDEF(kmovq,					k2gpr64)
