#pragma once

ZEN5_FUNCDEF(nop,				noop)
ZEN5_FUNCDEF(lnop2,				noop)
ZEN5_FUNCDEF(lnop3,				noop)
ZEN5_FUNCDEF(lnop4,				noop)
ZEN5_FUNCDEF(lnop5,				noop)
ZEN5_FUNCDEF(lnop6,				noop)
ZEN5_FUNCDEF(lnop7,				noop)
ZEN5_FUNCDEF(lnop8,				noop)
ZEN5_FUNCDEF(lnop9,				noop)
ZEN5_FUNCDEF(lnop10,			noop)
ZEN5_FUNCDEF(lnop11,			noop)
ZEN5_FUNCDEF(lnop12,			noop)
ZEN5_FUNCDEF(lnop13,			noop)
ZEN5_FUNCDEF(lnop14,			noop)
ZEN5_FUNCDEF(lnop15,			noop)

ZEN5_FUNCDEF(movaps,			xmm2xmm)
ZEN5_FUNCDEF(movapd,			xmm2xmm)
ZEN5_FUNCDEF(movups,			xmm2xmm)
ZEN5_FUNCDEF(movupd,			xmm2xmm)
ZEN5_FUNCDEF(movdqa,			xmm2xmm)
ZEN5_FUNCDEF(movdqu,			xmm2xmm)

ZEN5_FUNCDEF(mulpd,				xmm2xmm)
ZEN5_FUNCDEF(mulps,				xmm2xmm)
ZEN5_FUNCDEF(mulsd,				xmm2xmm)
ZEN5_FUNCDEF(mulss,				xmm2xmm)
ZEN5_FUNCDEF(rcpps,				xmm2xmm)
ZEN5_FUNCDEF(rcpss,				xmm2xmm)
ZEN5_FUNCDEF(rsqrtps,			xmm2xmm)
ZEN5_FUNCDEF(rsqrtss,			xmm2xmm)
ZEN5_FUNCDEF(pblendvb,			xmm0_2xmm)
ZEN5_FUNCDEF(blendvpd,			xmm0_2xmm)
ZEN5_FUNCDEF(blendvps,			xmm0_2xmm)

ZEN5_FUNCDEF(addpd,				xmm2xmm)
ZEN5_FUNCDEF(addps,				xmm2xmm)
ZEN5_FUNCDEF(addsd,				xmm2xmm)
ZEN5_FUNCDEF(addss,				xmm2xmm)
ZEN5_FUNCDEF(subpd,				xmm2xmm)
ZEN5_FUNCDEF(subps,				xmm2xmm)
ZEN5_FUNCDEF(subsd,				xmm2xmm)
ZEN5_FUNCDEF(subss,				xmm2xmm)
ZEN5_FUNCDEF(addsubpd,			xmm2xmm)
ZEN5_FUNCDEF(addsubps,			xmm2xmm)
ZEN5_FUNCDEF(roundpd,			xmmi2xmm)
ZEN5_FUNCDEF(roundps,			xmmi2xmm)
ZEN5_FUNCDEF(roundsd,			xmmi2xmm)
ZEN5_FUNCDEF(roundss,			xmmi2xmm)
ZEN5_FUNCDEF(cvtps2dq,			xmm2xmm)
ZEN5_FUNCDEF(cvtps2pd,			xmm2xmm)
ZEN5_FUNCDEF(cvtpd2ps,			xmm2xmm)
ZEN5_FUNCDEF(cvtpd2dq,			xmm2xmm)
ZEN5_FUNCDEF(cvtdq2pd,			xmm2xmm)
ZEN5_FUNCDEF(cvtdq2ps,			xmm2xmm)
ZEN5_FUNCDEF(cvtss2sd,			xmm2xmm)
ZEN5_FUNCDEF(cvtsd2ss,			xmm2xmm)

ZEN5_FUNCDEF(minpd,				xmm2xmm)
ZEN5_FUNCDEF(minps,				xmm2xmm)
ZEN5_FUNCDEF(minsd,				xmm2xmm)
ZEN5_FUNCDEF(minss,				xmm2xmm)
ZEN5_FUNCDEF(maxpd,				xmm2xmm)
ZEN5_FUNCDEF(maxps,				xmm2xmm)
ZEN5_FUNCDEF(maxsd,				xmm2xmm)
ZEN5_FUNCDEF(maxss,				xmm2xmm)
ZEN5_FUNCDEF(cmpeqpd,			xmm2xmm)
ZEN5_FUNCDEF(cmpeqps,			xmm2xmm)
ZEN5_FUNCDEF(cmpeqsd,			xmm2xmm)
ZEN5_FUNCDEF(cmpeqss,			xmm2xmm)

ZEN5_FUNCDEF(andpd,				xmm2xmm)
ZEN5_FUNCDEF(andps,				xmm2xmm)
ZEN5_FUNCDEF(andnpd,			xmm2xmmRot)
ZEN5_FUNCDEF(andnps,			xmm2xmmRot)
ZEN5_FUNCDEF(orpd,				xmm2xmm)
ZEN5_FUNCDEF(orps,				xmm2xmm)
ZEN5_FUNCDEF(xorpd,				xmm2xmmRot)
ZEN5_FUNCDEF(xorps,				xmm2xmmRot)
ZEN5_FUNCDEF(blendpd,			xmmi2xmm)
ZEN5_FUNCDEF(blendps,			xmmi2xmm)

ZEN5_FUNCDEF(pand,				xmm2xmm)
ZEN5_FUNCDEF(pandn,				xmm2xmm)
ZEN5_FUNCDEF(pandn,				xmm2xmmRot)
ZEN5_FUNCDEF(por,				xmm2xmm)
ZEN5_FUNCDEF(pxor,				xmm2xmm)
ZEN5_FUNCDEF(pxor,				xmm2xmmRot)
ZEN5_FUNCDEF(pblendw,			xmmi2xmm)

ZEN5_FUNCDEF(paddb,				xmm2xmm)
ZEN5_FUNCDEF(paddw,				xmm2xmm)
ZEN5_FUNCDEF(paddd,				xmm2xmm)
ZEN5_FUNCDEF(paddq,				xmm2xmm)
ZEN5_FUNCDEF(psubb,				xmm2xmmRot)
ZEN5_FUNCDEF(psubw,				xmm2xmmRot)
ZEN5_FUNCDEF(psubd,				xmm2xmmRot)
ZEN5_FUNCDEF(psubq,				xmm2xmmRot)

ZEN5_FUNCDEF(pcmpeqb,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpeqw,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpeqd,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpgtb,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpgtw,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpgtd,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpgtq,			xmm2xmmRot)

ZEN5_FUNCDEF(pminsb,			xmm2xmm)
ZEN5_FUNCDEF(pminub,			xmm2xmm)
ZEN5_FUNCDEF(pminsw,			xmm2xmm)
ZEN5_FUNCDEF(pminuw,			xmm2xmm)
ZEN5_FUNCDEF(pminsd,			xmm2xmm)
ZEN5_FUNCDEF(pminud,			xmm2xmm)
ZEN5_FUNCDEF(pmaxsb,			xmm2xmm)
ZEN5_FUNCDEF(pmaxub,			xmm2xmm)
ZEN5_FUNCDEF(pmaxsw,			xmm2xmm)
ZEN5_FUNCDEF(pmaxuw,			xmm2xmm)
ZEN5_FUNCDEF(pmaxsd,			xmm2xmm)
ZEN5_FUNCDEF(pmaxud,			xmm2xmm)

ZEN5_FUNCDEF(paddsb,			xmm2xmm)
ZEN5_FUNCDEF(paddsw,			xmm2xmm)
ZEN5_FUNCDEF(psubsb,			xmm2xmmRot)
ZEN5_FUNCDEF(psubsw,			xmm2xmmRot)
ZEN5_FUNCDEF(pcmpeqq,			xmm2xmmRot)
ZEN5_FUNCDEF(pabsb,				xmm2xmm)
ZEN5_FUNCDEF(pabsw,				xmm2xmm)
ZEN5_FUNCDEF(pabsd,				xmm2xmm)
ZEN5_FUNCDEF(pavgb,				xmm2xmm)
ZEN5_FUNCDEF(pavgw,				xmm2xmm)
ZEN5_FUNCDEF(psignb,			xmm2xmm)
ZEN5_FUNCDEF(psignw,			xmm2xmm)
ZEN5_FUNCDEF(psignd,			xmm2xmm)

ZEN5_FUNCDEF(aesenc,			xmm2xmm)
ZEN5_FUNCDEF(aesenclast,		xmm2xmm)
ZEN5_FUNCDEF(aesdec,			xmm2xmm)
ZEN5_FUNCDEF(aesdeclast,		xmm2xmm)
ZEN5_FUNCDEF(aesenc,			xmm2xmmRot)
ZEN5_FUNCDEF(aesenclast,		xmm2xmmRot)
ZEN5_FUNCDEF(aesdec,			xmm2xmmRot)
ZEN5_FUNCDEF(aesdeclast,		xmm2xmmRot)
ZEN5_FUNCDEF(aesimc,			xmm2xmm)
ZEN5_FUNCDEF(aeskeygenassist,	xmmi2xmm)
ZEN5_FUNCDEF(phminposuw,		xmm2xmm)
ZEN5_FUNCDEF(extrq,				xmm2xmm)
ZEN5_FUNCDEF(insertq	,		xmm2xmm)

ZEN5_FUNCDEF(psllw,				xmm2xmm)
ZEN5_FUNCDEF(psrlw,				xmm2xmm)
ZEN5_FUNCDEF(psraw,				xmm2xmm)
ZEN5_FUNCDEF(pslld,				xmm2xmm)
ZEN5_FUNCDEF(psrld,				xmm2xmm)
ZEN5_FUNCDEF(psrad,				xmm2xmm)
ZEN5_FUNCDEF(psllq,				xmm2xmm)
ZEN5_FUNCDEF(psrlq,				xmm2xmm)

ZEN5_FUNCDEF(psllw,				i2xmm)	
ZEN5_FUNCDEF(psrlw,				i2xmm)	
ZEN5_FUNCDEF(psraw,				i2xmm)	
ZEN5_FUNCDEF(pslld,				i2xmm)	
ZEN5_FUNCDEF(psrld,				i2xmm)	
ZEN5_FUNCDEF(psrad,				i2xmm)	
ZEN5_FUNCDEF(psllq,				i2xmm)	
ZEN5_FUNCDEF(psrlq,				i2xmm)	

ZEN5_FUNCDEF(pslldq,			i2xmm)	
ZEN5_FUNCDEF(psrldq,			i2xmm)	

ZEN5_FUNCDEF(punpcklbw,			xmm2xmm)
ZEN5_FUNCDEF(punpckhbw,			xmm2xmm)
ZEN5_FUNCDEF(punpcklwd,			xmm2xmm)
ZEN5_FUNCDEF(punpckhwd,			xmm2xmm)
ZEN5_FUNCDEF(punpckldq,			xmm2xmm)
ZEN5_FUNCDEF(punpckhdq,			xmm2xmm)
ZEN5_FUNCDEF(punpcklqdq,		xmm2xmm)
ZEN5_FUNCDEF(punpckhqdq,		xmm2xmm)
ZEN5_FUNCDEF(unpcklps,			xmm2xmm)
ZEN5_FUNCDEF(unpckhps,			xmm2xmm)
ZEN5_FUNCDEF(unpcklpd,			xmm2xmm)
ZEN5_FUNCDEF(unpckhpd,			xmm2xmm)
ZEN5_FUNCDEF(movhlps,			xmm2xmm)
ZEN5_FUNCDEF(movlhps,			xmm2xmm)
ZEN5_FUNCDEF(packsswb,			xmm2xmm)
ZEN5_FUNCDEF(packuswb,			xmm2xmm)
ZEN5_FUNCDEF(packssdw,			xmm2xmm)
ZEN5_FUNCDEF(packusdw,			xmm2xmm)
ZEN5_FUNCDEF(shufpd,			xmmi2xmm)
ZEN5_FUNCDEF(shufps,			xmmi2xmm)
ZEN5_FUNCDEF(pshufb,			xmm2xmm)
ZEN5_FUNCDEF(pshuflw,			xmmi2xmm)
ZEN5_FUNCDEF(pshufhw,			xmmi2xmm)
ZEN5_FUNCDEF(pshufd,			xmmi2xmm)
ZEN5_FUNCDEF(palignr,			xmmi2xmm)
ZEN5_FUNCDEF(movddup,			xmm2xmm)
ZEN5_FUNCDEF(movsldup,			xmm2xmm)
ZEN5_FUNCDEF(movshdup,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxbw,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxbd,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxbq,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxwd,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxwq,			xmm2xmm)
ZEN5_FUNCDEF(pmovzxdq,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxbw,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxbd,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxbq,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxwd,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxwq,			xmm2xmm)
ZEN5_FUNCDEF(pmovsxdq,			xmm2xmm)
ZEN5_FUNCDEF(insertps,			xmmi2xmm)

ZEN5_FUNCDEF(pmulhw,			xmm2xmm)
ZEN5_FUNCDEF(pmulhuw,			xmm2xmm)
ZEN5_FUNCDEF(pmulhrsw,			xmm2xmm)
ZEN5_FUNCDEF(pmullw,			xmm2xmm)
ZEN5_FUNCDEF(pmulld,			xmm2xmm)
ZEN5_FUNCDEF(pmuldq,			xmm2xmm)
ZEN5_FUNCDEF(pmuludq,			xmm2xmm)
ZEN5_FUNCDEF(pmaddwd,			xmm2xmm)
ZEN5_FUNCDEF(pmaddubsw,			xmm2xmm)
ZEN5_FUNCDEF(psadbw,			xmm2xmm)

ZEN5_FUNCDEF(divpd,				xmm2xmm2)
ZEN5_FUNCDEF(divps,				xmm2xmm2)
ZEN5_FUNCDEF(divsd,				xmm2xmm2)
ZEN5_FUNCDEF(divss,				xmm2xmm2)
ZEN5_FUNCDEF(sqrtpd,			xmm2xmm1)
ZEN5_FUNCDEF(sqrtps,			xmm2xmm1)
ZEN5_FUNCDEF(sqrtsd,			xmm2xmm1)
ZEN5_FUNCDEF(sqrtss,			xmm2xmm1)

ZEN5_FUNCDEF(movd,				xmm2gpr32)
ZEN5_FUNCDEF(movd,				xmm2gpr64)
ZEN5_FUNCDEF(movd,				gpr32_2xmm)
ZEN5_FUNCDEF(movd,				gpr64_2xmm)
ZEN5_FUNCDEF(movq2dq,			mm2xmm)
ZEN5_FUNCDEF(movdq2q,			xmm2mm)

ZEN5_FUNCDEF(pextrb,			xmmi2gpr32)
ZEN5_FUNCDEF(pextrb,			xmmi2gpr64)
ZEN5_FUNCDEF(pextrw,			xmmi2gpr32)
ZEN5_FUNCDEF(pextrw,			xmmi2gpr64)
ZEN5_FUNCDEF(pextrd,			xmmi2gpr32)
ZEN5_FUNCDEF(pextrq,			xmmi2gpr64)
ZEN5_FUNCDEF(pinsrb,			gpr32i2xmm)
ZEN5_FUNCDEF(pinsrw,			gpr32i2xmm)
ZEN5_FUNCDEF(pinsrd,			gpr32i2xmm)
ZEN5_FUNCDEF(pinsrq,			gpr64i2xmm)

ZEN5_FUNCDEF(cvtss2si,			xmm2gpr32)
ZEN5_FUNCDEF(cvtss2si,			xmm2gpr64)
ZEN5_FUNCDEF(cvtsd2si,			xmm2gpr32)
ZEN5_FUNCDEF(cvtsd2si,			xmm2gpr64)
ZEN5_FUNCDEF(cvtsi2ss,			gpr32_2xmm)
ZEN5_FUNCDEF(cvtsi2ss,			gpr64_2xmm)
ZEN5_FUNCDEF(cvtsi2sd,			gpr32_2xmm)
ZEN5_FUNCDEF(cvtsi2sd,			gpr64_2xmm)
ZEN5_FUNCDEF(extractps,			xmmi2gpr32)

ZEN5_FUNCDEF(pmovmskb,			xmm2gpr32)
ZEN5_FUNCDEF(pmovmskb,			xmm2gpr64)

ZEN5_FUNCDEF(movmskpd,			xmm2gpr32)
ZEN5_FUNCDEF(movmskpd,			xmm2gpr64)

ZEN5_FUNCDEF(movmskps,			xmm2gpr32)
ZEN5_FUNCDEF(movmskps,			xmm2gpr64)

ZEN5_FUNCDEF(ptest,				xmm2F)	

ZEN5_FUNCDEF(comisd,			xmm2F)	
ZEN5_FUNCDEF(comiss,			xmm2F)	
ZEN5_FUNCDEF(ucomisd,			xmm2F)	
ZEN5_FUNCDEF(ucomiss,			xmm2F)	

ZEN5_FUNCDEF(haddpd,			xmm2xmm)
ZEN5_FUNCDEF(haddps,			xmm2xmm)
ZEN5_FUNCDEF(hsubpd,			xmm2xmm)
ZEN5_FUNCDEF(hsubps,			xmm2xmm)
ZEN5_FUNCDEF(phaddw,			xmm2xmm)
ZEN5_FUNCDEF(phaddd,			xmm2xmm)
ZEN5_FUNCDEF(phaddsw,			xmm2xmm)
ZEN5_FUNCDEF(phsubw,			xmm2xmm)
ZEN5_FUNCDEF(phsubd,			xmm2xmm)
ZEN5_FUNCDEF(phsubsw,			xmm2xmm)

ZEN5_FUNCDEF(dppd,				xmmi2xmm)
ZEN5_FUNCDEF(dpps,				xmmi2xmm)
ZEN5_FUNCDEF(pclmulqdq,			xmmi2xmm)
ZEN5_FUNCDEF(mpsadbw,			xmmi2xmm)
ZEN5_FUNCDEF(extrq,				ii2xmm)
ZEN5_FUNCDEF(insertq,			xmmii2xmm)

ZEN5_FUNCDEF(sha1msg1,			xmm2xmm)
ZEN5_FUNCDEF(sha1msg2,			xmm2xmm)
ZEN5_FUNCDEF(sha1nexte,			xmm2xmm)
ZEN5_FUNCDEF(sha1rnds4,			xmmi2xmm1)
ZEN5_FUNCDEF(sha256msg1,		xmm2xmm)
ZEN5_FUNCDEF(sha256msg2,		xmm2xmm)
ZEN5_FUNCDEF(sha256rnds2,		xmm0_2xmm1)

ZEN5_FUNCDEF(pcmpestri,			xmmi2xmm)
ZEN5_FUNCDEF(pcmpestrm,			xmmi2xmm)
ZEN5_FUNCDEF(pcmpistri,			xmmi2xmm)
ZEN5_FUNCDEF(pcmpistrm,			xmmi2xmm)

ZEN5_FUNCDEF(pand,				mm2mm)	
ZEN5_FUNCDEF(pandn,				mm2mm)	
ZEN5_FUNCDEF(pandn,				mm2mmRot)
ZEN5_FUNCDEF(por,				mm2mm)	
ZEN5_FUNCDEF(pxor,				mm2mm)	
ZEN5_FUNCDEF(pxor,				mm2mmRot)
ZEN5_FUNCDEF(paddb,				mm2mm)	
ZEN5_FUNCDEF(paddw,				mm2mm)	
ZEN5_FUNCDEF(paddd,				mm2mm)	
ZEN5_FUNCDEF(paddq,				mm2mm)	
ZEN5_FUNCDEF(psubb,				mm2mmRot)
ZEN5_FUNCDEF(psubw,				mm2mmRot)
ZEN5_FUNCDEF(psubd,				mm2mmRot)
ZEN5_FUNCDEF(psubq,				mm2mmRot)

ZEN5_FUNCDEF(paddsb,			mm2mm)
ZEN5_FUNCDEF(paddsw,			mm2mm)
ZEN5_FUNCDEF(psubsb,			mm2mmRot)
ZEN5_FUNCDEF(psubsw,			mm2mmRot)

ZEN5_FUNCDEF(pabsb,				mm2mm)
ZEN5_FUNCDEF(pabsw,				mm2mm)
ZEN5_FUNCDEF(pabsd,				mm2mm)
ZEN5_FUNCDEF(pavgb,				mm2mm)
ZEN5_FUNCDEF(pavgw,				mm2mm)
ZEN5_FUNCDEF(psignb,			mm2mm)
ZEN5_FUNCDEF(psignw,			mm2mm)
ZEN5_FUNCDEF(psignd,			mm2mm)

ZEN5_FUNCDEF(psllw,				mm2mm)
ZEN5_FUNCDEF(psrlw,				mm2mm)
ZEN5_FUNCDEF(psraw,				mm2mm)
ZEN5_FUNCDEF(pslld,				mm2mm)
ZEN5_FUNCDEF(psrld,				mm2mm)
ZEN5_FUNCDEF(psrad,				mm2mm)
ZEN5_FUNCDEF(psllq,				mm2mm)
ZEN5_FUNCDEF(psrlq,				mm2mm)

ZEN5_FUNCDEF(psllw,				i2mm)
ZEN5_FUNCDEF(psrlw,				i2mm)
ZEN5_FUNCDEF(psraw,				i2mm)
ZEN5_FUNCDEF(pslld,				i2mm)
ZEN5_FUNCDEF(psrld,				i2mm)
ZEN5_FUNCDEF(psrad,				i2mm)
ZEN5_FUNCDEF(psllq,				i2mm)
ZEN5_FUNCDEF(psrlq,				i2mm)

ZEN5_FUNCDEF(pshufw,			mmi2mm)
ZEN5_FUNCDEF(palignr,			mmi2mm)
ZEN5_FUNCDEF(punpcklbw,			mm2mm)
ZEN5_FUNCDEF(punpckhbw,			mm2mm)
ZEN5_FUNCDEF(punpcklwd,			mm2mm)
ZEN5_FUNCDEF(punpckhwd,			mm2mm)
ZEN5_FUNCDEF(punpckldq,			mm2mm)
ZEN5_FUNCDEF(punpckhdq,			mm2mm)
ZEN5_FUNCDEF(packsswb,			mm2mm)
ZEN5_FUNCDEF(packuswb,			mm2mm)
ZEN5_FUNCDEF(packssdw,			mm2mm)

ZEN5_FUNCDEF(pmulhw,			mm2mm)
ZEN5_FUNCDEF(pmulhuw,			mm2mm)
ZEN5_FUNCDEF(pmullw,			mm2mm)
ZEN5_FUNCDEF(pmuludq,			mm2mm)
ZEN5_FUNCDEF(pmaddwd,			mm2mm)

ZEN5_FUNCDEF(pmovmskb,			mm2gpr32)
ZEN5_FUNCDEF(movd,				mm2gpr32)
ZEN5_FUNCDEF(movd,				gpr32_2mm)
ZEN5_FUNCDEF(pextrw,			mmi2gpr32)
ZEN5_FUNCDEF(pinsrw,			gpr32i2mm)

ZEN5_FUNCDEF(movq2dq,			mm2xmm)
ZEN5_FUNCDEF(movdq2q,			xmm2mm)
ZEN5_FUNCDEF(cvtps2pi,			xmm2mm)
ZEN5_FUNCDEF(cvtpd2pi,			xmm2mm)
ZEN5_FUNCDEF(cvtpi2ps,			mm2xmm)
ZEN5_FUNCDEF(cvtpi2pd,			mm2xmm)

ZEN5_FUNCDEF(,					mm2xmm)
